(function(g){var window=this;'use strict';var mE=function(S){S.publish("cardstatechange",S.e1()&&S.Je()?1:0)},ab=function(S,W){var m=g.NP(W);
const a=m?W:arguments;for(m=m?0:1;m<a.length;m++){if(S==null)return;S=S[a[m]]}return S},Z6H=function(S){const W=g.Wr(S);
S=g.yE(S);return new g.h8(W.x,W.y,S.width,S.height)},N78=function(S,W,m){let a;
return a=g.wd(S,W,function(){g.S0(a);m.apply(S,arguments)},{})},E0=function(S){S=g.c_(S);
delete J1[S];g.Sm(J1)&&Bx&&Bx.stop()},oX9=function(){Bx||(Bx=new g.rr(function(){b69()},20));
const S=Bx;S.isActive()||S.start()},b69=function(){var S=g.S$();
g.EP(J1,function(W){rGp(W,S)});
g.Sm(J1)||oX9()},z2=function(S,W,m,a){g.zc.call(this);
if(!Array.isArray(S)||!Array.isArray(W))throw Error("Start and end parameters must be arrays");if(S.length!=W.length)throw Error("Start and end points must be the same length");this.N=S;this.V=W;this.duration=m;this.A=a;this.coords=[];this.progress=this.W=0;this.j=null},rGp=function(S,W){W<S.startTime&&(S.endTime=W+S.endTime-S.startTime,S.startTime=W);
S.progress=(W-S.startTime)/(S.endTime-S.startTime);S.progress>1&&(S.progress=1);S.W=1E3/(W-S.j);S.j=W;Cc9(S,S.progress);S.progress==1?(S.C=0,E0(S),S.onFinish(),S.mP()):S.isPlaying()&&S.c_()},Cc9=function(S,W){typeof S.A==="function"&&(W=S.A(W));
S.coords=Array(S.N.length);for(let m=0;m<S.N.length;m++)S.coords[m]=(S.V[m]-S.N[m])*W+S.N[m]},cGv=function(S,W){g.BH.call(this,S);
this.coords=W.coords;this.x=W.coords[0];this.y=W.coords[1];this.z=W.coords[2];this.duration=W.duration;this.progress=W.progress;this.fps=W.W;this.state=W.C},yy=function(S,W,m,a,J){z2.call(this,W,m,a,J);
this.element=S},YN=function(S,W,m,a,J){if(W.length!=2||m.length!=2)throw Error("Start and end points must be 2D");
yy.call(this,S,W,m,a,J)},DPZ=function(S){return Math.pow(S,3)},w_v=function(S){return 3*S*S-2*S*S*S},G2=function(S){return S.baseUrl||null},Kl=function(S,W){return g.qx(g.F9(S,W),m=>!!m)},SQv=function(S,W,m){function a(g7){var $X=g7.hovercardButton;
if(!$X)return null;$X=$X.subscribeButtonRenderer;if(!$X)return null;const C6=B($X.unsubscribedButtonText),XZ=B($X.subscribedButtonText);let hG,ah;$X.subscribed?(hG=B($X.subscriberCountWithUnsubscribeText),ah=B($X.subscriberCountText)):(hG=B($X.subscriberCountText),ah=B($X.subscriberCountWithSubscribeText));let $k=null;return g7.signinEndpoint&&(($k=ab(g7,"signinEndpoint","webNavigationEndpointData","url"))||($k=g.H($X.signInEndpoint?.commandMetadata,g.E9)?.url),!$k)?null:C6&&(XZ||$k)?{subscribed:$X.subscribed,
subscribeText:C6,subscribeCount:hG,unsubscribeText:XZ,unsubscribeCount:ah,enabled:$X.enabled,signinUrl:$k,classic:g7.useClassicSubscribeButton}:null}
function J(g7){if(g7){var $X=[],C6=g7.videoId;C6&&$X.push("v="+C6);(C6=g7.playlistId)&&$X.push("list="+C6);(g7=g7.startTimeSeconds)&&$X.push("t="+g7);return"/watch?"+$X.join("&")}}
function B(g7){if(!g7)return null;const $X=g7.simpleText;return $X?$X:g7.runs?g.F9(g7.runs,C6=>C6.text).join(""):null}
W=W.endscreenElementRenderer;if(!W)return null;const E=W.style,z=W.endpoint||{};let y=null;var Y=null,G=!1;let K=null,T=null,q=null,V=null;var X=!1;let M=null,x=null;var L=null;let d=null,h=null,JG=null;if(E==="VIDEO")g.H(z,g.iU)?y=g.H(z,g.iU).url:(JG=g.H(z,g.om),y=J(JG)),Y=!1,K=S,W.thumbnailOverlays?(G=W.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,T=B(G.text),G=G.style==="LIVE"):T=B(W.videoDuration);else if(E==="PLAYLIST")g.H(z,g.iU)?y=g.H(z,g.iU).url:(JG=g.H(z,g.om),y=J(JG)),Y=!1,K=
S,q=B(W.playlistLength);else if(E==="CHANNEL"){if(X=ab(z,"browseEndpoint","browseId"))V=X,y=`/channel/${V}`;Y=!1;K="new";(X=!!W.isSubscribe)?M=a(W):x=B(W.subscribersText)}else E==="WEBSITE"?((L=ab(z,"urlEndpoint","url"))&&(y=L),Y=!0,K="new",L=W.icon.thumbnails[0].url):E==="CREATOR_MERCHANDISE"&&(W.productPrice&&(d=B(W.productPrice)),W.additionalFeesText&&(h=B(W.additionalFeesText)),(Y=ab(z,"urlEndpoint","url"))&&(y=Y),Y=!0,K="new");S=ab(W,"title","accessibility","accessibilityData","label");const yP=
W.endpoint?W.endpoint.clickTrackingParams:null;let kX="";if(W.metadata){const g7=B(W.metadata);g7&&(kX=g7)}return{id:`element-${m}`,type:E,title:B(W.title),metadata:kX,callToAction:B(W.callToAction),hW:W.image,iconUrl:L,left:Number(W.left),width:Number(W.width),top:Number(W.top),aspectRatio:Number(W.aspectRatio),startMs:Math.floor(Number(W.startMs)),endMs:Math.floor(Number(W.endMs)),videoDuration:T,MU:G,playlistLength:q,channelId:V,subscribeButton:M,subscribersText:x,isSubscribe:X,targetUrl:y||null,
At:Y,sessionData:yP?{itct:yP}:null,Bs:K,yl:S?S:null,isPlaceholder:W.isPlaceholder,impressionUrls:Kl(W.impressionUrls||[],G2),Qu:Kl(W.hovercardShowUrls||[],G2),clickUrls:Kl(z.loggingUrls||[],G2),visualElement:g.Qj(W.trackingParams),productPrice:d,additionalFeesText:h,watchEndpoint:JG||null}},T2=function(S,W){const m={startMs:Math.floor(Number(S.startMs)),
impressionUrls:Kl(S.impressionUrls||[],G2),elements:Kl(S.elements||[],(a,J)=>SQv(W,a,J))};
S.trackingParams&&(m.visualElement=g.Qj(S.trackingParams));return m},qw=function(S){return S.player.K().playerStyle==="creator-endscreen-editor"},W8N=function(S){return S.player.getVideoData().i$?"current":S.S?"new":"current"},pl=function(S,W,m=!0){S.player.Zz("creatorendscreen");
S.B&&(S.B.dispose(),S.B=null,S.A.dispose(),S.A=null);for(var a of Object.values(S.N))a.dispose();S.N={};S.W={};S.Z.length>0&&(S.Z.forEach(J=>{J.dispose()}),S.Z.length=0);
S.C&&(g.J$(S.C,"ytp-ce-element-show"),S.C.setAttribute("aria-hidden","true"));S.V=0;if((S.endscreen=W)&&W.elements){m&&mxH(S);m=[];a=new g.jX(W.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});m.push(a);S.player.K().N||(S.B=new g.c({G:"div",O:"ytp-ce-shadow"}),g.TJ(S.player,S.B.element,4),S.A=new g.HV(S.B,200));for(a=0;a<W.elements.length;++a){const J=W.elements[a],B=aZw(S,J);if(!B){g.IL(new g.VP("buildEndscreenElement null",J));continue}S.N[J.id]=B;S.W[J.id]=J;g.TJ(S.player,
B.element,4);const E=new g.jX(J.startMs,J.endMs,{id:"ytp-ce-element-"+J.id,namespace:"creatorendscreen"});m.push(E);JNw(S,B,J)}S.player.iQ(m);S.oL()}},BNg=function(S){var W=S.player.getVideoData(),m=W.videoId;
S.j&&S.j.abort();m={method:"POST",onFinish:J=>{var B=S.j=null;J.status===200&&(J=J.responseText,J.substring(0,3)===")]}"&&(J=J.substring(3),B=JSON.parse(J),B=T2(B,W8N(S))));pl(S,B)},
urlParams:{v:m},withCredentials:!0};S.S&&(m.urlParams.ptype="embedded");const a=W.pH;a&&(m.postParams={ad_tracking:a});if(W=g.cF_(W))if(W=g.oS(W),W=g.Ak(W))S.j=g.Zf(W,m)},mxH=function(S){const W=g.H1(),m=g.l2();
m&&W&&S.endscreen.visualElement&&g.KO(g.oL)(void 0,m,W,S.endscreen.visualElement)},aZw=function(S,W){var m=null;
switch(W.type){case "VIDEO":S={G:"div",Wn:["ytp-ce-element","ytp-ce-video"],J:{tabindex:"0","aria-label":W.yl||"","aria-hidden":"true"},D:[{G:"div",O:"ytp-ce-element-shadow"},{G:"div",O:"ytp-ce-covering-image",J:FS(W)},{G:"div",O:"ytp-ce-covering-shadow-top"},{G:"a",O:"ytp-ce-covering-overlay",J:{href:Vy(S,W.targetUrl),tabindex:"-1"},D:[{G:"div",Wn:["ytp-ce-video-title","ytp-webkit-ellipsis"],J:{dir:g.Fs(W.title||"")},Bn:W.title},{G:"div",O:W.MU?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Bn:W.videoDuration||void 0}]}]};m=new g.c(S);break;case "PLAYLIST":S={G:"div",Wn:["ytp-ce-element","ytp-ce-playlist"],J:{tabindex:"0","aria-label":W.yl||"","aria-hidden":"true"},D:[{G:"div",O:"ytp-ce-element-shadow"},{G:"div",O:"ytp-ce-covering-image",J:FS(W)},{G:"div",O:"ytp-ce-covering-shadow-top"},{G:"a",O:"ytp-ce-covering-overlay",J:{href:Vy(S,W.targetUrl),tabindex:"-1"},D:[{G:"div",Wn:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],J:{dir:g.Fs(W.title||"")},Bn:W.title},{G:"div",O:"ytp-ce-playlist-count",
D:[{G:"div",O:"ytp-ce-playlist-icon"},{G:"div",O:"ytp-ce-playlist-count-text",Bn:W.playlistLength||void 0}]}]}]};m=new g.c(S);break;case "CHANNEL":m={G:"div",Wn:["ytp-ce-element","ytp-ce-channel",W.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],J:{tabindex:"0","aria-label":W.yl||"","aria-hidden":"true"},D:[{G:"div",O:"ytp-ce-element-shadow"},{G:"div",O:"ytp-ce-expanding-overlay",D:[{G:"div",O:"ytp-ce-expanding-overlay-hider"},{G:"div",O:"ytp-ce-expanding-overlay-background"},{G:"div",O:"ytp-ce-expanding-overlay-content",
D:[{G:"div",O:"ytp-ce-expanding-overlay-body",D:[{G:"div",O:"ytp-ce-expanding-overlay-body-padding",D:[{G:"a",Wn:["ytp-ce-channel-title","ytp-ce-link"],J:{href:Vy(S,W.targetUrl),target:"_blank",tabindex:"-1",dir:g.Fs(W.title||"")},Bn:W.title},W.subscribeButton?{G:"div",O:"ytp-ce-subscribe-container",D:[{G:"div",O:"ytp-ce-channel-subscribe"}]}:"",W.subscribersText?{G:"div",O:"ytp-ce-channel-subscribers-text",Bn:W.subscribersText}:"",W.metadata?{G:"div",Wn:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Bn:W.metadata}:""]}]}]}]},{G:"div",O:"ytp-ce-expanding-image",J:FS(W)}]};m=new g.c(m);const J=g.BI(document,"div","ytp-ce-channel-subscribe",m.element)[0];if(W.subscribeButton&&W.channelId){g.my(J,"ytp-ce-subscribe-button");let B;if(S.player.K().N){var a=null;B=W.sessionData.itct}else a="endscreen",B=null;a=new g.rW(W.subscribeButton.subscribeText,W.subscribeButton.subscribeCount,W.subscribeButton.unsubscribeText,W.subscribeButton.unsubscribeCount,!!W.subscribeButton.enabled,!!W.subscribeButton.classic,
W.channelId,!!W.subscribeButton.subscribed,a,B,S.player,!1);J.appendChild(a.element);S.Z.push(a)}break;case "WEBSITE":S={G:"div",Wn:["ytp-ce-element","ytp-ce-website"],J:{tabindex:"0","aria-label":W.yl||"","aria-hidden":"true"},D:[{G:"div",O:"ytp-ce-element-shadow"},{G:"div",O:"ytp-ce-expanding-overlay",D:[{G:"div",O:"ytp-ce-expanding-overlay-hider"},{G:"div",O:"ytp-ce-expanding-overlay-background"},{G:"div",O:"ytp-ce-expanding-overlay-content",D:[{G:"div",O:"ytp-ce-expanding-overlay-body",D:[{G:"div",
O:"ytp-ce-expanding-overlay-body-padding",D:[{G:"div",O:"ytp-ce-website-title",J:{dir:g.Fs(W.title||"")},Bn:W.title},{G:"div",O:"ytp-ce-website-metadata",Bn:W.metadata},{G:"a",Wn:["ytp-ce-website-goto","ytp-ce-link"],J:{href:Vy(S,W.targetUrl),target:"_blank",tabindex:"-1"},Bn:W.callToAction}]}]}]}]},{G:"div",O:"ytp-ce-expanding-image",J:FS(W)},{G:"div",O:"ytp-ce-expanding-icon",J:Epv(W.iconUrl)}]};m=new g.c(S);break;case "CREATOR_MERCHANDISE":m="",W.productPrice&&(m={G:"div",O:"ytp-ce-merchandise-price-container",
D:[{G:"div",O:"ytp-ce-merchandise-price",Bn:W.productPrice}]},W.additionalFeesText&&m.D.push({G:"div",O:"ytp-ce-merchandise-additional-fees",Bn:W.additionalFeesText})),S={G:"div",Wn:["ytp-ce-element","ytp-ce-merchandise"],J:{tabindex:"0","aria-label":W.yl||"","aria-hidden":"true"},D:[{G:"div",O:"ytp-ce-element-shadow"},{G:"div",O:"ytp-ce-expanding-overlay",D:[{G:"div",O:"ytp-ce-expanding-overlay-hider"},{G:"div",O:"ytp-ce-expanding-overlay-background"},{G:"div",O:"ytp-ce-expanding-overlay-content",
D:[{G:"div",O:"ytp-ce-expanding-overlay-body",D:[{G:"div",O:"ytp-ce-expanding-overlay-body-padding",D:[{G:"div",O:"ytp-ce-merchandise-title",J:{dir:g.Fs(W.title||"")},Bn:W.title},m,{G:"div",O:"ytp-ce-merchandise-metadata",Bn:W.metadata},{G:"a",Wn:["ytp-ce-merchandise-goto","ytp-ce-link"],J:{href:Vy(S,W.targetUrl),target:"_blank",tabindex:"-1"},Bn:W.callToAction}]}]}]}]},{G:"div",O:"ytp-ce-expanding-image",J:FS(W)},{G:"div",O:"ytp-ce-merchandise-invideo-cta-container",D:[{G:"div",O:"ytp-ce-merchandise-invideo-cta",
Bn:W.callToAction||void 0}]}]},m=new g.c(S)}W.isPlaceholder&&g.my(m.element,"ytp-ce-placeholder");return m},JNw=function(S,W,m){function a(){E(1)}
function J(){E(-1)}
W.listen("mouseenter",()=>{nl(S,W,m)});
W.listen("mouseleave",()=>{s0(S,W,m)});
S.player.K().N||W.listen("click",()=>{g.my(W.element,"ytp-ce-element-hover")});
W.listen("click",z=>{zvp(S,m,z)});
W.listen("keypress",z=>{zvp(S,m,z)});
W.listen("focus",()=>{nl(S,W,m)});
W.listen("blur",()=>{s0(S,W,m)});
W.listen("touchstart",()=>{nl(S,W,m)});
var B=g.EN("ytp-ce-expanding-overlay-hider",W.element);B&&W.L(B,"touchstart",z=>{z.stopPropagation();g.J$(W.element,"ytp-ce-element-hover");g.J$(W.element,"ytp-ce-force-expand")});
W.listen("keydown",z=>{S.iY=z.keyCode===9&&!z.shiftKey});
const E=z=>{S.V+=z;S.V>0?(g.my(W.element,"ytp-ce-force-expand"),u$(S,m.id,!0)):(g.J$(W.element,"ytp-ce-force-expand"),g.J$(W.element,"ytp-ce-element-hover"),u$(S,m.id,!1))};
B=z=>{z&&(W.listen("blur",()=>{z.style.display!="none"&&S.iY&&z.focus()}),W.L(z,"focus",a),W.L(z,"blur",J))};
B(g.EN("ytp-sb-subscribe",W.element));B(g.EN("ytp-sb-unsubscribe",W.element));W.listen("focus",a);W.listen("blur",J)},go=function(S,W,m){function a(){B||(J++,J===W.length&&(E.stop(),m&&m()))}
if(!W||W.length===0||qw(S))m&&m();else{W=yN$(S,W);var J=0,B=!1,E=new g.rr(()=>{B=!0;m&&m()},1E3,S);
E.start();for(S=0;S<W.length;S++)g.oY(W[S],a)}},FS=function(S){let W;
S.hW&&(W=S.hW.thumbnails);return Epv(W?W[W.length-1].url:null)},Vy=function(S,W){S=S.player.K();
if(W){if(W.startsWith("//"))return S.protocol+":"+W;if(W.startsWith("/"))return g.y9(S)+W}else return"";return W},Epv=function(S){return S?{style:"background-image: url("+S+")"}:{}},nl=function(S,W,m){g.WL(W.element,"ytp-ce-element-hover")||(m.type==="VIDEO"||m.type==="PLAYLIST"?g.my(W.element,"ytp-ce-element-hover"):S.player.K().N?(new g.rr(()=>{g.my(W.element,"ytp-ce-element-hover")},200)).start():g.my(W.element,"ytp-ce-element-hover"),go(S,m.Qu),u$(S,m.id,!0))},s0=function(S,W,m){g.J$(W.element,
"ytp-ce-element-hover");
g.J$(W.element,"ytp-ce-force-expand");u$(S,m.id,!1)},zvp=function(S,W,m){if(W.targetUrl&&(!m||m.type!=="keypress"||m.keyCode===13)){for(var a=m.target;a&&!g.WL(a,"ytp-ce-element");){g.WL(a,"subscribe-label")&&O0(S,W);
if(g.WL(a,"ytp-ce-channel-subscribe"))return;a=a.parentElement||null}if(!a||g.WL(a,"ytp-ce-element-hover")){m.preventDefault();m.stopPropagation();if(a=S.N[W.id])s0(S,a,W),a.element.blur();if(m.ctrlKey||m.metaKey||W.Bs==="new")O0(S,W),S.player.sendVideoStatsEngageEvent(17,void 0),S.player.pauseVideo(),m=g.oS(Vy(S,W.targetUrl)),m=g.Ak(m),g.aR(m,void 0,W.sessionData);else{const J=g.SB(S.player.K())||S.player.getVideoData().i$,B=()=>{var E=Vy(S,W.targetUrl),z=W.sessionData,y=W.watchEndpoint;const Y=
g.nO(E);J&&Y&&(Y.v||Y.list)?S.player.HA(Y.v,z,Y.list,!1,void 0,y||void 0):g.me(E,z)};
O0(S,W,()=>{S.player.sendVideoStatsEngageEvent(17,B)})}}}},u$=function(S,W,m){S.B&&(m?S.A.show():S.A.hide());
for(const a of Object.keys(S.N))a!==W&&g.I(S.N[a].element,"ytp-ce-element-shadow-show",m)},O0=function(S,W,m){go(S,W.clickUrls,m);
(S=g.l2())&&W.At&&g.Bz(S,W.visualElement)},yN$=function(S,W){var m=S.player.getVideoData().clientPlaybackNonce;
S=S.player.getCurrentTime().toFixed(2);m={CPN:m,AD_CPN:m,MT:S};S=[];for(let a=0;a<W.length;a++)S.push(YQH(W[a],m));return S},YQH=function(S,W){return S.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,m=>{let a=unescape(m);
a=a.substring(1,a.length-1);return W[a]?escape(W[a]):m})},Ggv=function(S){return typeof S==="string"?S:""},jt=function(S,W,m){for(const a in W)if(W[a]===S)return S;
return m},Qy=function(S){if(!S)return null;
var W=g.oS(Ggv(S.value));W=g.Ak(W);if(!W)return null;const m=jt(S.target,K8Q,"current");if(m==null)S=null;else{var a=S.show_link_icon;S=new TNZ(W,m,a==="true"||a==="false"?a==="true":!0,S.pause_on_navigation!=null?S.pause_on_navigation:!0)}return S},V$H=function(S){if(!S)return null;
const W=jt(S.type,qQH),m=jt(S.trigger,p9w);S=S.url;S=Array.isArray(S)&&S.length?S[0]:S;S=Qy(S?S:null);return W?new F8$(W,m,S):null},npp=function(S,W){return g.gN(S.action,W)},XS=function(S,W){S="background-image: url("+S+");";
const m=[];W&&m.push(W);return{G:"div",O:"iv-card-image",J:{style:S},D:m}},Hx=function(S){return S.customMessage?vx("div","iv-card-message",S.customMessage):""},l$=function(S){if(!S.metaInfo||S.metaInfo.length===0)return"";
const W=[];for(const m of S.metaInfo)W.push(vx("li","",m));return{G:"ul",O:"iv-card-meta-info",D:W}},Mw=function(S,W,m,a){if(a)for(const J of W)S.C(J,a,m.id,m.sessionData,m.vQ.click,5)},vx=function(S,W,m){W?typeof W==="string"?W={"class":W}:Array.isArray(W)&&(W={"class":W.join(" ")}):W={};
W.dir=g.Fs(m);return{G:S,J:W,Bn:m}},sZw=function(S){if(!S.customMessage)return"";
const W=["iv-card-action","iv-card-primary-link"],m={};S.nT&&(W.push("iv-card-action-icon"),m.style="background-image: url("+S.nT+");");m.dir=g.Fs(S.customMessage);const a=[{G:"span",Bn:S.customMessage}];S.showLinkIcon&&(a.push("\u00a0"),a.push({G:"span",O:"iv-card-link-icon"}));return{G:"div",Wn:W,J:m,D:a}},u9$=function(S){var W;
(W=S)&&!(W=S.length>1?S.charAt(0)==="/"&&S.charAt(1)!=="/":S==="/")&&(W=S.replace(/^(https?:)?\/\//,"").split("/",1),W=!W||W.length<1||!W[0]?[]:W[0].toLowerCase().split(".").reverse(),W=W[0]==="com"&&W[1]==="youtube"||W[0]==="be"&&W[1]==="youtu");return W?S.indexOf("/redirect?")===-1:!1},gpQ=function(S,W){return W?W:u9$(S)?"current":"new"},U0=function(S,W,m,a,J,B,E){S.context.C.listen(W,"click",z=>{S.K_(m,a,J,B||[],E||0,z)});
S.context.C.listen(W,"touchstart",()=>{S.p_=!1});
S.context.C.listen(W,"touchmove",()=>{S.p_=!0})},Onn=function(S){if(g.H(S,g.iU)?.url)return g.H(S,g.iU).url;
if((S=g.H(S,g.om))&&S.videoId){let W="/watch?v="+S.videoId;S.playlistId&&(W+="&list="+S.playlistId);S.index&&(W+="&index="+S.index);S.startTimeSeconds&&(W+="&t="+S.startTimeSeconds);return W}return null},Ll=function(S,W,m){return{Rk:(S.impressionLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
click:(m.loggingUrls||[]).map(a=>a.baseUrl||""),
close:(W.dismissLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
uA:(W.impressionLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
W3:(W.clickLoggingUrlsV2s||[]).map(a=>a.baseUrl||"")}},i$=function(S,W){if(W.onClickCommand&&g.H(W.onClickCommand,g.OFK)?.targetId==="engagement-panel-error-corrections"){S.U=W;
var m=!0}else m=!1;if(!m||jZH(S,W))if(m=QZ9(S,W)){var a={Ka:W,cB:m.element,J8:!1};if(W.onClickCommand)S.X.T("web_infocards_teaser_show_logging_fix")&&(S.C3||vpH(S),Rb(S,W.id),m=S.findLastIndex(a),g.RZ(S.cards,m,0,a));else{S.isInitialized||X9$(S);Rb(S,W.id);const J=S.findLastIndex(a);g.RZ(S.cards,J,0,a);m.Xn(S.N,J);S.AX()}W.autoOpen?S.addCueRange(W.startMs,0x8000000000000,W.id,()=>{S.B||(S.C=a,et(S),HnN(S,a),xN(S,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(m=S.context.X.getCurrentTime()*1E3,m<5E3&&m>W.startMs&&
lZN(S,a),S.addCueRange(W.startMs,W.startMs+1,W.id,()=>{lZN(S,a)}),et(S))}},Ib=function(S){S.B&&(S.d2.hide(),g.Bp(S.TN),g.J$(S.context.X.getRootNode(),g.hf.IV_DRAWER_OPEN),S.B=!1,mE(S.X),S.W&&S.W.stop(),S.W=new g.rr(()=>{S.cn&&(S.cn.focus(),S.cn=null)},330),S.W.start())},M$9=function(S,W){W=W.data;
W.autoOpenMs&&S.addCueRange(W.autoOpenMs,0x8000000000000,"",()=>{xN(S,"YOUTUBE_DRAWER_AUTO_OPEN")});
W.autoCloseMs&&S.addCueRange(W.autoCloseMs,0x8000000000000,"",()=>{Ib(S)});
const m=W.headerText;g.XO(S.x6,m);S.A&&(S.X.T("player_tooltip_data_title_killswitch")?S.A.setAttribute("title",m):S.A.setAttribute("data-tooltip-title",m));W.eventId&&(S.eventId=W.eventId);S.GN=g.Qj(W.trackingParams);S.Z=g.Qj(W.closeTrackingParams);S.Mi=g.Qj(W.iconTrackingParams)},Px=function(S,W,m){let a=-1,J=-1;
for(let B=0;B<S.length;B++){if(S[B].height===W||S[B].width===m)return S[B];((S[B].height||0)<W||(S[B].width||0)<m)&&(a<0||(S[a].height||0)<(S[B].height||0)||(S[a].width||0)<(S[B].width||0))?a=B:((S[B].height||0)>=W||(S[B].width||0)>=m)&&(J<0||(S[J].height||0)>(S[B].height||0)||(S[J].width||0)>(S[B].width||0))&&(J=B)}return S[J>=0?J:a]},fl=function(S,W,m,a){return{feature:m.feature?m.feature:"cards",
src_vid:S.context.videoData.videoId,annotation_id:W,ei:S.context.videoData.eventId||"",itct:a.trackingParams||""}},UxH=function(S,W){const m=W.cardId?W.cardId:`cr:${S.V}`;
var a=S.X.K().experiments.Y6("enable_error_corrections_infocard_web_client");if(!W.content&&W.teaser.simpleCardTeaserRenderer&&a){a=W.teaser.simpleCardTeaserRenderer;var J=W.icon?W.icon.infoCardIconRenderer:null;if(a.channelAvatar&&a.channelAvatar.thumbnails&&a.channelAvatar.thumbnails.length>0)var B=Px(a.channelAvatar.thumbnails,22,22).url;W={id:m,timestamp:S.V,type:"simple",teaserText:g.qL(a.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),
autoOpen:!!W.autoOpen,sessionData:{},sponsored:!1,vQ:{},zT:null,De:a.trackingParams?g.Qj(a.trackingParams):null,Mi:J&&J.trackingParams?g.Qj(J.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,nT:null,title:"",customMessage:"",url:null,onClickCommand:a.onTapCommand||null,H6:B};i$(S,W)}else if(W.content?.simpleCardContentRenderer){if(!W.cueRanges.length)return;B=W.content?.simpleCardContentRenderer;a=W.teaser.simpleCardTeaserRenderer;J=W.icon?W.icon.infoCardIconRenderer:null;W={id:m,
timestamp:S.V,type:"simple",teaserText:g.qL(a.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:fl(S,m,W,B),sponsored:!1,vQ:Ll(B,a,B.command),zT:B.trackingParams?g.Qj(B.trackingParams):null,De:a.trackingParams?g.Qj(a.trackingParams):null,Mi:J&&J.trackingParams?g.Qj(J.trackingParams):null,imageUrl:Px(B.image.thumbnails,290,290).url,displayDomain:B.displayDomain?g.qL(B.displayDomain):null,showLinkIcon:!!B.showLinkIcon,
nT:null,title:B.title?g.qL(B.title):"",customMessage:B.callToAction?g.qL(B.callToAction):"",url:g.H(B.command,g.iU).url?Qy({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:g.H(B.command,g.iU).url}):null,onClickCommand:null};i$(S,W)}else if(W.content?.collaboratorInfoCardContentRenderer){if(!W.cueRanges.length)return;B=W.content?.collaboratorInfoCardContentRenderer;a=W.teaser.simpleCardTeaserRenderer;J=W.icon?W.icon.infoCardIconRenderer:null;W={id:m,timestamp:S.V,type:"collaborator",
teaserText:g.qL(a.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:fl(S,m,W,B),sponsored:!1,vQ:Ll(B,a,B.endpoint),zT:B.trackingParams?g.Qj(B.trackingParams):null,De:a.trackingParams?g.Qj(a.trackingParams):null,Mi:J&&J.trackingParams?g.Qj(J.trackingParams):null,channelId:g.H(B.endpoint,g.bA).browseId,customMessage:B.customText?g.qL(B.customText):null,profileImageUrl:Px(B.channelAvatar.thumbnails,290,
290).url,title:B.channelName?g.qL(B.channelName):"",metaInfo:[B.subscriberCountText?g.qL(B.subscriberCountText):""],url:Qy({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:g.H(B.endpoint,g.bA).canonicalBaseUrl?g.H(B.endpoint,g.bA).canonicalBaseUrl:`/channel/${g.H(B.endpoint,g.bA).browseId}`}),onClickCommand:null};i$(S,W)}else if(W.content?.playlistInfoCardContentRenderer){if(!W.cueRanges.length)return;B=W.content?.playlistInfoCardContentRenderer;a=W.teaser.simpleCardTeaserRenderer;
J=W.icon?W.icon.infoCardIconRenderer:null;W={id:m,timestamp:S.V,type:"playlist",teaserText:g.qL(a.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:fl(S,m,W,B),sponsored:!1,vQ:Ll(B,a,B.action),zT:B.trackingParams?g.Qj(B.trackingParams):null,De:a.trackingParams?g.Qj(a.trackingParams):null,Mi:J&&J.trackingParams?g.Qj(J.trackingParams):null,nH:Px(B.playlistThumbnail.thumbnails,258,290).url,customMessage:B.customMessage?
g.qL(B.customMessage):null,playlistVideoCount:g.qL(B.playlistVideoCount),title:B.playlistTitle?g.qL(B.playlistTitle):"",metaInfo:[B.channelName?g.qL(B.channelName):"",B.videoCountText?g.qL(B.videoCountText):""],url:Qy({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:Onn(B.action)}),onClickCommand:null};i$(S,W)}else if(W.content?.videoInfoCardContentRenderer){if(!W.cueRanges.length)return;B=W.content?.videoInfoCardContentRenderer;a=W.teaser.simpleCardTeaserRenderer;J=W.icon?
W.icon.infoCardIconRenderer:null;W={id:m,timestamp:S.V,type:"video",teaserText:g.qL(a.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:fl(S,m,W,B),sponsored:!1,vQ:Ll(B,a,B.action),zT:B.trackingParams?g.Qj(B.trackingParams):null,De:a.trackingParams?g.Qj(a.trackingParams):null,Mi:J&&J.trackingParams?g.Qj(J.trackingParams):null,nH:Px(B.videoThumbnail.thumbnails,258,290).url,videoDuration:B.lengthString?
g.qL(B.lengthString):null,customMessage:B.customMessage?g.qL(B.customMessage):null,title:B.videoTitle?g.qL(B.videoTitle):"",metaInfo:[B.channelName?g.qL(B.channelName):"",B.viewCountText?g.qL(B.viewCountText):""],isLiveNow:!!B.badge,url:Qy({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:Onn(B.action)}),onClickCommand:null};i$(S,W)}S.V++},L8p=function(S,W){return g.gN(S.cards,m=>m.Ka.id===W)},et=function(S){g.I(S.X.getRootNode(),"ytp-cards-shopping-active",Rv9(S))},Rb=function(S,
W){if(W=L8p(S,W))W===S.C&&(S.C=null),S.X.removeCueRange(W.Ka.id),g.ju(W.cB),g.v9(S.cards,W),S.AX(),et(S)},xN=function(S,W,m){if(!S.B){S.d2.show();
S.ZQ=new g.rr(()=>{g.my(S.context.X.getRootNode(),g.hf.IV_DRAWER_OPEN)},0);
S.ZQ.start();S.TN.L(S.N,"mousewheel",J=>{S.q2.start();J.preventDefault();J=J||window.event;let B=0;J.type=="MozMousePixelScroll"?B=0==(J.axis==J.HORIZONTAL_AXIS)?J.detail:0:window.opera?B=J.detail:B=J.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?J.wheelDeltaY/-30:J.wheelDeltaY/-1.2:J.wheelDelta/-1.6:J.wheelDeltaY/-3;if(J=B)S.N.scrollTop+=J});
S.B=!0;var a=g.l2();a&&S.GN&&S.Z&&g.aP(a,[S.GN,S.Z]);W={TRIGGER_TYPE:W};for(const J of S.cards)J.J8||(J.J8=!0,evn(S.context.logger,J.Ka.vQ.Rk,W)),a&&g.aP(a,[J.Ka.zT]);mE(S.X);m&&(S.W=new g.rr(()=>{S.cn=S.A;S.R2.focus()},330),S.W.start())}},X9$=function(S){g.ak(S.IL(),[g.hf.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.TJ(S.X,S.j,5);S.Yf();S.A=g.EN("ytp-cards-button",S.X.getRootNode());S.R2=g.EN("iv-drawer-close-button",S.j);S.isInitialized=!0},vpH=function(S){S.iY.push(g.yG("iv-teaser-shown",S.tv,S));
S.iY.push(g.yG("iv-teaser-hidden",S.Qc,S));S.iY.push(g.yG("iv-teaser-clicked",S.yc,S));S.C3=!0},jZH=function(S,W){S.U=W;
var m=S.X.getVideoData();if(!m)return!1;m=g.LN(m);if(m?.markersMap)for(let J=0;m?.markersMap.length>J;J++){var a=m?.markersMap[J];if(a.key==="ERROR_CORRECTION_MARKERS"&&(a=a.value?.markers)&&a.length>0)return W.startMs=g.H(a[0],g.hVK)?.timeRangeStartMillis||0,S.U=null,!0}return!1},QZ9=function(S,W){switch(W.type){case "simple":S=S.vn;
var m=W.displayDomain?{G:"div",O:"iv-card-image-text",Bn:W.displayDomain}:void 0;var a=sZw(W);m={G:"div",Wn:["iv-card"],D:[{G:"a",O:"iv-click-target",J:{href:W.url?W.url.C()||"":""},D:[XS(W.imageUrl,m),{G:"div",O:"iv-card-content",D:[vx("h2",void 0,W.title),a]}]}]};m=new g.c(m);Mw(S,g.J8("iv-click-target",m.element),W,W.url);W=m;break;case "collaborator":S=S.vn;m={G:"div",Wn:["iv-card","iv-card-channel"],D:[{G:"a",Wn:["iv-click-target"],J:{href:W.url.C()||"","data-ytid":W.channelId},D:[XS(W.profileImageUrl),
{G:"div",O:"iv-card-content",D:[Hx(W),{G:"h2",O:"iv-card-primary-link",Bn:W.title},l$(W)]}]}]};m=new g.c(m);Mw(S,g.J8("iv-click-target",m.element),W,W.url);W=m;break;case "playlist":S=S.vn;m={G:"div",Wn:["iv-card","iv-card-playlist"],D:[{G:"a",O:"iv-click-target",J:{href:W.url.C()||""},D:[XS(W.nH,{G:"div",O:"iv-card-image-overlay",D:[{G:"span",O:"iv-card-playlist-video-count",Bn:W.playlistVideoCount}]}),{G:"div",O:"iv-card-content",D:[Hx(W),vx("h2","iv-card-primary-link",W.title),l$(W)]}]}]};m=new g.c(m);
Mw(S,g.J8("iv-click-target",m.element),W,W.url);W=m;break;case "productListing":S=S.vn;var J=W.offers.length!=0;m=["iv-card"];a="";var B=sZw(W);J&&(m.push("iv-card-product-listing"),a="iv-card-primary-link",B=W.offers[0],J=[],B.price&&J.push({G:"div",O:"iv-card-offer-price",Bn:B.price}),B.merchant&&J.push({G:"div",O:"iv-card-offer-merchant",Bn:B.merchant}),B={G:"div",D:J});J=W.url?W.url.C()||"":"";m={G:"div",Wn:m,J:{tabindex:"0"},D:[{G:"a",Wn:["iv-card-image","iv-click-target"],J:{style:"background-image: url("+
W.imageUrl+");",href:J,"aria-hidden":"true",tabindex:"-1"}},{G:"div",O:"iv-card-content",D:[W.sponsored?{G:"div",O:"iv-card-sponsored",D:["Sponsored",{G:"div",O:"iv-ad-info-container",D:[{G:"div",O:"iv-ad-info",Bn:"{{adInfo}}"},{G:"div",O:"iv-ad-info-icon-container",D:[{G:"div",O:"iv-ad-info-icon"},{G:"div",O:"iv-ad-info-callout"}]}]}]}:"",{G:"a",O:"iv-click-target",J:{href:J},D:[vx("h2",a,W.title),B]}]}]};m=new g.c(m);a=g.nX("span");g.XO(a,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
m.setContent(a,"adInfo");Mw(S,g.J8("iv-click-target",m.element),W,W.url);W=m;break;case "video":S=S.vn;m=W.isLiveNow?{G:"span",Wn:["yt-badge","yt-badge-live"],Bn:"LIVE NOW"}:null;m={G:"div",Wn:["iv-card","iv-card-video"],D:[{G:"a",O:"iv-click-target",J:{href:W.url?.C()||""},D:[XS(W.nH,W.videoDuration?{G:"span",O:"iv-card-video-duration",Bn:W.videoDuration}:void 0),{G:"div",O:"iv-card-content",D:[Hx(W),vx("h2","iv-card-primary-link",W.title),l$(W),m]}]}]};m=new g.c(m);Mw(S,g.J8("iv-click-target",m.element),
W,W.url);W=m;break;default:return null}return W},lZN=function(S,W){if(!g.WL(S.X.getRootNode(),"ytp-cards-teaser-shown")){if(S.C!==W){var m=g.l2(),a=S.C?S.C.Ka.Mi:S.Mi;
m&&a&&g.JY(m,[a]);S.C=W;et(S)}(m=S.isInitialized&&S.IL().style.display=="none")||(m=S.context.X.getPlayerState(),a=m===0&&S.context.X.getCurrentTime()===0,m=!(m===1||m===3||a));m||W.Ka.teaserDurationMs&&S.X.qv(!0,{teaserText:W.Ka.teaserText,durationMs:W.Ka.teaserDurationMs,onClickCommand:W.Ka.onClickCommand,H6:W.Ka.H6??null});S.mU.isActive()||((!S.B||!S.q2.isActive()&&S.Hn)&&HnN(S,W),S.mU.start(910+W.Ka.teaserDurationMs))}},Rv9=function(S){return S.C?S.C.Ka.type==="productListing":S.X.T("enable_wn_infocards")?
!!S.cards?.length&&g.sQ(S.cards,W=>W.Ka.type==="productListing"):g.sQ(S.cards,W=>W.Ka.type==="productListing")},HnN=function(S,W){S.S.jg?(W=new z2([0,
S.N.scrollTop],[0,W.cB.offsetTop],600,w_v),S.context.B.listen(W,"animate",m=>{S.N.scrollTop=m.y}),S.context.B.listen(W,"finish",m=>{S.N.scrollTop=m.y}),W.play()):(S.S.UV(!0),S.N.scrollTop=W.cB.offsetTop,S.S.UV(!1))},kN=function(S){return S.C&&S.C.Ka?S.C.Ka:S.cards[0]&&S.cards[0].Ka?S.cards[0].Ka:null},xxH=function(S){const W=S.annotation.data;
"start_ms"in W&&"end_ms"in W&&S.addCueRange(Number(W.start_ms),Number(W.end_ms),S.annotation.id,()=>{S.show()},()=>{S.hide()})},inQ=function(S,W){var m=Z6H(W).width;
g.Dt(W,m);m=new YN(W,[m,W.offsetTop],[m-m,W.offsetTop],200,DPZ);g.R(S,m);S.context.B.listen(m,"begin",()=>{g.Yr(W,!0)});
m.play()},$N=function(S,W,m){m.stopPropagation();
dxx(S);IZg(S,W);S.C.focus()},Pww=function(S){const W=S.annotation.data;
if(S.annotation.style==="cta")var m=6;else if(S.annotation.style==="video"||S.annotation.style==="playlist")m=7;S.W=W.collapsedelay_ms||S.W;const a=["iv-promo","iv-promo-inactive"];S.IL().setAttribute("aria-hidden","true");S.IL().setAttribute("aria-label","Promotion");S.IL().tabIndex=0;const J=S.annotation.Od();let B;var E=W.image_url;E&&(B=S.createElement({G:"div",Wn:["iv-promo-img","iv-click-target"]}),E=S.createElement({G:"img",J:{src:E,"aria-hidden":"true"}}),B.appendChild(E),W.video_duration&&
!W.is_live?(E=S.createElement({G:"span",O:"iv-promo-video-duration",Bn:W.video_duration}),B.appendChild(E)):W.playlist_length&&(E=S.createElement({G:"span",O:"iv-promo-playlist-length",Bn:W.playlist_length.toString()}),B.appendChild(E)),J&&U0(S,B,J,S.annotation.id,W.session_data,void 0,m));J?(E=S.createElement({G:"a",O:"iv-promo-txt"}),g.cF(E,J.C()),S.C=E):S.C=S.createElement({G:"div",O:"iv-promo-txt"});let z,y,Y,G;switch(S.annotation.style){case "cta":case "website":z=S.createElement({G:"p",D:[{G:"strong",
Bn:W.text_line_1}]});y=S.createElement({G:"p",D:[{G:"span",O:"iv-promo-link",Bn:W.text_line_2}]});if(E=W.text_line_3)a.push("iv-promo-website-card-cta-redesign"),Y=S.createElement({G:"button",Wn:["iv-promo-round-expand-icon","ytp-button"]}),E=S.createElement({G:"button",Wn:["iv-button","iv-promo-button"],D:[{G:"span",O:"iv-button-content",Bn:E}]}),G=S.createElement({G:"div",O:"iv-promo-button-container"}),G.appendChild(E),J&&U0(S,S.IL(),J,S.annotation.id,W.session_data,void 0,m);g.my(S.C,"iv-click-target");
J&&U0(S,S.C,J,S.annotation.id,W.session_data,void 0,m);break;case "playlist":case "video":z=S.createElement({G:"p",D:[{G:"span",Bn:W.text_line_1}]}),y=S.createElement({G:"p",D:[{G:"strong",Bn:W.text_line_2}]}),W.is_live&&(z=y,y=S.createElement({G:"span",Wn:["yt-badge","iv-promo-badge-live"],Bn:"LIVE NOW"})),g.my(S.C,"iv-click-target"),J&&U0(S,S.C,J,S.annotation.id,W.session_data,void 0,m),a.push("iv-promo-video")}z&&S.C.appendChild(z);y&&S.C.appendChild(y);S.V.appendChild(S.C);G&&S.V.appendChild(G);
m=S.createElement({G:"div",O:"iv-promo-actions"});S.N=S.createElement({G:"button",Wn:["iv-promo-expand","ytp-button"]});S.N.title="Expand";S.context.C.listen(S.N,"click",K=>{$N(S,5E3,K)});
m.appendChild(S.N);g.Yr(S.N,!1);S.context.C.listen(S.IL(),"mouseover",S.q2,S);S.context.C.listen(S.IL(),"mouseout",S.vn,S);S.context.C.listen(S.IL(),"touchend",K=>{$N(S,5E3,K)});
S.B=S.createElement({G:"button",Wn:["iv-promo-close","ytp-button"]});S.B.title="Close";S.context.C.listen(S.B,"click",S.annotation.style==="cta"&&W.text_line_3?S.U:S.iY,S);m.appendChild(S.B);g.ak(S.IL(),a);B&&(g.uD(S.IL(),B),Y&&B.appendChild(Y));g.uD(S.IL(),S.V);g.uD(S.IL(),m)},h1=function(S){S.j&&(g.P_.clearTimeout(S.j),S.j=null)},dxx=function(S){S.A.stop();
S.isCollapsed&&(g.BL(S.IL(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),S.isCollapsed=!1,S.C&&S.C.removeAttribute("aria-hidden"),g.Yr(S.N,!1),g.Yr(S.B,!0))},IZg=function(S,W){S.j||(S.j=g.aG(function(){h1(this);
fZg(this)},W,S))},fZg=function(S){S.isCollapsed||S.Z||S.j||(g.my(S.IL(),"iv-promo-collapsed"),S.isCollapsed=!0,S.A.start())},evn=function(S,W,m){W&&(m?t1(S,W.map(a=>g.MB(a,m))):t1(S,W))},t1=function(S,W,m,a){let J=1,B=void 0,E=-1;
if(m){let z=!1;B=()=>{J--;J||z||(clearTimeout(E),z=!0,m())};
E=setTimeout(()=>{z=!0;m()},1E3)}for(const z of W||[])J++,g.oY(z,B);
a&&(J++,a!==0&&S.X.sendVideoStatsEngageEvent(a,B))},kgg=function(S){return S==="annotation-editor"||S==="live-dashboard"},$x9=function(S){S.j&&(S.player.removeEventListener("videodatachange",S.j),S.j=null)},hvN=function(S){S=S.createElement({G:"div",
Wn:["annotation","annotation-type-custom"]});g.Yr(S,!1);return S},Z_=function(S,W){var m=!1,a=W.getElementsByTagName("annotations");
if(a&&!(a.length<1)&&(a=a[0].getAttribute("itct"))){var J=g.l2();if(J){var B=g.H1();B&&g.KO(g.b2)(void 0,J,B,[g.Qj(a)])}}W=W.getElementsByTagName("annotation");for(a=0;a<W.length;a++){var E=t$g(S,W[a]);J=null;try{a:{if(!E){J=null;break a}var z=E.id;B=/.+/;const q=typeof z==="string"&&B!=null&&z!=null&&z.match(B)?z:"",V=jt(E.type,ANZ),X=jt(E.style,Znx),M=Ggv(E.data),x=M.length!==0?JSON.parse(M):{};b:{var y=E.action;B=V$H;if(y==null){var Y=null;break b}if(g.NP(y)){E=[];for(const d of y){const h=B(d);
h&&E.push(h)}Y=E;break b}const L=B(y);Y=L?[L]:[]}B=Y;J=q&&V?new NNQ(q,V,X,B,x):null}}catch(q){}if(J)if(J.type==="branding"||J.type==="promotion"){B=S;E=J;var G=hvN(B),K=null;switch(E.type){case "branding":if(B.player.K().TV)break;B.player.T("web_player_overlay_positioned_layout")?(G.setAttribute("data-overlay-order","11"),B.player.W4(G,4,!0)):B.N.element.appendChild(G);K=new bnp(G,A1(B),E);break;case "promotion":g.TJ(B.player,G,4),K=new op$(G,A1(B),E)}K&&K.bY();if(B=K)g.R(S,B),S.V[J.id]=B}else if(J.type===
"card"||J.type==="drawer"){S.C||(S.C=rNw(S),g.R(S,S.C));if(J.type==="card"){G=S.C;var T=(m=J)&&m.data&&m.data.card_type;J=m.data;if(T)switch(B=J.tracking||{},B={Rk:B.impression,click:B.click,close:B.close,uA:B.teaser_impression,W3:B.teaser_click},E=J.tracking_params||{},K=null,T){case "collaborator":m={id:m.id,timestamp:J.timestamp||0,type:J.card_type,teaserText:J.teaser_text,teaserDurationMs:J.teaser_duration_ms,startMs:J.start_ms,autoOpen:J.auto_open||!1,sessionData:J.session_data||{},sponsored:J.sponsored||
!1,vQ:B,zT:E.card?g.Qj(E.card):null,De:E.teaser?g.Qj(E.teaser):null,Mi:E.icon?g.Qj(E.icon):null,channelId:J.channel_id,customMessage:J.custom_message?J.custom_message:null,profileImageUrl:J.image_url,title:J.title,metaInfo:J.meta_info,url:Qy({pause_on_navigation:J.pause_on_navigation,target:J.target||"new",value:J.url}),onClickCommand:null};i$(G,m);break;case "playlist":m={id:m.id,timestamp:J.timestamp||0,type:J.card_type,teaserText:J.teaser_text,teaserDurationMs:J.teaser_duration_ms,startMs:J.start_ms,
autoOpen:J.auto_open||!1,sessionData:J.session_data||{},sponsored:J.sponsored||!1,vQ:B,zT:E.card?g.Qj(E.card):null,De:E.teaser?g.Qj(E.teaser):null,Mi:E.icon?g.Qj(E.icon):null,nH:J.image_url,playlistVideoCount:J.playlist_video_count,customMessage:J.custom_message?J.custom_message:null,title:J.title,metaInfo:J.meta_info,url:Qy({pause_on_navigation:J.pause_on_navigation,target:J.target||"new",value:J.url}),onClickCommand:null};i$(G,m);break;case "productListing":J.signin_url&&(K=Qy({target:"current",
value:J.signin_url}));T=[];const q=J.offers||[];for(let V=0;V<q.length;V++)T.push(new Cw$(g.uz(q[V].merchant),g.uz(q[V].price)));m={id:m.id,timestamp:J.timestamp||0,type:J.card_type,teaserText:J.teaser_text,teaserDurationMs:J.teaser_duration_ms,startMs:J.start_ms,autoOpen:J.auto_open||!1,sessionData:J.session_data||{},sponsored:J.sponsored||!1,vQ:B,zT:E.card?g.Qj(E.card):null,De:E.teaser?g.Qj(E.teaser):null,Mi:E.icon?g.Qj(E.icon):null,imageUrl:J.image_url,displayDomain:J.display_domain?J.display_domain:
null,showLinkIcon:!!J.show_link_icon,nT:J.button_icon_url?J.button_icon_url:null,title:J.title,customMessage:J.custom_message?J.custom_message:null,url:Qy({pause_on_navigation:J.pause_on_navigation,target:J.target||"new",value:J.url}),jU9:K,Bp_:J.signin_title?J.signin_title:void 0,vsD:J.signin_message?J.signin_message:void 0,offers:T,onClickCommand:null};i$(G,m);break;case "simple":m={id:m.id,timestamp:J.timestamp||0,type:J.card_type,teaserText:J.teaser_text,teaserDurationMs:J.teaser_duration_ms,
startMs:J.start_ms,autoOpen:J.auto_open||!1,sessionData:J.session_data||{},sponsored:J.sponsored||!1,vQ:B,zT:E.card?g.Qj(E.card):null,De:E.teaser?g.Qj(E.teaser):null,Mi:E.icon?g.Qj(E.icon):null,imageUrl:J.image_url,displayDomain:J.display_domain?J.display_domain:null,showLinkIcon:!!J.show_link_icon,nT:J.button_icon_url?J.button_icon_url:null,title:J.title,customMessage:J.custom_message?J.custom_message:null,url:Qy({pause_on_navigation:J.pause_on_navigation,target:J.target||"new",value:J.url}),onClickCommand:null};
i$(G,m);break;case "video":m={id:m.id,timestamp:J.timestamp||0,type:J.card_type,teaserText:J.teaser_text,teaserDurationMs:J.teaser_duration_ms,startMs:J.start_ms,autoOpen:J.auto_open||!1,sessionData:J.session_data||{},sponsored:J.sponsored||!1,vQ:B,zT:E.card?g.Qj(E.card):null,De:E.teaser?g.Qj(E.teaser):null,Mi:E.icon?g.Qj(E.icon):null,nH:J.image_url,videoDuration:J.video_duration||null,customMessage:J.custom_message?J.custom_message:null,title:J.title,metaInfo:J.meta_info,isLiveNow:!!J.is_live_now,
url:Qy({pause_on_navigation:J.pause_on_navigation,target:J.target||"new",value:J.url}),onClickCommand:null},i$(G,m)}}else M$9(S.C,J);m=!0}}m&&(mE(S.player),S.iY())},cNg=function(S){const W=S.player.K();
S=S.player.getVideoData();return(W.annotationsLoadPolicy||S.annotationsLoadPolicy)===1&&!S.EY||W.GN.get(S.videoId)||S.v4()||g.RV(S)?!0:!1},Dx8=function(S,W){W=!W.isCued()&&!W.C(1024);
S.N.UV(W);S.B.UV(W)},aPN=function(S,W){const m=W.videoId;
var a=E=>{var z=S.loadNumber;S.W=null;S.loaded&&S.loadNumber===z&&S.player.getVideoData().videoId===m&&(E=g.eF(E)&&E.responseXML?E.responseXML:null)&&(Z_(S,E),g.my(S.player.getRootNode(),"iv-module-loaded"))};
g.vp()&&(a=w9H(S,a));const J={format:"XML",onFinish:a,onError:()=>{S.W=null},
urlParams:{}};W.isPharma&&(J.urlParams.pharma="1");J.method="POST";J.withCredentials=!0;(a=S.player.K().GN.get(m))&&SC$(J,a);const B=a&&(a.P8||a.c8);a?.P8&&Math.random()<g.kW(S.player.K().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.IL(new g.VP("Unexpected call to loadVastInfoCards; Attempting to load annotations via cardsXml."));if(!W.xr||B)W.dZ?WX9(S,W.dZ,J):(S.j=()=>{if(!S.Z)S.onVideoDataChange(J);const E=S.player.getVideoData();E?.P1()&&!S.U&&mKv(S,E)},S.player.addEventListener("videodatachange",
S.j))},Nw=function(S,W){var m=!1;
S.C||(S.C=rNw(S),g.R(S,S.C));for(var a of W.cards||[])a.cardRenderer&&(UxH(S.C,a.cardRenderer),m=!0);m&&(S.player.getVideoData()?.P1()||(m=S.C,a=W.headerText?g.qL(W.headerText):"",g.XO(m.x6,a),m.A&&(m.X.T("player_tooltip_data_title_killswitch")?m.A.setAttribute("title",a):m.A.setAttribute("data-tooltip-title",a)),m.context.videoData.eventId&&(m.eventId=m.context.videoData.eventId),m.GN=W.trackingParams?g.Qj(W.trackingParams):null,m.Z=W.closeButton.infoCardIconRenderer.trackingParams?g.Qj(W.closeButton.infoCardIconRenderer.trackingParams):
null,m.Mi=W.icon.infoCardIconRenderer.trackingParams?g.Qj(W.icon.infoCardIconRenderer.trackingParams):null,S.iY()),mE(S.player))},mKv=function(S,W){if(W=W.getWatchNextResponse()?.cards?.cardCollectionRenderer)S.U=!0,Nw(S,W),W.headerText&&S.FM&&(W=g.qL(W.headerText),S.player.T("player_tooltip_data_title_killswitch")?S.FM.setAttribute("title",W):S.FM.setAttribute("data-tooltip-title",W))},w9H=function(S,W){return(...m)=>{S.n_()||S.bY.push(g.fK.hE(()=>{W(...m)}))}},SC$=function(S,W){S.method="POST";
S.postParams=S.postParams||{};W.c8&&(S.postParams.ic_coll=W.c8);W.P8&&(S.postParams.ic_xml=W.P8);W.yK&&(S.postParams.ic_track=W.yK)},WX9=function(S,W,m){Math.random()<g.kW(S.player.K().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.IL(new g.VP("Unexpected call to loadInvideoUrl; Attempting to load annotations via invideo URL."));
S.Z=!0;S.W=g.Zf(W,m)},t$g=function(S,W){const m={};
for(var a of W.attributes)m[a.name]=a.nodeValue;for(a=0;a<W.childNodes.length;a++){var J=W.childNodes[a];if(g.bc(J)&&J.nodeType==1){var B=void 0;if(m[J.tagName])B=m[J.tagName];else if(J.tagName==="data"){J.childNodes.length>0&&(B=J.childNodes[0].nodeValue,m[J.tagName]=typeof B==="string"?B.trim():B);continue}else B=[],m[J.tagName]=B;J&&J.tagName==="TEXT"?J.childNodes.length===1&&J.childNodes[0].nodeType===3?B.push(J.childNodes[0].nodeValue):B.push(""):J&&B.push(t$g(S,J))}}return m},A1=function(S){if(!S.S){const W=
new JkZ(S);
g.R(S,W);const m=new g.Ew(S);g.R(S,m);S.S=new Bh9(W,m,S.player.K(),S.player.getVideoData(),S.logger,S.player,S.Ec)}return S.S},ElN=function(S){const W=S.player.getVideoData();
if(W.dZ){var m=S.player.K().GN.get(W.videoId);if(m){var a={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(J,B,E)=>{J=S.loadNumber;B=W.videoId;S.loaded&&S.loadNumber===J&&S.player.getVideoData().videoId===B&&(E=g.eF(E)&&E.responseXML?E.responseXML:null)&&Z_(S,E)}};
g.vp()&&(a.onFinish=w9H(S,a.onFinish));a.postParams={ic_only:"1"};SC$(a,m);S.Z=!0;g.Zf(W.dZ,a)}}},rNw=function(S){const W=new g.c({G:"div"});
g.Yr(W.element,!1);const m=new z_n(S.player,W.element,A1(S));g.R(m,W);W.Xn(S.N.element);m.bY();return m},ykN=function(S,W,m,a,J){if(!S.player.K().TV){var B=[];
W.navigationEndpoint&&g.H(W.navigationEndpoint,g.bA)&&g.H(W.navigationEndpoint,g.bA).browseId&&B.push(new F8$("openUrl","click",new TNZ(`/channel/${g.H(W.navigationEndpoint,g.bA).browseId}`,"new",!0,!0)));var E=W.watermark.thumbnails[0];a={channel_name:W.channelName,end_ms:W.endTimeMs,image_height:E.height,image_type:1,image_url:E.url,image_width:E.width,is_mobile:!1,session_data:{annotation_id:m,ei:J,feature:"iv",itct:W.trackingParams,src_vid:a},start_ms:W.startTimeMs};if(W.subscribeButton&&g.H(W.subscribeButton,
g.BT)){a.channel_id=g.H(W.subscribeButton,g.BT).channelId;W=g.H(W.subscribeButton,g.BT);E=J=null;W.subscribed?(W.subscriberCountWithUnsubscribeText&&(J=g.qL(W.subscriberCountWithUnsubscribeText)),W.subscriberCountText&&(E=g.qL(W.subscriberCountText))):(W.subscriberCountText&&(J=g.qL(W.subscriberCountText)),W.subscriberCountWithSubscribeText&&(E=g.qL(W.subscriberCountWithSubscribeText)));const z=g.H(W.signInEndpoint?.commandMetadata,g.E9)?.url||"";W={subscribeText:g.qL(W.unsubscribedButtonText),subscribeCount:J||
"",unsubscribeText:g.qL(W.subscribedButtonText),unsubscribeCount:E||"",enabled:W.enabled||!1,classic:!1,subscribed:W.subscribed||!1,feature:"iv",signInUrl:z};a.standalone_subscribe_button_data=W}B=new NNQ(m,"branding","branding",B,a);a=hvN(S);S.player.T("web_player_overlay_positioned_layout")?(a.setAttribute("data-overlay-order","11"),S.player.W4(a,4,!0)):S.N.element.appendChild(a);B=new bnp(a,A1(S),B);B.bY();g.R(B,B);S.V[m]=B}};
g.c5.prototype.qv=g.lc(36,function(S,W){const m=g.jI(this.Pv());m&&m.qv(S,W)});
var J1={},Bx=null;g.B9(z2,g.zc);g.v=z2.prototype;g.v.getDuration=function(){return this.duration};
g.v.play=function(S){if(S||this.C==0)this.progress=0,this.coords=this.N;else if(this.isPlaying())return!1;E0(this);this.startTime=S=g.S$();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.j=this.startTime;this.progress||this.Dk();this.g4("play");this.isPaused()&&this.g4("resume");this.C=1;const W=g.c_(this);W in J1||(J1[W]=this);oX9();rGp(this,S);return!0};
g.v.stop=function(S){E0(this);this.C=0;S&&(this.progress=1);Cc9(this,this.progress);this.onStop();this.mP()};
g.v.pause=function(){this.isPlaying()&&(E0(this),this.C=-1,this.g4("pause"))};
g.v.j9=function(){this.C==0||this.stop(!1);this.g4("destroy");z2.bJ.j9.call(this)};
g.v.destroy=function(){this.dispose()};
g.v.c_=function(){this.g4("animate")};
g.v.g4=function(S){this.dispatchEvent(new cGv(S,this))};
g.B9(cGv,g.BH);g.B9(yy,z2);yy.prototype.B=function(){};
yy.prototype.c_=function(){this.B();yy.bJ.c_.call(this)};
yy.prototype.mP=function(){this.B();yy.bJ.mP.call(this)};
yy.prototype.Dk=function(){this.B();yy.bJ.Dk.call(this)};
g.B9(YN,yy);YN.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var JkZ=class extends g.JW{constructor(S){super();this.N=S||window;this.C=[]}listen(S,W,m,a){m=(0,g.D6)(m,a||this.N);S=g.wd(S,W,m);this.C.push(S);return S}Pj(S,W,m,a){m=(0,g.D6)(m,a||this.N);S=N78(S,W,m);this.C.push(S);return S}Zb(S){g.S0(S);g.v9(this.C,S)}removeAll(){g.S0(this.C);this.C.length=0}j9(){this.removeAll();super.j9()}};var qCN=class extends g.gL{constructor(S){super(S);this.j=this.endscreen=null;this.N={};this.W={};this.A=this.B=null;this.Z=[];this.C=null;this.iY=!0;this.V=0;S=S.K();this.S=g.PW(S)||g.hu(S);this.events=new g.JC(this);g.R(this,this.events);this.events.L(this.player,g.yC("creatorendscreen"),this.onCueRangeEnter);this.events.L(this.player,g.Yf("creatorendscreen"),this.onCueRangeExit);this.events.L(this.player,"resize",this.oL);this.events.L(window,"focus",this.U);this.load();const W=g.nX("STYLE");(g.an("HEAD")[0]||
document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.ju(W)});
W.sheet&&(W.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),W.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!qw(this)){var S=g.Dpj(this.player.getVideoData());S?(S=T2(S,W8N(this)),pl(this,S,!1)):BNg(this)}}unload(){pl(this,null);this.j&&(this.j.abort(),this.j=null);super.unload()}pJ(S,W){return qw(this)?S==="loadCustomEndscreenRenderer"?(S=T2(W,"new"),pl(this,S),!0):null:null}getOptions(){return qw(this)?["loadCustomEndscreenRenderer"]:[]}oL(){if(this.endscreen&&this.endscreen.elements){var S=this.player.getVideoContentRect();if(S&&S.width!==0&&S.height!==0){var W=this.player.getPlayerSize();
if(W&&W.width!==0&&W.height!==0){var m=S.width/S.height;var a=0;var J=-1;for(var B=0;B<YCQ.length;B++){var E=Math.abs(W.width-YCQ[B]);if(J===-1||a>=E)J=B,a=E}a=Gtx[J];this.B&&g.Zt(this.B.element,"outline-width",Math.max(W.width,W.height)+"px");for(W=0;W<this.endscreen.elements.length;++W){B=this.endscreen.elements[W].id;J=this.N[B];E=this.W[B];if(!J||!E)continue;const y=E.width*m/E.aspectRatio;var z=Math.round(E.width*S.width);B=Math.round(y*S.height);const Y=S.left+Math.round(E.left*S.width),G=S.top+
Math.round(E.top*S.height);g.z6(J.element,z,B);g.Dt(J.element,Y,G);g.BL(J.element,KX9);z>256||B>256?g.my(J.element,"ytp-ce-large-round"):z>96||B>96?g.my(J.element,"ytp-ce-medium-round"):g.my(J.element,"ytp-ce-small-round");g.BL(J.element,ThN);z=E.left+E.width/2;E=E.top+y/2;g.my(J.element,z<=.5&&E<=.5?"ytp-ce-top-left-quad":z>.5&&E<=.5?"ytp-ce-top-right-quad":z<=.5&&E>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.BL(J.element,Gtx);g.my(J.element,a);(J=g.BI(document,"div","ytp-ce-expanding-overlay-body",
J.element)[0])&&g.Zt(J,"height",`${B}px`)}}}}}onCueRangeEnter(S){if(this.endscreen)if(S.getId()==="ytp-ce-in-endscreen")go(this,this.endscreen.impressionUrls),(S=g.l2())&&this.endscreen.visualElement&&g.m_(S,this.endscreen.visualElement),this.C&&(g.my(this.C,"ytp-ce-element-show"),this.C.removeAttribute("aria-hidden"),this.player.e1()?g.my(this.C,"ytp-ce-hide-button-lower"):g.J$(this.C,"ytp-ce-hide-button-lower"));else{S=S.getId().substring(15);var W=this.N[S],m=this.W[S];g.my(W.element,"ytp-ce-element-show");
W.element.removeAttribute("aria-hidden");W=this.player.getRootNode();g.my(W,"ytp-ce-shown");go(this,m.impressionUrls);(W=g.l2())&&g.m_(W,m.visualElement);this.player.K().Z&&g.AJ(this.player,"endscreenelementshown",S)}}onCueRangeExit(S){if(S.getId()==="ytp-ce-in-endscreen")this.C&&(g.J$(this.C,"ytp-ce-element-show"),this.C.setAttribute("aria-hidden","true"));else{S=S.getId().substring(15);var W=this.N[S];g.J$(W.element,"ytp-ce-element-show");W.element.setAttribute("aria-hidden","true");W=this.player.getRootNode();
g.J$(W,"ytp-ce-shown");this.player.K().Z&&g.AJ(this.player,"endscreenelementhidden",S)}}U(S){S.target===window&&(new g.rr(()=>{for(const W of Object.values(this.N))g.BL(W.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}UV(S){for(const W of Object.values(this.N))S?W.element.setAttribute("hidden",""):W.element.removeAttribute("hidden")}h9(S){this.C&&this.player.getRootNode().removeChild(this.C);
S&&(g.my(S,"ytp-ce-hide-button-container"),this.C=S,g.TJ(this.player,this.C,4))}},YCQ=[346,426,470,506,570,640,853,1280,1920],Gtx="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ThN=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],KX9=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var TNZ=class{constructor(S,W,m,a){this.value=S;this.target=W;this.showLinkIcon=m;this.N=a}C(){return this.value?this.value:null}},K8Q={oQ:"current",Nf:"new"};var F8$=class{constructor(S,W,m){this.type=S;this.trigger=W;this.url=m}},qQH={CLOSE:"close",Pt:"openUrl",SUBSCRIBE:"subscribe"},p9w={Ki:"click",CLOSE:"close",PH:"hidden",s29:"rollOut",n6n:"rollOver",hqn:"shown"};var NNQ=class{constructor(S,W,m,a,J){this.id=S;this.type=W;this.style=m;this.data=J;this.action=a||[]}Od(){const S=npp(this,W=>W.type==="openUrl"&&W.url!=null);
return S?S.url:null}},Znx={Kz:"anchored",bE:"branding",CHANNEL:"channel",MB:"cta",tB:"highlightText",aA:"label",PLAYLIST:"playlist",POPUP:"popup",kND:"speech",SUBSCRIBE:"subscribe",Bd_:"title",VIDEO:"video",mw2:"website"},ANZ={bE:"branding",tK:"card",wl:"drawer",Xx:"highlight",JH:"marker",US:"promotion",TEXT:"text",Hn2:"widget"};var pFN=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
FXp=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var Vmn=class{constructor(S,W){this.context=S;this.C=W}};var Cw$=class{constructor(S,W){this.merchant=S;this.price=W}};var nlZ=class extends g.JW{constructor(S,W){super();this.element=S;this.context=W;this.p_=!1;this.g2=new Map;this.hX=new Map;this.context.X.addEventListener(g.yC("annotations_module"),m=>{(m=this.g2.get(m))&&m.apply(this)});
this.context.X.addEventListener(g.Yf("annotations_module"),m=>{(m=this.hX.get(m))&&m.apply(this)})}addCueRange(S,W,m,a,J){S=new g.jX(S,W,{id:m,
namespace:"annotations_module"});a&&this.g2.set(S,a);J&&this.hX.set(S,J);this.context.X.iQ([S],1)}bY(){this.context.N.subscribe("resize",this.AX,this)}IL(){return this.element}K_(S,W,m,a,J,B){if(this.p_)return!1;B&&(B.stopPropagation(),B.preventDefault());this.navigate(S,m,a,J);return!1}show(){}hide(){}destroy(){g.ju(this.IL())}AX(){}navigate(S,W,m,a){const J=S.C();if(J){var B=gpQ(J,S.target),E=()=>{S.N&&this.context.X.pauseVideo();const z=this.context.videoData.i$||!1,y=g.nO(J||"");z&&y&&(y.v||y.list)?
this.context.X.HA(y.v,W,y.list,!1):g.aR(J||"",B==="current"?"_top":void 0,W)};
B==="new"&&(E(),E=null);t1(this.context.logger,m,E,a);u9$(J)||(m=g.l2(),a=W.itct,m&&a&&g.Bz(m,g.Qj(a)))}}j9(){this.g2.clear();this.hX.clear();super.j9()}createElement(S){S=new g.c(S);g.R(this,S);return S.element}};var z_n=class extends nlZ{constructor(S,W,m){super(W,m);this.X=S;this.eventId=null;this.C3=this.Hn=this.sV=this.B=this.isInitialized=!1;this.cards=[];this.R2=this.A=this.cn=this.W=this.ZQ=this.C=null;this.iY=[];this.U=this.Z=this.Mi=this.GN=null;this.V=0;this.q2=new g.rr(()=>{},m.Y.hO?4E3:3E3);
g.R(this,this.q2);this.mU=new g.rr(()=>{});
g.R(this,this.mU);this.vn=new Vmn(m,(a,J,B,E,z,y)=>{U0(this,a,J,B,E,z,y)});
this.S=new g.c({G:"div",O:"iv-drawer",J:{id:"iv-drawer"},D:[{G:"div",O:"iv-drawer-header",J:{"aria-role":"heading"},D:[{G:"span",O:"iv-drawer-header-text"},{G:"button",Wn:["iv-drawer-close-button","ytp-button"],J:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",O:"iv-drawer-content"}]});g.R(this,this.S);this.j=this.S.element;this.d2=new g.HV(this.S,330);g.R(this,this.d2);this.x6=g.EN("iv-drawer-header-text",this.j);this.N=g.EN("iv-drawer-content",this.j);this.addCueRange(0,m.videoData.lengthSeconds*
1E3,"",()=>{this.sV&&xN(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.sV=this.B)&&Ib(this)});
this.TN=new g.JC(this);g.R(this,this.TN);this.X.addEventListener("videodatachange",this.bV.bind(this))}bV(){this.U&&i$(this,this.U)}isAvailable(){var S;if(S=!!this.cards.length)(S=this.X.getRootNode())?(S=g.yE(S),S=173<S.width&&173<S.height):S=!1;return S}AX(){const S=this.isAvailable();g.Yr(this.IL(),S);g.I(this.context.X.getRootNode(),g.hf.IV_DRAWER_ENABLED,S);mE(this.X)}destroy(){this.X.qv(!1);try{this.X.getRootNode().removeChild(this.j)}catch(S){}g.Yy(this.iY);g.Bp(this.TN);this.ZQ&&this.ZQ.dispose();
this.W&&this.W.dispose();super.destroy()}Yf(){this.context.C.listen(g.EN("iv-drawer-close-button",this.j),"click",this.K3,this);this.context.C.listen(this.N,"touchend",()=>{this.q2.start()});
this.context.C.listen(this.N,"scroll",this.TV,this);this.context.N.subscribe("onHideControls",()=>{this.Hn=!0});
this.context.N.subscribe("onShowControls",()=>{this.Hn=!1});
this.context.N.subscribe("onVideoAreaChange",()=>{this.Hn=g.WL(this.X.getRootNode(),"ytp-autohide")});
this.iY.push(g.yG("iv-button-shown",this.Sg,this));this.iY.push(g.yG("iv-button-hidden",this.Fz,this));vpH(this)}findLastIndex(S){if(this.cards.length===0)return 0;const W=g.OQ(this.cards,m=>S.Ka.startMs>m.Ka.startMs||S.Ka.startMs===m.Ka.startMs&&S.Ka.timestamp>=m.Ka.timestamp?!0:!1);
return W===-1?0:W+1}K3(){if(this.B){t1(this.context.logger,kN(this).vQ.close);var S=g.l2();S&&this.Z&&g.Bz(S,this.Z);Ib(this)}}TV(){g.I(this.j,"iv-drawer-scrolled",this.N.scrollTop>0)}Sg(){const S=g.l2();var W=kN(this);W=W?W.Mi:this.Mi;S&&W&&g.aP(S,[W])}Fz(){const S=g.l2();var W=kN(this);W=W?W.Mi:this.Mi;S&&W&&g.JY(S,[W])}tv(){const S=kN(this);t1(this.context.logger,S.vQ.uA);const W=g.l2();if(W&&S)if(this.X.T("web_infocards_teaser_show_logging_fix")){const m=[];S.De&&m.push(S.De);S.Mi&&m.push(S.Mi);
m.length>0&&g.aP(W,m)}else g.aP(W,[S.De,S.Mi])}Qc(){const S=g.l2(),W=kN(this);S&&W&&g.JY(S,[W.De])}yc(S){const W=kN(this),m=g.l2();this.C?S?(S=this.context.logger,t1(S,W.vQ.W3),S.X.sendVideoStatsEngageEvent(4,void 0),m&&W.De&&g.Bz(m,W.De)):(S=this.context.logger,t1(S,W.vQ.W3),S.X.sendVideoStatsEngageEvent(4,void 0),m&&W.Mi&&g.Bz(m,W.Mi)):(S=this.context.logger,t1(S,W.vQ.W3),S.X.sendVideoStatsEngageEvent(4,void 0),m&&this.Mi&&g.Bz(m,this.Mi))}};var sSQ=class extends nlZ{constructor(S,W,m){super(S,W);this.annotation=m;this.isActive=!1}bY(){super.bY();xxH(this)}show(){super.show();const S=g.l2();var W=this.annotation.data;S&&W&&(W=W.session_data)&&g.aP(S,[g.Qj(W.itct)])}hide(){super.hide();const S=g.l2();var W=this.annotation.data;S&&W&&(W=W.session_data)&&g.JY(S,[g.Qj(W.itct)])}};var bnp=class extends sSQ{constructor(S,W,m){super(S,W,m);this.C=null;this.B=!1;this.N=null}show(){if(!this.isActive){super.show();if(!this.B){g.my(this.IL(),"iv-branding");const S=this.annotation.data;this.C=this.createElement({G:"img",Wn:["branding-img","iv-click-target"],J:{"aria-label":"Channel watermark",src:S.image_url,width:S.image_width,height:S.image_height}});g.Yr(this.C,!1);const W=this.createElement({G:"button",Wn:["branding-img-container","ytp-button"]});W.appendChild(this.C);this.IL().appendChild(W);
const m=this.annotation.Od();m&&U0(this,W,m,this.annotation.id,S.session_data);this.B=!0}g.Yr(this.IL(),!0);this.isActive=!0;if(this.C){try{inQ(this,this.C)}catch{}g.my(this.context.X.getRootNode(),"ytp-branding-shown");this.context.X.getRootNode().style.setProperty("--branding-image-width",`${this.C.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.Yr(this.IL(),!1),this.isActive=!1,g.J$(this.context.X.getRootNode(),"ytp-branding-shown"))}destroy(){this.N&&(this.N.dispose(),this.N=
null);g.J$(this.context.X.getRootNode(),"ytp-branding-shown");super.destroy()}};var Bh9=class{constructor(S,W,m,a,J,B,E){this.C=S;this.B=W;this.Y=m;this.videoData=a;this.logger=J;this.X=B;this.N=E}};var op$=class extends sSQ{constructor(S,W,m){super(S,W,m);this.Z=this.isCollapsed=this.S=!1;this.W=5E3;this.N=this.B=this.C=this.j=null;this.V=this.createElement({G:"div",Wn:["iv-promo-contents"]});this.A=new g.rr(()=>{this.C.setAttribute("aria-hidden","true");g.Yr(this.B,!1);g.Yr(this.N,!0)},700,this);
g.R(this,this.A)}show(){this.isActive||(super.show(),this.S||(Pww(this),this.S=!0),g.Yr(this.IL(),!0),g.aG(function(){g.J$(this.IL(),"iv-promo-inactive")},100,this),this.IL().removeAttribute("aria-hidden"),this.isActive=!0,h1(this),dxx(this),IZg(this,this.W))}hide(){this.isActive&&(g.my(this.IL(),"iv-promo-inactive"),this.isActive=!1,this.IL().setAttribute("aria-hidden","true"))}K_(S,W,m,a,J,B){return this.isCollapsed?!1:super.K_(S,W,m,a,J,B)}q2(S){this.Z=!0;
$N(this,500,S)}vn(){this.Z=!1;fZg(this)}iY(S){S.stopPropagation();this.hide()}U(S){S.stopPropagation();h1(this);this.isCollapsed=!0;g.my(this.IL(),"iv-promo-collapsed-no-delay");this.A.start()}destroy(){this.A.dispose();super.destroy()}};var uZg=class{constructor(S){this.X=S}};g.FL("annotations_module",class extends g.gL{constructor(S){super(S);this.U=this.Z=!1;this.loadNumber=0;this.V={};this.logger=new uZg(this.player);this.A=new g.JC(this);this.W=this.j=null;this.events=new g.JC(this);this.FM=this.S=this.C=null;this.bY=[];g.R(this,this.A);this.A.L(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.A.L(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.A.L(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.A.L(this.player,"resize",m=>{this.publish("resize",m)});
this.A.L(this.player,"presentingplayerstatechange",m=>{this.publish("presentingplayerstatechange",m)});
this.subscribe("presentingplayerstatechange",this.q2,this);this.subscribe("resize",this.iY,this);this.player.K().GN.subscribe("vast_info_card_add",this.vn,this);g.R(this,this.events);this.AX=this.createElement({G:"div",O:"video-custom-annotations"});this.N=new g.c({G:"div",Wn:["ytp-player-content","ytp-iv-player-content"]});g.R(this,this.N);g.TJ(this.player,this.N.element,4);this.N.hide();this.B=new g.c({G:"div",Wn:["ytp-iv-video-content"]});g.R(this,this.B);S=this.createElement({G:"div",O:"video-annotations"});
S.appendChild(this.AX);this.B.element.appendChild(S);this.E3()?this.load():this.player.T("web_fix_annotations")&&(this.j=()=>{this.loaded||this.n_()||!this.E3()||($x9(this),this.load())},this.player.addEventListener("videodatachange",this.j));
const W=this.createElement({G:"style"});(g.an("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.ju(W)});
if(S=W.sheet){for(const m of pFN)S.insertRule(m,0);for(const m of FXp)S.insertRule(m,0)}}pJ(S,W){if(!kgg(this.player.K().playerStyle))return null;switch(S){case "loadCustomAnnotationsXml":return(S=g.aT(W))&&Z_(this,S),!0;case "removeCustomAnnotationById":return W&&this.C&&(Rb(this.C,W),mE(this.player)),!0}return null}getOptions(){return kgg(this.player.K().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}E3(){const S=this.player.getVideoData(),W=S.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return S.i$||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.T("web_fix_annotations")?cNg(this)?W?.isWatermarkEnforced===!0?!0:W?.isAnnotationsEnabled??!1:!1:cNg(this)}iY(){if(this.B){var S=this.player.QD().getVideoContentRect(!0);g.z6(this.B.element,S.width,S.height);g.Dt(this.B.element,S.left,S.top)}if(this.C){var W=this.player.Cy();S=this.C;W=W.width;g.I(S.j,"iv-drawer-small",W<=426);g.I(S.j,"iv-drawer-big",W>=1280)}}q2(S){Dx8(this,S.state);S.state.C(2)&&(this.e1()&&this.Je()&&this.player.getPresentingPlayerType()!==
2&&this.I7(!1),this.qv(!1))}load(){super.load();Dx8(this,this.player.getPlayerStateObject());this.loadNumber++;const S=this.player.getVideoData();aPN(this,S);g.TJ(this.player,this.B.element,4);this.iY();var W=g.RV(S);const m=S.v4();if(this.player.T("web_fix_annotations")){if(W&&(W.featuredChannel&&ykN(this,W.featuredChannel,W.annotationId||"branding",S.videoId||null,S.eventId||null),W=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,W?.isWatermarkEnforced&&
!W?.isAnnotationsEnabled))return;m&&Nw(this,m)}else m&&Nw(this,m),W&&W.featuredChannel&&ykN(this,W.featuredChannel,W.annotationId||"branding",S.videoId||null,S.eventId||null);this.FM=g.EN("ytp-cards-button",this.player.getRootNode());S.P1()&&mKv(this,S)}onVideoDataChange(S){const W=this.player.getVideoData();W.dZ&&WX9(this,W.dZ,S)}unload(){this.player.Zz("annotations_module");for(const S of Object.keys(this.V))this.V[S].destroy();this.S=null;this.C&&(this.C.destroy(),this.C=null,mE(this.player));
this.Z=!1;this.W&&(this.W.abort(),this.W=null);this.U=!1;this.V={};this.N.hide();super.unload();this.B.detach();$x9(this)}vn(S){S===this.player.getVideoData().videoId&&(this.loaded?ElN(this):this.load())}e1(){return this.C?.isAvailable()||this.U}Je(){return!!this.C&&this.C.B}I7(S,W=!1,m){this.e1();this.C&&(S?m?xN(this.C,m,W):xN(this.C,"YOUTUBE_DRAWER_AUTO_OPEN",W):Ib(this.C))}qv(S,W){this.player.publish(S?"cardsteasershow":"cardsteaserhide",W)}j9(){this.player.K().GN.unsubscribe("vast_info_card_add",
this.vn,this);g.J$(this.player.getRootNode(),g.hf.IV_DRAWER_OPEN);var S=this.bY,W=g.fK;for(let m=0,a=S.length;m<a;m++)W.u6(S[m]);this.bY.length=0;super.j9()}createElement(S){S=new g.c(S);g.R(this,S);return S.element}});g.FL("creatorendscreen",qCN);})(_yt_player);
