(function(g){var window=this;'use strict';var O$x=async function(S,W,m){S.N=g.Zf(W,m)},b$=function(S){S.isActive()||S.start()},ob=function(S,W){return W?S.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},jS9=function(S){return g.SB(S)||S.T("web_enable_caption_language_preference_stickiness")},QSw=function(S,W){const m=new g.Q9;
m.languageCode=S.languageCode;m.languageName=S.languageName;m.name=S.name;m.displayName=S.displayName;m.kind=S.kind;m.isDefault=!1;m.C=S.C;m.isTranslateable=S.isTranslateable;m.vssId=S.vssId;m.url=S.url;m.translationLanguage=W;S.xtags&&(m.xtags=S.xtags);S.captionId&&(m.captionId=S.captionId);return m},XFn=async function(S,W){S=S+"|"+W;
W=await g.qd();if(!W)throw g.$O("gct");return(await g.dn(W)).get("captions",S)},vlN=function(S,W,m){XFn(S,W).then(a=>{a&&m(a.trackData,new g.Q9(a.metadata))})},ro=function(S){if(!H$9.test(S))throw Error("'"+S+"' is not a valid hex color");
S.length==4&&(S=S.replace(lPZ,"#$1$1$2$2$3$3"));S=S.toLowerCase();S=parseInt(S.slice(1),16);return[S>>16,S>>8&255,S&255]},MmZ=function(){var S={};
let W="suggest_correction"in g.TL?g.TL.suggest_correction:"Edit caption";W=W||"";for(let m in S){const a=()=>String(S[m]);
W=W.replace(new RegExp("\\$\\{"+m+"\\}","gi"),a);W=W.replace(new RegExp("\\$"+m,"gi"),a)}return W},Cl=function(){return g.yM("yt-player-caption-display-settings")},UKw=function(S,W){let m=g.iw(S.segments,W);
m>=0||m<0&&(-m-1)%2===1||(m=-m-1,m>0&&W-S.segments[m-1]===1&&m<S.segments.length&&S.segments[m]-W===1?(g.X9(S.segments,m),g.X9(S.segments,m-1)):m>0&&W-S.segments[m-1]===1?S.segments[m-1]=W:m<S.segments.length&&S.segments[m]-W===1?S.segments[m]=W:(g.RZ(S.segments,m,0,W),g.RZ(S.segments,m+1,0,W)))},LXN=function(S){return S.C&&S.C.A?S.C.A+S.player.f3()<S.player.getCurrentTime():!1},R_v=function(S,W){if(S.policy.x0&&S.player.SI()){var m=g.qE(W,S.policy,{});
m.set("pot",S.player.SI());m=m.Od()}else m=g.qE(W,S.policy,{}).Od();const a={format:"RAW",withCredentials:!0};if(S.policy.GN){a.method="POST";const E=W.j;E&&Object.keys(E).length>0?a.postBody=g.ZR(E,g.zq):a.postBody=(0,g.Nn)([120,0])}S.A&&(a.responseType="arraybuffer");let J=++S.bY;const B=(0,g.t)();S.N=g.wa(m,a,3,100,-1,E=>{E.errorCode==="net.timeout"&&S.player.N2("capnt",{rn:J++})}).then(E=>{if(S.policy.N$&&J%100===1){var z=(0,g.t)();
S.player.N2("caprsp",{rn:J,ms:z-B,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;S.n_();if(S.B){var y=!(S.A?E.response:E.responseText)||E.status>=400;if(z=g.AjQ(E)){E=g.qE(S.B,S.policy,{});S.B.bH(E,z);R_v(S,S.B);break a}y?S.player.N2("capfail",{status:E.status}):(g.m6("fcb_r",(0,g.t)(),S.player.getVideoData()?.U||""),z=S.B.e9[0],y=z.O9,S.Z!=null&&S.W!==y&&(S.A?S.Z(E.response,(z.startTime+S.player.f3())*1E3):S.Z(E.responseText,(z.startTime+S.player.f3())*1E3),S.W=y))}S.B=null;S.N=null}}).S1(E=>
{S.B=null;
S.N=null;S.player.N2("capfail",{rn:J,status:E.xhr?.status})});
S.B=W;UKw(S.j,S.B.e9[0].O9)},e_Q=function(S,W){return W!=null&&W in S.N.C?S.N.C[W]:null},xKZ=function(S,W,m){const a=[];
for(const J in S.N.C){if(!S.N.C.hasOwnProperty(J))continue;const B=S.N.C[J];if(g.u0(B,m||null)){const E=B.info.captionTrack;E&&E.languageCode===W&&a.push(B)}}return a.length?a[0]:null},dKg=function(S,W){const m=[];
for(const J in S.N.C)if(S.N.C.hasOwnProperty(J)){var a=S.N.C[J];if(g.u0(a,W||null)){let B=a.info.id,E=B,z=`.${B}`,y="",Y="";if(a=a.info.captionTrack)B=a.languageCode,E=a.displayName,z=a.vssId,y=a.kind,Y=a.id;else{{a=B;let G=g.TVl.get(a);G==null&&(G=i$8[a]||i$8[a.replace(/-/g,"_")],g.TVl.set(a,G));a=G}E=a||E}m.push(new g.Q9({id:J,languageCode:B,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:z,kind:y,captionId:Y}))}}return m},IPp=function(S,W,m,a){let J=W/360*16;
W>=S&&(S=640,a>m*1.3&&(S=480),J=m/S*16);return J},PHH=function(S){let W=1+.25*(S.fontSizeIncrement||0);
if(S.offset===0||S.offset===2)W*=.8;return W},fPv=function(S,W){let m="vertical-rl";
S.C.gV===1&&(m="vertical-lr");g.Tc&&(m=m==="vertical-lr"?"tb-lr":"tb-rl");g.Zt(W,"-o-writing-mode",m);g.Zt(W,"-webkit-writing-mode",m);g.Zt(W,"writing-mode",m);g.Zt(W,"text-orientation","upright");g.my(W,"ytp-vertical-caption");S.N.params.KW===3&&(g.Zt(W,"text-orientation",""),g.Zt(W,"transform","rotate(180deg)"))},kt$=function(S,W){const m={};
var a=W.background?W.background:S.C.v1.background;if(W.backgroundOpacity!=null||W.background){var J=W.backgroundOpacity!=null?W.backgroundOpacity:S.C.v1.backgroundOpacity;a=ro(a);m.background="rgba("+a[0]+","+a[1]+","+a[2]+","+J+")";S.TV&&(m["box-decoration-break"]="clone",m["border-radius"]=`${S.g2/8}px`)}if(W.fontSizeIncrement!=null||W.offset!=null)m["font-size"]=`${S.ZQ*PHH(W)}px`;a=1;J=W.color||S.C.v1.color;if(W.color||W.textOpacity!=null)J=ro(J),a=W.textOpacity==null?S.C.v1.textOpacity:W.textOpacity,
J="rgba("+J[0]+","+J[1]+","+J[2]+","+a+")",m.color=J,m.fill=J;var B=W.charEdgeStyle;B===0&&(B=void 0);if(B){J=`rgba(34, 34, 34, ${a})`;let y=`rgba(204, 204, 204, ${a})`;W.PB&&(y=J=W.PB);const Y=S.ZQ/16/2,G=Math.max(Y,1);var E=Math.max(2*Y,1),z=Math.max(3*Y,1);const K=Math.max(5*Y,1);a=[];switch(B){case 4:for(;z<=K;z+=Y)a.push(`${E}px ${E}px ${z}px ${J}`);break;case 1:E=window.devicePixelRatio>=2?.5:1;for(B=G;B<=z;B+=E)a.push(`${B}px ${B}px ${J}`);break;case 2:a.push(`${G}px ${G}px ${y}`);a.push(`-${G}px -${G}px ${J}`);
break;case 3:for(z=0;z<5;z++)a.push(`0 0 ${E}px ${J}`)}m["text-shadow"]=a.join(", ")}J="";switch(W.fontFamily){case 1:J='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:J='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:J='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:J='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:J='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:J=g.V_()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:J='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}J&&(m["font-family"]=J);J=W.offset;J==null&&(J=S.C.v1.offset);switch(J){case 0:m["vertical-align"]="sub";break;case 2:m["vertical-align"]="super"}W.fontFamily===7&&(m["font-variant"]="small-caps");W.bold&&(m["font-weight"]="bold");W.italic&&(m["font-style"]="italic");W.underline&&
(m["text-decoration"]="underline");W.RK&&(m.visibility="hidden");W.kJ===1&&S.B&&(m["text-combine-upright"]="all",m["text-orientation"]="mixed",J=g.Bd||g.Pp,S.N.params.KW===3?m.transform=J?"rotate(90deg)":"rotate(180deg)":J&&(m.transform="rotate(-90deg)"));if(W.textEmphasis===1||W.textEmphasis===2||W.textEmphasis===3||W.textEmphasis===4||W.textEmphasis===5)if(g.Bd)m["font-weight"]="bold";else switch(m["text-emphasis-style"]="filled circle",m["text-emphasis-color"]="currentcolor",m["webkit-text-emphasis"]=
"filled circle",W.textEmphasis){case 4:case 3:m["text-emphasis-position"]="under left";m["webkit-text-emphasis-position"]="under left";break;case 5:case 2:m["text-emphasis-position"]="over right",m["webkit-text-emphasis-position"]="over right"}return m},cx=function(S){S=S.split("px");
return S.length>0?(S=Number(S[0]))?S:0:0},tmv=function(S,W,m){S.AX=S.AX||!!m;
const a={};Object.assign(a,S.C.v1);Object.assign(a,m||W.C);Object.assign(a,S.Qc.v1);(m=!S.V)&&$Kp(S);let J=S.GN&&S.cn&&g.aS(a,S.cn)?S.GN:h_w(S,a);const B=typeof W.text==="string",E=B?W.text.split("\n"):[W.text];for(let y=0;y<E.length;y++){var z=y>0||!W.append;const Y=E[y];z&&!m?($Kp(S),J=h_w(S,a)):z&&m&&(m=!1);Y&&(J.appendChild(B?g.sN(Y):Y),B||Y.tagName!=="RUBY"||Y.childElementCount!==4||g.Bd||!g.on(Y.children[2],"text-emphasis")||(z=S.B?"padding-right":"padding-top",g.on(Y.children[2],"text-emphasis-position")&&
(z=S.B?"padding-left":"padding-bottom"),g.Td?g.Zt(J,z,"1em"):g.Zt(J,z,"0.5em")))}S.cn=a;S.GN=J;S.W.push(W)},$Kp=function(S){S.V=g.nX("SPAN");
g.Zt(S.V,{display:"block"});g.my(S.V,"caption-visual-line");S.j.appendChild(S.V)},h_w=function(S,W){const m=g.nX("SPAN");
g.Zt(m,{display:"inline-block","white-space":"pre-wrap"});g.Zt(m,kt$(S,W));m.classList.add("ytp-caption-segment");S.V.appendChild(m);m.previousElementSibling&&(g.Zt(m.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Zt(m,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return m},Z$N=function(S,W,m){if(S===255&&W===255||!S&&!W)return{vZ:S,
kW:W,result:0};S=Akv[S];W=Akv[W];if(S&128){var a;if(a=!(W&128))a=W,a=m.FD()&&m.kW===a;if(a)return{vZ:S,kW:W,result:1}}else if(W&128&&1<=S&&S<=31)return{vZ:S,kW:W,result:2};return{vZ:S,kW:W,result:3}},b$Z=function(S,W,m,a){W===255&&m===255||!W&&!m?(++S.B===45&&S.reset(),S.j.N.clear(),S.A.N.clear()):(S.B=0,NhZ(S.j,W,m,a))},olQ=function(S,W){S.C.sort((m,a)=>{const J=m.time-a.time;
return J===0?m.order-a.order:J});
for(const m of S.C)S.time=m.time,m.type===0?b$Z(S,m.In,m.yv,W):m.type===1&&S.N&496&&NhZ(S.A,m.In,m.yv,W);S.C.length=0},wF9=function(S,W){switch(S){case 0:return rkH[(W&127)-32];
case 1:return CH9[W&15];case 2:return ckH[W&31];case 3:return DKH[W&31]}return 0},D_=function(S,W){if(S.style.type===3){var m=0,a=0,J=S.A.time+0,B="",E="",z=J;
for(var y=1;y<=15;++y){var Y=!1;for(var G=a?a:1;G<=32;++G){var K=S.B[y][G];if(K.C!==0){m===0&&(m=y,a=G);Y=String.fromCharCode(K.C);var T=K.timestamp;T<J&&(J=T);K.timestamp=z;E&&(B+=E,E="");B+=Y;Y=!0}if((K.C===0||G===32)&&Y){E="\n";break}else if(a&&!Y)break}if(m&&!Y)break}B&&W.j(m,a,J,z,B)}else for(a=m=0,B=J=S.A.time+0,E=1;E<=15;++E)for(z="",y=1;y<=32;++y)if(G=S.B[E][y],K=G.C,K!==0&&(m===0&&(m=E,a=y),Y=String.fromCharCode(K),T=G.timestamp,T<=J&&(J=T),z+=Y,G.reset()),y===32||K===0)z&&W.j(m,a,J,B,z),
J=B,z="",a=m=0},wo=function(S){return S.B[S.row][S.N]},S1=function(S,W,m){W>=2&&S.N>1&&(--S.N,wo(S).C=0);
const a=wo(S);a.timestamp=S.A.time+0;a.C=wF9(W,m);S.N<32&&S.N++},SRn=function(S,W,m,a){for(let E=0;E<a;E++)for(let z=0;z<=32;z++){var J=S.B[W+E][z],B=S.B[m+E][z];
J.C=B.C;J.timestamp=B.timestamp}},W0=function(S,W,m){for(let a=0;a<m;a++)for(let J=0;J<=32;J++)S.B[W+a][J].reset()},mR=function(S){S.row=S.C>0?S.C:1;
S.N=1;W0(S,0,15)},WWN=function(S){S.style.set(1);
S.C=S.j;S.C.C=0;S.C.style=S.style;S.B.mode=1<<S.C.j},aN=function(S,W,m){const a=S.N;
let J=!1;switch(S.style.get()){case 4:case 1:case 2:S.style.get()===4&&a.C>0||(D_(a,m),mR(S.N),mR(S.j),a.row=15,a.C=W,J=!0)}S.style.set(3);S.C=a;S.C.style=S.style;S.B.mode=1<<a.j;J?a.N=1:a.C!==W&&(a.C>W?(D_(a,m),W0(a,a.row-a.C,W)):a.row<W&&(W=a.C),a.C=W)},ma$=function(S){S.style.set(4);
S.C=S.text;S.C.style=S.style;S.B.mode=1<<S.C.j},NhZ=function(S,W,m,a){S.N.update();
W=Z$N(W,m,S.N);switch(W.result){case 0:return;case 1:case 2:return}var J=W.vZ;W=W.kW;if(32<=J||!J)S.C.mode&S.C.N&&(m=J,m&128&&(m=127),W&128&&(W=127),S=S.j.C,m&96&&S1(S,0,m),W&96&&S1(S,0,W),m!==0&&W!==0&&S.style.type===3&&D_(S,a));else if(J&16)a:if(!S.N.matches(J,W)&&(m=S.N,m.vZ=J,m.kW=W,m.state=2,m=J&8?S.W:S.B,S.j=m,S.C.mode=1<<(S.A<<2)+(m.A<<1)+(m.style.type===4?1:0),(S.C.mode|1<<(S.A<<2)+(m.A<<1)+(m.style.type!==4?1:0))&S.C.N))if(W&64){a=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(J&7)<<1|W>>5&1];
S=W&16?((W&14)>>1)*4:0;W=m.C;switch(m.style.get()){case 4:a=W.row;break;case 3:if(a!==W.row){if(a<W.C&&(a=W.C,a===W.row))break;var B=1+W.row-W.C;const E=1+a-W.C;SRn(W,E,B,W.C);m=B;J=W.C;E<B?(B=E+J-B,B>0&&(m+=B,J-=B)):(B=B+J-E,B>0&&(J-=B));W0(W,m,J)}}W.row=a;W.N=S+1}else switch(J&7){case 1:switch(W&112){case 32:S1(m.C,0,32);break a;case 48:W===57?(a=m.C,wo(a).C=0,a.N<32&&a.N++):S1(m.C,1,W&15)}break;case 2:W&32&&S1(m.C,2,W&31);break;case 3:W&32&&S1(m.C,3,W&31);break;case 4:case 5:if(32<=W&&W<=47)switch(W){case 32:WWN(m);
break;case 33:a=m.C;a.N>1&&(--a.N,wo(a).C=0);break;case 36:a=m.C;S=wo(a);for(W=0;W<=15;W++)for(m=0;m<=32;m++)if(a.B[W][m]===S){for(;m<=32;m++)a.B[W][m].reset();break}break;case 37:aN(m,2,a);break;case 38:aN(m,3,a);break;case 39:aN(m,4,a);break;case 40:S1(m.C,0,32);break;case 41:a=m;a.style.set(2);a.C=a.N;a.C.C=0;a.C.style=a.style;a.B.mode=1<<a.C.j;break;case 42:a=m;S=a.text;S.C=15;S.style.set(4);mR(S);ma$(a);break;case 43:ma$(m);break;case 44:S=m;W=S.N;switch(S.style.get()){case 1:case 2:case 3:D_(W,
a)}W0(W,0,15);break;case 45:b:{W=m;S=W.C;switch(W.style.get()){default:case 2:case 1:break b;case 4:if(S.row<15){++S.row;S.N=1;break b}break;case 3:}S.C<2&&(S.C=2,S.row<S.C&&(S.row=S.C));W=S.row-S.C+1;D_(S,a);SRn(S,W,W+1,S.C-1);W0(S,S.row,1)}break;case 46:W0(m.j,0,15);break;case 47:S=m,D_(S.N,a),S.j.updateTime(S.B.time+0),a=S.j,S.j=S.N,S.N=a,WWN(S)}break;case 7:switch(W){case 33:case 34:case 35:a=m.C,(a.N+=W&3)>32&&(a.N=32)}}},Jxg=function(S,W,m,a,J,B,E){var z=B[0];
let y=E[z.getAttribute("p")];if(y.wr===1){var Y=B[1],G=B[2];B=B[3];z.getAttribute("t");Y.getAttribute("t");G.getAttribute("t");B.getAttribute("t");z.getAttribute("p");Y.getAttribute("p");B.getAttribute("p");E=E[G.getAttribute("p")];z=aN9(z.textContent,Y.textContent,G.textContent,B.textContent,E);return new JH(S,W,J,m,z,a,y)}switch(y.wr){case 9:case 10:y.textEmphasis=1;break;case 11:y.textEmphasis=2;break;case 12:y.textEmphasis=3;break;case 13:y.textEmphasis=4;break;case 14:y.textEmphasis=5}return new JH(S,
W,J,m,z.textContent||"",a,y)},aN9=function(S,W,m,a,J){var B=g.V_();
const E=B?g.nX("DIV"):g.nX("RUBY"),z=g.nX("SPAN");z.textContent=S;E.appendChild(z);S=B?g.nX("DIV"):g.nX("RP");S.textContent=W;E.appendChild(S);W=B?g.nX("DIV"):g.nX("RT");W.textContent=m;E.appendChild(W);m=J.wr;if(m===10||m===11||m===12||m===13||m===14)if(g.Zt(W,"text-emphasis-style","filled circle"),g.Zt(W,"text-emphasis-color","currentcolor"),g.Zt(W,"webkit-text-emphasis","filled circle"),J.wr===11||J.wr===13)g.Zt(W,"webkit-text-emphasis-position","under left"),g.Zt(W,"text-emphasis-position","under left");
m=!0;if(J.wr===4||J.wr===7||J.wr===12||J.wr===14)g.Zt(E,"ruby-position","over"),g.Zt(E,"-webkit-ruby-position","before");else if(J.wr===5||J.wr===6||J.wr===11||J.wr===13)g.Zt(E,"ruby-position","under"),g.Zt(E,"-webkit-ruby-position","after"),m=!1;J=B?g.nX("DIV"):g.nX("RP");J.textContent=a;E.appendChild(J);B&&(a=m,g.Zt(E,{display:"inline-block",position:"relative"}),B=E.firstElementChild.nextElementSibling,g.Zt(B,"display","none"),B=B.nextElementSibling,g.Zt(B,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Zt(E.lastElementChild,"display","none"),a?(g.Zt(E,"padding-top","0.6em"),g.Zt(B,"top","0")):(g.Zt(E,"padding-bottom","0.6em"),g.Zt(B,"bottom","0")));return E},Bb9=function(S){const W="_"+B0++;
return new Ep(0,0x8000000000000,0,W,S)},zk=function(S,W){S=S.getAttribute(W);
if(S!=null)return Number(S)},yp=function(S,W){S=S.getAttribute(W);
if(S!=null)return S==="1"},Yw=function(S,W){S=zk(S,W);
return S!==void 0?S:null},KQ=function(S,W){S=S.getAttribute(W);
if(S!=null)return Gk.test(S),S},Ekn=function(S,W){const m={},a=W.getAttribute("ws");
Object.assign(m,a?S.S[a]:S.j);S=Yw(W,"mh");S!=null&&(m.O4=S);S=Yw(W,"ju");S!=null&&(m.textAlign=S);S=Yw(W,"pd");S!=null&&(m.KW=S);S=Yw(W,"sd");S!=null&&(m.gV=S);S=KQ(W,"wfc");S!=null&&(m.windowColor=S);W=zk(W,"wfo");W!==void 0&&(m.windowOpacity=W/255);return m},zNg=function(S,W){const m={},a=W.getAttribute("wp");
a&&Object.assign(m,S.Z[a]);S=Yw(W,"ap");S!=null&&(m.lV=S);S=zk(W,"cc");S!=null&&(m.Q6=S);S=zk(W,"ah");S!=null&&(m.Io=S);S=zk(W,"rc");S!=null&&(m.vc=S);W=zk(W,"av");W!=null&&(m.PT=W);return m},yx9=function(S,W,m,a){let J={};
Object.assign(J,zNg(S,W));Object.assign(J,Ekn(S,W));a?g.aS(J,S.j)?(a=S.A,J=S.j):a="_"+B0++:a=W.getAttribute("id")||"_"+B0++;S=zk(W,"t")+m;W=zk(W,"d")||0x8000000000000;if(J.KW===2||J.KW===3)m=J.vc,J.vc=J.Q6,J.Q6=m;return new Ep(S,W,0,a,J)},Tk=function(S){S=g.P$(Math.round(S),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-S.length)+S},YRQ=function(S,W,m,a,J){a===0&&(a=0x8000000000000);
const B={};W.wpWinPosId&&Object.assign(B,S.j.get(W.wpWinPosId));W.wsWinStyleId&&Object.assign(B,S.A.get(W.wsWinStyleId));S=W.rcRowCount;S!==void 0&&(B.vc=S);W=W.ccColCount;W!==void 0&&(B.Q6=W);if(B.KW===2||B.KW===3)W=B.vc,B.vc=B.Q6,B.Q6=W;return new Ep(m,a,0,J,B)},qe=function(S){const W=S.byteOffset;
S.byteOffset+=1;return S.C.getUint8(W)},pQ=function(S){const W=S.byteOffset;
S.byteOffset+=4;return S.C.getUint32(W)},Tbx=function(S){if(typeof S==="string")return!1;
S=new GCp(S,0);return KW$(S)},KW$=function(S){if(!(S.byteOffset<S.C.byteLength)||pQ(S)!==1380139777)return!1;
S.version=qe(S);if(S.version>1)return!1;qe(S);qe(S);qe(S);return!0},qRN=function(S,W){if(!W)return"";
S.B&&S.N.params.gV!==1&&(W*=-1);return`translate${S.B?"X":"Y"}(${W}px)`},p$$=function(S){S.vn=Array.from(S.element.getElementsByClassName("caption-visual-line"));
for(var W=S.N.params.vc,m=0,a=0,J=S.vn.length-1;m<W&&J>-1;){var B=S.vn[J];a+=S.B?B.offsetWidth:B.offsetHeight;m++;J--}S.S=a;W=Math;m=W.max;isNaN(S.q2)&&((a=S.C.Q6)?(J=g.nX("SPAN"),g.XO(J,"\u2013".repeat(a)),g.Zt(J,kt$(S,S.C.v1)),S.j.appendChild(J),S.q2=J.offsetWidth,S.j.removeChild(J)):S.q2=0);a=S.j;S.U=m.call(W,S.q2,S.yc,(S.B?a.offsetHeight:a.offsetWidth)+1)},FW9=function(S,W){p$$(S);
var m=S.vn.reduce((a,J)=>(S.B?J.offsetWidth:J.offsetHeight)+a,0);
m=S.S-m;if(m!==S.Hn){const a=m>0&&S.Hn===0,J=m<S.Hn;W||isNaN(m)||a||!J||(g.my(S.element,"ytp-rollup-mode"),S.L(S.element,"transitionend",S.K_));g.Zt(S.j,"transform",qRN(S,m));S.Hn=m}p$$(S)},nkN=function(S,W){S.C=(m,a)=>{if(m.info.B){var J=m;
if(S.aT.length>0){for(J=S.aT.shift();S.aT.length>0;)J=J.W(S.aT.shift());J=J.W(m)}if(J){m=J;try{var B=g.vh(m)*1E3}catch(q){B=m.info.startTime*1E3}try{var E=g.dbD(m)*1E3}catch(q){E=m.info.duration*1E3}if(B<0||E<0)B<0&&(B=m.info.startTime*1E3),E<0&&(E=m.info.duration*1E3);m.info.startTime=B/1E3;m.info.j=B/1E3;m.info.duration=E/1E3;m.info.Z=E/1E3;const {formatId:z,O9:y,startTimeMs:Y,durationMs:G}=S.Ti(J);B={formatId:z,startTimeMs:Y,durationMs:G,b6:y,iJ:y};E=VA8(S.Aw,B.startTimeMs);const K=(m=E>=0?S.Aw[E]:
null)?m.startTimeMs+m.durationMs:0,T=B.startTimeMs+B.durationMs;!m||B.startTimeMs-K>S.N?S.Aw.splice(E+1,0,B):(m.durationMs=Math.max(K,T)-m.startTimeMs,m.iJ=Math.max(m.iJ,B.iJ));a(S.Aw);B=g.jP(J);a=S.B;B=B.buffer.slice(B.byteOffset,B.byteLength+B.byteOffset);J=J.info.j;a.iY?a.Z==null?g.OK(a.logger,350058965,"Null loaded track meta data at captions data received"):W.BL(B,a.Z,J*1E3):g.OK(a.logger,350058965,"Null Representation at captions data received")}else g.OK(S.logger,350058965,"Empty slice")}else S.aT.push(m)};
S.X.addEventListener("sabrCaptionsDataLoaded",S.C)},VA8=function(S,W){S=g.iw(S,{startTimeMs:W},(m,a)=>m.startTimeMs-a.startTimeMs);
return S>=0?S:-S-2},sh9=function(S,W){if(!g.m2P(S)||S.C!=null&&g.ny(W,S.C)&&S.C.C.rawcc!=null)return!1;
W=!!S.C&&S.C.isManifestless&&Object.values(S.C.C).some(m=>g.u0(m,"386"));
S=!!S.C&&!S.C.isManifestless&&g.yY6(S.C);return W||S},uWN=function(S,W,m){const a=[];
for(const J in S.N.C){if(!S.N.C.hasOwnProperty(J))continue;const B=S.N.C[J];if(g.u0(B,m||null)){const E=B.info.captionTrack;E&&E.languageCode===W&&a.push(B)}}return a.length?a[0]:null},gkv=function(S,W){const m=[];
for(const J in S.N.C)if(S.N.C.hasOwnProperty(J)){var a=S.N.C[J];if(g.u0(a,W||null)){let B=a.info.id,E=B,z=`.${B}`,y="",Y="";if(a=a.info.captionTrack)B=a.languageCode,E=a.displayName,z=a.vssId,y=a.kind,Y=a.id;m.push(new g.Q9({id:J,languageCode:B,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:z,kind:y,captionId:Y}))}}return m},jhv=function(S){const W=Oan.length;
if(S.byteLength<W)return!1;S=new Uint8Array(S,0,W);for(let m=0;m<W;m++)if(Oan[m]!==S[m])return!1;return!0},Ff=function(S){S=S.split(":");
let W=0;for(const m of S)W=W*60+Number(m);return W*1E3},QhQ=function(S,W,m,a){a=Object.assign({O4:0},a);
return new Ep(S,W,m,"_"+B0++,a)},X$p=function(S,W,m,a,J,B,E,z,y){switch(E.tagName){case "b":z.bold=!0;
break;case "i":z.italic=!0;break;case "u":z.underline=!0}for(let G=0;G<E.childNodes.length;G++){var Y=E.childNodes[G];if(Y.nodeType===3)Y=new JH(W,m,a,J.id,Y.nodeValue,B||G>0,g.Sm(z)?void 0:z),y.push(Y),J.C.push(Y);else{const K={};Object.assign(K,z);X$p(S,W,m,a,J,!0,Y,K,y)}}},Haw=function(S,W,m){if(typeof W==="string"||Tbx(W))return[{trackData:W,
P3:m}];if(typeof W==="string"&&W.substring(0,6)==="WEBVTT"||typeof W!=="string"&&jhv(W))return[{trackData:W,P3:m}];const a=new DataView(W);if(a.byteLength<=8||a.getUint32(4)!==1718909296)return[];var J=g.$ul(a);if(S.Xz&&J){var B=g.RO6(J),E=g.eO7(J);J=J.s3;B&&J&&S.Xz.LH(J,B,E)}S=g.lL(a,1835295092);if(!S||!S.length||!S[0].size)return[];B=[];for(E=0;E<S.length;E++)J=S[E],J=new Uint8Array(W,J.dataOffset,J.size-(J.dataOffset-J.offset)),J=g.lg(J),B.push({trackData:J,P3:m+E*1E3});vkQ(a,B,m);return B=B.filter(z=>
!!z.trackData)},MAv=function(S,W,m){S.C||(S.C=new lNw);
S=S.C.B(W,m);Math.random()<.01&&g.IL(Error("Deprecated subtitles format in web player: WebVTT"));return S},vkQ=function(S,W,m){var a=g.Qq(S,0,1836476516);
let J=9E4;a&&(J=g.XG(a)||9E4);a=0;const B=g.lL(S,1836019558);for(let z=0;z<B.length;z++){var E=B[z];z<W.length&&(E=g.Qq(S,E.dataOffset,1953653094))&&(E=g.Qq(S,E.dataOffset,1952867444))&&(E=g.Hk(E)/J*1E3,z===0&&(a=E),W[z].P3=E-a+m||m*z*1E3)}},Ua9=function(S){const W={};
if(S=g.s6(S))W.lang=S,g.fCP.test(S)&&(W.KW=1);return W},LWp=function(S){const W=!!S.X.QT()?.cn();
return S.B==="HLS"&&W?!0:S.ZQ&&W&&S.B!=="LIVE"&&S.B!=="SABR_LIVE"},nQ=function(S,W,m=!1){const a=Vp.v1;
S.A={};Object.assign(S.A,Vp);S.A.v1={};Object.assign(S.A.v1,a);S.W={v1:{}};var J=W.backgroundOverride?S.W:S.A,B=W.background||a.background;Gk.test(B);J.v1.background=B;J=W.colorOverride?S.W:S.A;B=W.color||a.color;Gk.test(B);J.v1.color=B;J=W.windowColorOverride?S.W:S.A;B=W.windowColor||Vp.windowColor;Gk.test(B);J.windowColor=B;J=W.backgroundOpacityOverride?S.W:S.A;B=W.backgroundOpacity;B==null&&(B=a.backgroundOpacity);J.v1.backgroundOpacity=B;J=W.fontSizeIncrementOverride?S.W:S.A;B=W.fontSizeIncrement;
B==null&&(B=a.fontSizeIncrement);J.v1.fontSizeIncrement=B;B=W.fontStyleOverride?S.W:S.A;J=W.fontStyle;J==null&&(J=a.bold&&a.italic?3:a.bold?1:a.italic?2:0);B=B.v1;switch(J){case 1:B.bold=!0;delete B.italic;break;case 2:delete B.bold;B.italic=!0;break;case 3:B.bold=!0;B.italic=!0;break;default:delete B.bold,delete B.italic}J=W.textOpacityOverride?S.W:S.A;B=W.textOpacity;B==null&&(B=a.textOpacity);J.v1.textOpacity=B;J=W.windowOpacityOverride?S.W:S.A;B=W.windowOpacity;B==null&&(B=Vp.windowOpacity);J.windowOpacity=
B;J=W.charEdgeStyleOverride?S.W:S.A;B=W.charEdgeStyle;B==null&&(B=a.charEdgeStyle);J.v1.charEdgeStyle=B;J=W.fontFamilyOverride?S.W:S.A;B=W.fontFamily;B==null&&(B=a.fontFamily);J.v1.fontFamily=B;S.loaded&&S.R2();m&&g.zN("yt-player-caption-display-settings",W,2592E3)},sp=function(S,W,m){W&&!S.iY?(W=Bb9({KW:0,
lang:"en"}),S.iY=[W,new JH(W.start,W.end-W.start,0,W.id,m??"Captions look like this")],S.player.iQ(S.iY)):!W&&S.iY&&(RNg(S,S.iY),S.iY=null)},eNn=function(S){if(!S.X.isInline())return g.yM("yt-player-sticky-caption")},uE=function(S){let W=void 0;
const m=g.pz().uY(65);if(g.SB(S.Y)&&m!=null){if(eNn(S)!=null)return!1;W=!m}return W},xaN=function(S){if(S.Y.Y8===1||S.videoData.Qx===1||g.vT(S.videoData,"yt:cc")==="alwayson")return!0;
let W;S.videoData.captionTracks.length&&(W=S.getAudioTrack().N);if(S.Y.Y8===2){if(g.SB(S.Y))var m=eNn(S);else if(S.storage)try{m=S.storage.get("module-enabled")}catch(J){S.storage.remove("module-enabled")}else m=null;if(m!=null)return!!m}m=ob(S.player.getAudioTrack(),g.SB(S.Y));const a=g.vT(S.videoData,"yt:cc");if(uE(S)===void 0){if(m==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return a?a==="on":!0;if(m==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return a==="on"}else return a==="on";return W==="ON"||
g.vT(S.videoData,"yt:cc")==="on"},g9=function(S,W=!1){if(S.C&&!W||!S.videoData.captionTracks.length)return!1;
S=S.getAudioTrack();return!!S.C||S.N==="FORCED_ON"},iaN=function(S,W){if(S.C){var m=S.X.QT().IL().textTracks,a=null;
S.B==="HLS"?a=S.C.getId():a=S.C.toString();for(let B=0;B<m.length;B++){var J=m[B];J.id===a&&(W?J.mode!=="showing"&&(J.mode="showing",J=S.C,S.Xf(J,!!J,Op(S)?"g":S.V?"m":"s")):J.mode==="showing"&&(J.mode="disabled"))}}},Op=function(S){const W=j1(S);
return!!W&&S.C===W},dan=function(S,W){if(S.B==="HLS")return!1;
g.xL(S.videoData)&&(W=!0);W||(W=S.B==="TTS"?!1:S.B==="INNERTUBE"?!1:!0);return W||S.Y.T("web_deprecate_always_includes_asr_setting")&&g.SB(S.Y)?!0:!!g.pz().uY(66)},j1=function(S){return S.S&&S.S.C},Qp=function(S,W){if(!S.N)return null;
if(S.S&&S.S.j)return S.S.j;W=dan(S,W);W=g.Cf(S.N.C,W);let m=null;if(jS9(S.Y)){var a=S.X.isInline()?void 0:g.yM("yt-player-caption-sticky-language");var J=[a,S.videoData.captionsLanguagePreference,S.Y.captionsLanguagePreference,g.vT(S.videoData,"yt:cc_default_lang")];let z=!1;for(let y=0;y<J.length;y++){const Y=J[y];if(Y){z=!0;for(var B=0;B<W.length;B++)if(g.s6(W[B])===Y)return W[B];for(B=0;B<W.length;B++)if(g.s6(W[B]).split("-")[0]===Y.split("-")[0])return W[B]}}if(z&&S.N&&(J=S.N.S,J.length))for(var E of J)if(E.languageCode===
a){m=E;break}}else for(E=[S.videoData.captionsLanguagePreference,S.Y.captionsLanguagePreference,g.vT(S.videoData,"yt:cc_default_lang")],a=0;a<E.length;a++)for(J=0;J<W.length;J++)if(g.s6(W[J])===E[a])return W[J];E=null;S.S&&S.S.B&&(E=S.S.B);E||(E=W.find(z=>z.isDefault)||null);
E||(E=W[0]||j1(S));E&&m&&g.s6(E).split("-")[0]!==m.languageCode.split("-")[0]&&(E=QSw(E,m));return E},lE=function(S,W,m){S.loaded&&S.unload();
m!=null&&(S.V=m,S.V&&(g.SB(S.Y)?Xf(S,!!W):v0(S,!!W)));W!==null||g9(S,!0)||S.Xf(W,!!W,S.V?"m":"s");S.C=W;g9(S)&&(S.C=j1(S));H0(S,S.C??void 0);S.load()},Xf=function(S,W){S.X.isInline()||g.zN("yt-player-sticky-caption",W,2592E3)},v0=function(S,W){if(S.storage)try{S.storage.set("module-enabled",W)}catch(m){}},H0=function(S,W){S.Y.T("html5_modify_caption_vss_logging")&&(S.videoData.Op=W)},Pz8=function(S,W){var m=S.bY[W.id];
m&&m.N!==W&&(m.dispose(),delete S.bY[W.id],m=null);m||(m=IN8(S,W))&&(S.bY[W.id]=m)},fNp=function(S,W){const m=W.windowId;
S.TN[m]||(S.TN[m]=[]);S.TN[m].push(W)},IN8=function(S,W){const m=kCw(S);
if(!m)return null;var a=S.C?g.s6(S.C):null;a&&g.fCP.test(a)&&(W.params.KW=1);var J=S.mU.getPlayerSize();a=J.height*S.U.height;J=J.width*S.U.width;S.Y.playerStyle!=="google-live"||S.A.isDefault||Object.assign(W.params,S.A);switch(W.params.O4!=null?W.params.O4:W.C.length>1?1:0){case 1:return new $aN(W,S.A,S.W,m.width,m.height,J,a,S.Y.experiments,S.g2.bind(S),S.X);case 2:return new hNn(W,S.A,S.W,m.width,m.height,J,a,S.Y.experiments,S.g2.bind(S),S.X);default:return new Me(W,S.A,S.W,m.width,m.height,J,
a,S.Y.experiments,S.g2.bind(S),S.X)}},kCw=function(S){let W=S.mU.getVideoContentRect(!0).height,m=S.mU.getVideoContentRect(!0).width;
if(!W||!m)return null;W*=S.U.height;m*=S.U.width;return{width:m,height:W}},RNg=function(S,W){S.player.FK(W);
for(const m of W)g.v9(S.AX,m);b$(S.GN)},tAZ=function(S,W){if(!S.N)return{};
if(W){g.Sm(W)||S.hV(W.vss_id,"m");if(S.j&&S.B!=="HLS"||!g.bc(W))return;if(g.Sm(W)){lE(S,null,!0);return}let a;var m=g.Cf(S.N.C,!0);for(let J=0;J<m.length;J++){const B=m[J];B.languageCode!==W.languageCode||a&&(B.languageName!==W.languageName||(B.captionId||"")!==(W.captionId||"")||g.V9(B)!==W.displayName)||(a=W.translationLanguage?QSw(B,W.translationLanguage):B)}S.KM(W.position);!a||a===S.C&&S.loaded||(W=g.kY(),m=g.s6(a),W.length&&m===W[W.length-1]||(W.push(m),g.zN("yt-player-caption-language-preferences",
W)),jS9(S.Y)&&!S.X.isInline()&&g.zN("yt-player-caption-sticky-language",m,2592E3),lE(S,a,!0))}else return S.loaded&&S.C&&!Op(S)?g.nN(S.C):{};return""};
g.x7.prototype.LH=g.lc(69,function(S,W,m){this.N.set(S,{HZ:W,wC:m})});
g.i8.prototype.LH=g.lc(68,function(S,W,m){this.iY.LH(S,W,m)});
g.Ob.prototype.U=g.lc(67,function(){return!1});
g.Ob.prototype.j=g.lc(66,function(){});
g.jH.prototype.j=g.lc(65,function(S,W,m){this.n_();W=this.W(S,W);const a=this.L_.K().T("html5_report_captions_ctmp_qoe"),J=(0,g.t)();this.B();O$x(this,W,{format:"RAW",onSuccess:B=>{this.N=null;if(a){const E=(B.responseText.length/1024).toFixed(),z=(0,g.t)();this.videoData.N2("capresp",{ms:z-J,kb:E})}m.BL(B.responseText,S)},
onError:a?B=>{this.videoData.N2("capfail",{status:B?.status??0})}:void 0,
withCredentials:!0})});
g.Qh.prototype.j=g.lc(64,function(S,W,m){this.n_();W=this.W(S,W);this.B();this.N=g.Zf(W,{format:"RAW",onSuccess:a=>{this.N=null;m.BL(a.responseText,S)},
withCredentials:!0})});
g.MQ.prototype.q2=g.lc(63,function(){const S=g.BI(document,"track",void 0,this.C);for(let W=0;W<S.length;W++)g.ju(S[W])});
g.lY.prototype.q2=g.lc(62,function(){const S=g.BI(document,"track",void 0,this.C);for(let W=0;W<S.length;W++)g.ju(S[W])});
g.eg.prototype.q2=g.lc(61,function(){this.mediaElement.q2()});
g.MQ.prototype.Hn=g.lc(60,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.lY.prototype.Hn=g.lc(59,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.eg.prototype.Hn=g.lc(58,function(){return this.mediaElement.Hn()});
g.MQ.prototype.cn=g.lc(57,function(){return!!this.C.textTracks});
g.lY.prototype.cn=g.lc(56,function(){return!!this.C.textTracks});
g.eg.prototype.cn=g.lc(55,function(){return this.mediaElement.cn()});
g.MQ.prototype.AX=g.lc(54,function(S){for(let W=0;W<S.length;W++)this.C.appendChild(S[W])});
g.lY.prototype.AX=g.lc(53,function(S){for(let W=0;W<S.length;W++)this.C.appendChild(S[W])});
g.eg.prototype.AX=g.lc(52,function(S){this.mediaElement.AX(S)});
g.c5.prototype.CE=g.lc(40,function(S){return g.ia(this.app,{playerType:void 0}).CE(S)});
g.aW.prototype.CE=g.lc(39,function(S){return this.C_.iK.CE(S)});
g.TY.prototype.CE=g.lc(38,function(S){return this.Zr().some(W=>W.namespace===S)});
g.LF.prototype.CE=g.lc(37,function(){return!1});
g.c5.prototype.hV=g.lc(35,function(S,W){this.app.U9().hV(S,W)});
g.aW.prototype.hV=g.lc(34,function(S,W){this.C_.hV(S,W)});
g.Y7.prototype.hV=g.lc(33,function(S,W){S=[S,W];g.uG(this,g.ji(this.provider),"cfi",S)});
g.KF.prototype.hV=g.lc(32,function(S,W){this.qoe&&this.qoe.hV(S,W)});
g.Yb.prototype.hV=g.lc(31,function(S,W){this.DH.hV(S,W)});
g.LF.prototype.hV=g.lc(30,function(){});
g.c5.prototype.Xf=g.lc(29,function(S,W,m){this.app.U9().Xf(S,W,m)});
g.aW.prototype.Xf=g.lc(28,function(S,W,m){this.C_.Xf(S,W,m)});
g.Y7.prototype.Xf=g.lc(27,function(S,W,m){if(this.GN!==S||this.x6!==W)W=W==="rawcc"?"":W,m=[S,W,this.GN,m],g.uG(this,g.ji(this.provider),"cfs",m),this.GN=S,this.x6=W});
g.KF.prototype.Xf=g.lc(26,function(S,W,m){this.qoe&&this.qoe.Xf(S,W,m)});
g.Yb.prototype.Xf=g.lc(25,function(S,W,m){this.DH.Xf(S,W,m)});
g.LF.prototype.Xf=g.lc(24,function(){});
g.fC.prototype.ZB=g.lc(3,function(S){return(S=this.B(S))?S.C:0});
g.$9.prototype.ZB=g.lc(2,function(){return 0});
var lPZ=/#(.)(.)(.)/,H$9=/^#(?:[0-9a-f]{3}){1,2}$/i,i$8={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},Ax$={en:"English"},ZaN=class extends g.Ob{constructor(S){super(S);this.N=new Set}A(S){var W=this.L_.QT();if(W&&W.IL()){W=W.IL().textTracks;for(const m of W)m.kind==="subtitles"&&!this.N.has(m.language)&&m.language&&(g.Vm(this.C,new g.Q9({languageCode:m.language,languageName:m.language,kind:m.kind,id:m.id,displayName:Ax$[m.label]||m.label,vss_id:`.${m.language}`})),this.N.add(m.language))}g.Cf(this.C).length>
0&&S.jS()}},Nbg=class{constructor(){this.segments=[]}contains(S){S=g.iw(this.segments,S);return S>=0||S<0&&(-S-1)%2===1}length(){return this.segments.length/2}},ba8=class extends g.JW{constructor(S,W,m,a,J,B){super();this.policy=S;this.player=W;this.yD=m;this.Z=a;this.A=J;this.U=B;this.j=new Nbg;this.W=-1;this.N=this.B=this.C=null;this.bY=0;this.V=new g.rr(this.iY,1E3,this);this.events=new g.JC(this);g.R(this,this.V);g.R(this,this.events);this.events.L(W,"SEEK_COMPLETE",this.S);this.S();this.iY()}j9(){super.j9();
this.N&&this.N.cancel()}S(){this.seekTo(this.player.getCurrentTime())}seekTo(S){S-=this.player.f3();const W=this.C;this.C=g.Kn(this.yD.W(S).e9);W!==this.C&&this.U&&this.U()}reset(){this.j=new Nbg;this.W=-1;this.N&&(this.N.cancel(),this.N=null)}iY(){this.n_();var S;if(S=this.C!=null)S=this.C,S=S.yD.j(S);if(S&&!this.N&&!(this.C&&this.C.startTime-this.player.getCurrentTime()>30)){S=this.C;S=S.yD.GN(S);const J=S.e9[0];if(this.player.getVideoData()?.enableServerStitchedDai){var W=this.player.rD();if(W){var m=
J.yD.info.id;const B=J.O9;var a=S.e9[0].j;if(this.policy.GN){if(W=g.si7(W,a,B,m,3))S.j=W}else if(m=W.yJ(a,B,m,3))if(a=2,W.Ea.has(B)?a=0:g.Et(W,B)&&(a=1),W=a,W===0)m&&(S.C=new g.bB(m));else if(W===2){this.V.start();LXN(this)&&this.seekTo(this.player.getCurrentTime());return}}}J.yD.index.YM(J.O9)?(this.j.contains(S.e9[0].O9)||R_v(this,S),this.C=g.Kn(S.e9)):LXN(this)&&this.seekTo(this.player.getCurrentTime())}this.V.start()}},okp=class extends g.Ob{constructor(S,W){super(W);this.N=S;this.X=W;this.Z=
null;this.iY=!1;this.logger=new g.gz("caps");this.bY=g.ny(this.X,this.N)}j(S,W,m){this.B();W=e_Q(this,S.getId());W||(W=S.languageCode,W=this.N.isManifestless?xKZ(this,W,"386"):xKZ(this,W));if(W){var a=(W.index.ZB(W.index.FV())-W.index.getStartTime(W.index.FV()))*1E3,J=new g.cmj(this.X.K());this.Z=new ba8(J,this.X,W,(B,E)=>{m.BL(B,S,E,a)},this.bY||g.QO(W.info),()=>{this.Z&&this.Z.reset();
this.iY=!0})}}U(){const S=this.iY;
this.iY=!1;return S}A(S){var W=this.X.K().T("html5_fallback_if_rawcc_missing");const m=this.N.C.rawcc!=null;if(!this.bY||!m&&W)W=this.N.isManifestless?dKg(this,"386"):dKg(this);else{if(!m){g.OK(this.logger,386248249,"rawcc used but unavailable");return}W=[new g.Q9({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Q9({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const a of W)g.Vm(this.C,
a);S.jS()}B(){this.Z&&(this.Z.dispose(),this.Z=null)}W(){return""}},Gk=/^#(?:[0-9a-f]{3}){1,2}$/i;var rxp=["left","right","center","justify"];var Me=class extends g.c{constructor(S,W,m,a,J,B,E,z,y,Y){const G=Y.isInline()&&!0,K={};Object.assign(K,W);Object.assign(K,S.params);Object.assign(K,m);const T={};Object.assign(T,W.v1);S.params.v1&&Object.assign(T,S.params.v1);Object.assign(T,m.v1);G&&(K.windowOpacity=.6,T.backgroundOpacity=0);K.v1=T;const q=K.KW===1,V=[{G:"span",O:"captions-text",J:{style:"word-wrap: normal; display: block;"}}];(z=z.Y6("caption_edit_on_hover")&&Y.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand)&&
V.unshift({G:"button",O:"caption-edit",J:{tabindex:"0","aria-label":MmZ()},D:[{G:"svg",J:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},D:[{G:"path",J:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({G:"div",O:"caption-window",J:{id:`${"caption-window"}-${S.id}`,dir:q?"rtl":"ltr",tabindex:"0",lang:K.lang},D:V});this.W=
[];this.AX=!1;this.N=S;this.cn=this.GN=null;this.zC=B;this.Ec=E;this.V=null;this.maxWidth=B*.96;this.maxHeight=E*.96;this.C=K;this.Qc=m;this.bY=W;this.j=this.I2("captions-text");this.TV=this.j.style.getPropertyValue("box-decoration-break")!==""||this.j.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.ZQ=IPp(a,J,B,E);this.Sg=y;z&&(this.A=this.I2("caption-edit"),this.L(this.A,"click",()=>{this.Sg()}));
this.type=0;this.g2=this.ZQ*PHH(T);this.R2=G;S=new g.Dk(this.element,!0);g.R(this,S);S.subscribe("dragstart",this.a6,this);S.subscribe("dragmove",this.I6,this);S.subscribe("dragend",this.BU,this);this.d2=this.hX=this.p_=this.mU=0;S="";this.C.windowOpacity&&(S=ro(this.C.windowColor),S="rgba("+S[0]+","+S[1]+","+S[2]+","+this.C.windowOpacity+")");W={"background-color":S,display:this.C.isVisible===!1?"none":"","text-align":rxp[this.C.textAlign]};this.TV&&(W["border-radius"]=S?`${this.g2/8}px`:"");(this.B=
this.N.params.KW===2||this.N.params.KW===3)&&fPv(this,this.element);g.Zt(this.element,W);G&&this.element.parentElement?.style.setProperty("--caption-window-color",S);switch(this.C.lV){case 0:case 1:case 2:g.my(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.my(this.element,"ytp-caption-window-bottom")}}a6(S,W){this.hX=S;this.d2=W;const m=g.EM(this.element,this.element.parentElement);this.mU=S-m.x;this.p_=W-m.y}I6(S,W){if(S!==this.hX||W!==this.d2){g.WL(this.element,"ytp-dragging")||
g.my(this.element,"ytp-dragging");var m=g.yE(this.element);S=S-this.mU-.02*this.zC;var a=W-this.p_-.02*this.Ec,J=(S+m.width/2)/this.maxWidth*3;J=Math.floor(g.P$(J,0,2));var B=(a+m.height/2)/this.maxHeight*3;B=Math.floor(g.P$(B,0,2));W=J+B*3;S=(S+J/2*m.width)/this.maxWidth;S=g.P$(S,0,1)*100;m=(a+B/2*m.height)/this.maxHeight;m=g.P$(m,0,1)*100;this.N.params.lV=W;this.N.params.PT=m;this.N.params.Io=S;this.N.params.isDefault=!1;this.C.lV=W;this.C.PT=m;this.C.Io=S;this.C.isDefault=!1;this.bY.lV=W;this.bY.PT=
m;this.bY.Io=S;this.bY.isDefault=!1;this.tv()}}BU(){g.J$(this.element,"ytp-dragging")}tv(){this.Z(this.W)}Z(S){var W=this.R2?0:Math.min(this.C3(),this.maxWidth),m=this.x6(),a=this.R2;if(a){var J=getComputedStyle(this.j.parentNode);J=cx(J.borderLeftWidth)+cx(J.borderRightWidth)+cx(J.paddingLeft)+cx(J.paddingRight)}else J=0;const B=J;J="";this.N.params.KW===3&&(J="rotate(180deg)");var E=a?`calc(${"96%"} - ${B}px)`:"96%";g.Zt(this.element,{top:0,left:0,right:"",bottom:"",width:W?`${W}px`:"",height:m?
`${m}px`:"","max-width":E,"max-height":E,margin:"",transform:""});this.TN(S);J={transform:J,top:"",left:"",width:W?`${W}px`:"",height:m?`${m}px`:"","max-width":"","max-height":""};var z=this.C.Io*.96+2;E=this.C.lV;switch(E){case 0:case 3:case 6:(a=this.C.v1.fontSizeIncrement)&&a>0&&this.C.KW!==2&&this.C.KW!==3&&(z=Math.max(z/(1+a*2),2));J.left=`${z}%`;break;case 1:case 4:case 7:J.left=`${z}%`;z=this.j.offsetWidth;W||z?(W=W||z+1,J.width=`${W}px`,J["margin-left"]=a?`${W/-2-B/2}px`:`${W/-2}px`):J.transform+=
" translateX(-50%)";break;case 2:case 5:case 8:J.right=`${100-z}%`}a=this.C.PT*.96+2;switch(E){case 0:case 1:case 2:J.top=`${a}%`;break;case 3:case 4:case 5:J.top=`${a}%`;(m=m||this.element.clientHeight)?(J.height=`${m}px`,J["margin-top"]=`${m/-2}px`):J.transform+=" translateY(-50%)";break;case 6:case 7:case 8:J.bottom=`${100-a}%`}g.Zt(this.element,J);if(this.A){m=this.j.offsetHeight;a=1;for(W=0;W<S.length;W++)J=S[W],typeof J.text==="string"&&(a+=J.text.split("\n").length-1,J.append||W===0||a++);
m/=a;this.A.style.height=`${m}px`;this.A.style.width=`${m}px`;this.element.style.paddingLeft=`${m+5}px`;this.element.style.paddingRight=`${m+5}px`;S=Number(this.element.style.marginLeft.replace("px",""))-m-5;m=Number(this.element.style.marginRight.replace("px",""))-m-5;this.element.style.marginLeft=`${S}px`;this.element.style.marginRight=`${m}px`}}TN(S){let W;for(W=0;W<S.length&&S[W]===this.W[W];W++);if(this.AX||this.W.length>W)W=0,this.AX=!1,this.W=[],this.V=this.cn=this.GN=null,g.gY(this.j);for(;W<
S.length;W++)tmv(this,S[W])}C3(){return 0}x6(){return 0}toString(){return super.toString()}};var cxv=class{constructor(){this.B=this.time=this.mode=this.N=0;this.j=new Cz9(this);this.A=new Cz9(this);this.C=[];this.clear()}clear(){this.B=this.time=this.mode=0;this.C=[];this.reset()}reset(){this.mode=0;this.j.reset(0);this.A.reset(1)}},Akv=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],DaN=class{constructor(){this.type=0}set(S){this.type=S}get(){return this.type}},w$g=class{constructor(){this.state=this.kW=this.vZ=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}FD(){return this.state!==0}matches(S,W){return this.FD()&&S===this.vZ&&W===this.kW}},SNw=class{constructor(){this.timestamp=this.C=0}reset(){this.timestamp=
this.C=0}},Up=class{constructor(S){this.A=S;this.B=[];this.C=this.N=this.row=0;this.style=new DaN;this.j=0;for(S=0;S<=15;S++){this.B[S]=[];for(let W=0;W<=32;W++)this.B[S][W]=new SNw}}updateTime(S){for(let W=1;W<=15;++W)for(let m=1;m<=32;++m)this.B[W][m].timestamp=S}debugString(){let S="\n";for(let W=1;W<=15;++W){for(let m=1;m<=32;++m){const a=this.B[W][m];S=a.C===0?S+"_":S+String.fromCharCode(a.C)}S+="\n"}return S}reset(S){for(let W=0;W<=15;W++)for(let m=0;m<=32;m++)this.B[W][m].reset();this.j=S;
this.C=0;this.N=this.row=1}},rkH=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],CH9=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ckH=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],DKH=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],WGN=class{constructor(S){this.B=S;this.A=0;this.style=new DaN;this.W=new Up(this.B);this.V=new Up(this.B);this.text=new Up(this.B);this.N=this.W;this.j=this.V;this.C=this.N}reset(S,W){this.A=W;this.style.set(2);this.N=this.W;this.j=this.V;this.C=this.N;const m=(S<<2)+(W<<1);this.W.reset(m);this.V.reset(m);
this.text.reset((S<<2)+(W<<1)+1)}},Cz9=class{constructor(S){this.C=S;this.A=0;this.B=new WGN(this.C);this.W=new WGN(this.C);this.N=new w$g;this.j=this.B}reset(S){this.A=S;this.N.clear();this.j=this.B;this.B.reset(S,0);this.W.reset(S,1)}};var m1$=class{j(){}};var JH=class extends g.jX{constructor(S,W,m,a,J,B=!1,E=null){super(S,S+W,{priority:m,namespace:"captions"});this.windowId=a;this.text=J;this.append=B;this.C=E}toString(){return super.toString()}};var LQ=class extends g.JW{reset(){}};var Ep=class extends g.jX{constructor(S,W,m,a,J){super(S,S+W,{priority:m,namespace:"captions"});this.id=a;this.params=J;this.C=[]}toString(){return super.toString()}},B0=0;var atn=class extends LQ{constructor(S){super();this.j=S;this.pens={};this.Z={};this.S={};this.A="_"+B0++;this.V={};this.N=this.C=null;this.W=!0}reset(){this.V={};this.N=this.C=null;this.W=!0}B(S,W){S=S.firstChild;S.getAttribute("format");W=W||0;Number.isFinite(W);S=Array.from(S.childNodes);for(var m of S)if(m.nodeType===1)switch(m.tagName){case "head":var a=m;break;case "body":var J=m}if(a){a=Array.from(a.childNodes);for(var B of a)if(B.nodeType===1)switch(B.tagName){case "pen":m=B.getAttribute("id");
a=this.pens;S={};var E=B.getAttribute("p");E&&Object.assign(S,this.pens[E]);E=yp(B,"b");E!=null&&(S.bold=E);E=yp(B,"i");E!=null&&(S.italic=E);E=yp(B,"u");E!=null&&(S.underline=E);E=Yw(B,"et");E!=null&&(S.charEdgeStyle=E);E=Yw(B,"of");E!=null&&(S.offset=E);E=KQ(B,"bc");E!=null&&(S.background=E);E=KQ(B,"ec");E!=null&&(S.PB=E);E=KQ(B,"fc");E!=null&&(S.color=E);E=Yw(B,"fs");E!=null&&E!==0&&(S.fontFamily=E);E=zk(B,"sz");E!==void 0&&(S.fontSizeIncrement=E/100-1);E=zk(B,"bo");E!==void 0&&(S.backgroundOpacity=
E/255);E=zk(B,"fo");E!==void 0&&(S.textOpacity=E/255);E=Yw(B,"rb");E!=null&&E!==10&&E!==0&&(S.wr=E>10?E-1:E);E=Yw(B,"hg");E!=null&&(S.kJ=E);a[m]=S;break;case "ws":a=B.getAttribute("id");this.S[a]=Ekn(this,B);break;case "wp":a=B.getAttribute("id"),this.Z[a]=zNg(this,B)}}if(J){B=[];J=Array.from(J.childNodes);for(X of J)if(X.nodeType===1)switch(X.tagName){case "w":this.C=yx9(this,X,W,!1);(J=this.V[this.C.id])&&J.end>this.C.start&&(J.end=this.C.start);this.V[this.C.id]=this.C;B.push(this.C);break;case "p":var z=
X;S=W;J=[];a=z.getAttribute("w")||this.A;m=!!yp(z,"a");S=(zk(z,"t")||0)+S;E=zk(z,"d")||5E3;m||(!this.W&&this.N&&this.N.windowId===a&&this.N.end>S&&(this.N.end=S),this.N&&this.N.text==="\n"&&(this.N.text=""));const M=m?6:5;var y=z.getAttribute("p");y=y?this.pens[y]:null;const x=Array.from(z.childNodes);x.length&&(this.W=z.getAttribute("d")!=null);for(z=0;z<x.length;z++){var Y=x[z],G=void 0;z>0&&(m=!0);let L;Y.nodeType===1&&(L=Y);if(L&&L.tagName==="s"){if((Y=(Y=L.getAttribute("p"))?this.pens[Y]:null)&&
Y.wr&&(Y.wr===1?(Y=x.slice(z,z+4),Y.length===4&&(G=Jxg(S,E,a,m,M,Y,this.pens),z+=3)):G=Jxg(S,E,a,m,M,[L],this.pens)),!G){var K=L;G=S;Y=E;var T=a,q=m;const d=K.textContent?K.textContent:"";var V=K.getAttribute("p");V=V?this.pens[V]:null;K=zk(K,"t")||0;G=new JH(G+K,Y-K,M,T,d,q,V)}}else G=new JH(S,E,M,a,Y.textContent||"",m,y);J.push(G);this.N=G}if(J.length>0){J[0].windowId===this.A&&(this.C=yx9(this,X,W,!0),B.push(this.C));for(const L of J)L.windowId=this.C.id,this.C.C.push(L),B.push(L)}}var X=B}else X=
[];return X}};var J8H=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),BYx=class extends LQ{constructor(S){super();this.W=S;this.C=new Map;this.j=new Map;this.A=new Map;this.N=new Map}reset(){this.N.clear()}B(S,W){S=JSON.parse(S);if(!S)return[];if(S.pens){var m=S.pens,a=0;for(var J of m){m={};var B=J.pParentId;B&&Object.assign(m,this.C.get(B));J.bAttr&&(m.bold=!0);J.iAttr&&(m.italic=!0);J.uAttr&&(m.underline=!0);B=J.ofOffset;B!=null&&(m.offset=B);J.szPenSize!==void 0&&(m.fontSizeIncrement=J.szPenSize/100-1);
B=J.etEdgeType;B!=null&&(m.charEdgeStyle=B);J.ecEdgeColor!==void 0&&(m.PB=Tk(J.ecEdgeColor));B=J.fsFontStyle;B!=null&&B!==0&&(m.fontFamily=B);J.fcForeColor!==void 0&&(m.color=Tk(J.fcForeColor));J.foForeAlpha!==void 0&&(m.textOpacity=J.foForeAlpha/255);J.bcBackColor!==void 0&&(m.background=Tk(J.bcBackColor));J.boBackAlpha!==void 0&&(m.backgroundOpacity=J.boBackAlpha/255);(B=J.rbRuby)&&B!==10&&(m.wr=B>10?B-1:B,m.textEmphasis=J8H.get(m.wr));J.hgHorizGroup&&(m.kJ=J.hgHorizGroup);this.C.set(a++,m)}}if(S.wsWinStyles){a=
S.wsWinStyles;J=0;for(var E of a)a={},(m=E.wsParentId)?Object.assign(a,this.A.get(m)):Object.assign(a,this.W),E.mhModeHint!==void 0&&(a.O4=E.mhModeHint),E.juJustifCode!==void 0&&(a.textAlign=E.juJustifCode),E.pdPrintDir!==void 0&&(a.KW=E.pdPrintDir),E.sdScrollDir!==void 0&&(a.gV=E.sdScrollDir),E.wfcWinFillColor!==void 0&&(a.windowColor=Tk(E.wfcWinFillColor)),E.wfoWinFillAlpha!==void 0&&(a.windowOpacity=E.wfoWinFillAlpha/255),this.A.set(J++,a)}if(S.wpWinPositions){J=S.wpWinPositions;E=0;for(var z of J)J=
{},(a=z.wpParentId)&&Object.assign(J,this.j.get(a)),z.ahHorPos!==void 0&&(J.Io=z.ahHorPos),z.apPoint!==void 0&&(J.lV=z.apPoint),z.avVerPos!==void 0&&(J.PT=z.avVerPos),z.ccCols!==void 0&&(J.Q6=z.ccCols),z.rcRows!==void 0&&(J.vc=z.rcRows),this.j.set(E++,J)}if(S.events){S=S.events;z=[];for(const h of S)if(E=(h.tStartMs||0)+W,J=h.dDurationMs||0,h.id)a=String(h.id),S=YRQ(this,h,E,J,a),z.push(S),this.N.set(a,S);else{h.wWinId?a=h.wWinId.toString():(a="_"+B0++,S=YRQ(this,h,E,J,a),z.push(S),this.N.set(a,S));
S=z;var y=h;J===0&&(J=5E3);m=this.N.get(a);const JG=(B=!!y.aAppend)?6:5,yP=y.segs;let kX=null;y.pPenId&&(kX=this.C.get(y.pPenId));for(y=0;y<yP.length;y++){var Y=yP[y],G=Y.utf8;if(G){var K=Y.tOffsetMs||0;let g7=null;Y.pPenId&&(g7=this.C.get(Y.pPenId));if((m.params.O4!=null?m.params.O4:m.C.length>1?1:0)===2&&B&&G==="\n")continue;Y=null;var T=[],q;if(q=g7&&g7.wr===1){q=yP;var V=y;if(V+3>=q.length||!q[V+1].pPenId||!q[V+2].pPenId||!q[V+3].pPenId)q=!1;else{var X=q[V+1].pPenId;(X=this.C.get(X))&&X.wr&&X.wr===
2?(X=q[V+2].pPenId,X=this.C.get(X),!X||!X.wr||X.wr<3?q=!1:(X=q[V+3].pPenId,q=(X=this.C.get(X))&&X.wr&&X.wr===2?!0:!1)):q=!1}}if(q)K=yP[y+1].utf8,Y=yP[y+3].utf8,q=yP[y+2].utf8,V=this.C.get(yP[y+2].pPenId),G=aN9(G,K,q,Y,V),Y=new JH(E,J,JG,a,G,B,g7),y+=3;else{if(G.indexOf("<")>-1){T=g7;q=kX;V=E;X=J;var M=K,x=JG,L=B;const $X=[];var d=g.aT(`<html>${G}</html>`);if(!d.getElementsByTagName("parsererror").length&&d.firstChild?.childNodes.length)for(const C6 of d.firstChild.childNodes){d=C6.textContent?.replace(/\n/g,
"")??"";if(C6.nodeType===3&&(!d||d.match(/^ *$/)!=null))continue;const XZ={};Object.assign(XZ,T||q);switch(C6?.tagName){case "b":XZ.bold=!0;break;case "i":XZ.italic=!0;break;case "u":XZ.underline=!0}$X.push(new JH(V+M,X-M,x,m.id,d,L,XZ))}T=$X}T.length||(T=[new JH(E+K,J-K,JG,m.id,G,B,g7||kX)])}if(T.length)for(const $X of T)S.push($X),m.C.push($X);else Y&&(S.push(Y),m.C.push(Y))}B=!0}}W=z}else W=[];return W}};var Egg=class extends g.Ob{constructor(S,W,m){super(S);this.videoData=W;this.audioTrack=m;this.S=W.Ah}j(S,W,m){vlN(this.videoData.videoId,S.vssId,m.BL)}A(S){if(this.audioTrack)for(const W of this.audioTrack.captionTracks)g.Vm(this.C,W);S.jS()}};var $aN=class extends Me{constructor(S,W,m,a,J,B,E,z,y,Y){super(S,W,m,a,J,B,E,z,y,Y);this.type=1}TN(S){const W=this.N.C;super.TN(S);let m,a;for(S=S.length;S<W.length;S++){const J=W[S];let B;a&&J.C===m?B=a:(B={},Object.assign(B,J.C),Object.assign(B,z2v),m=J.C,a=B);tmv(this,J,B)}}},z2v={RK:!0};var GCp=class extends m1${constructor(S,W){super();this.trackData=S;this.W=W;this.version=this.A=this.B=this.byteOffset=0;this.N=[];this.C=new DataView(this.trackData)}j(S,W,m,a,J){if(m<a){const B="_"+B0++;m=m/1E3-this.W;a=a/1E3-this.W;S=new Ep(m,a-m,5,B,{textAlign:0,lV:0,Io:W*2.5,PT:S*5.33});J=new JH(m,a-m,5,B,J);this.N.push(S);this.N.push(J)}}},y8Q=class extends LQ{constructor(S,W){super();this.N=S;this.j=W;this.track=this.j.languageName==="CC3"?4:0;this.C=new cxv;this.C.N=1<<this.track}B(S){S=
new GCp(S,this.N);if(KW$(S)){for(;S.byteOffset<S.C.byteLength;)for(S.version===0?S.B=pQ(S)*(1E3/45):S.version===1&&(S.B=pQ(S)*4294967296+pQ(S)),S.A=qe(S);S.A>0;S.A--){var W=qe(S);const m=qe(S),a=qe(S);W&4&&(W&3)===this.track&&(this.track===0||this.track===1)&&(W=this.C,W.C.push({time:S.B,type:this.track,In:m,yv:a,order:W.C.length}))}olQ(this.C,S);return S.N}return[]}reset(){this.C.clear()}};var hNn=class extends Me{constructor(S,W,m,a,J,B,E,z,y,Y){super(S,W,m,a,J,B,E,z,y,Y);this.type=2;this.vn=[];this.U=this.S=this.Hn=0;this.q2=NaN;this.yc=0;this.Fz=null;this.K3=new g.rr(this.K_,433,this);this.A&&(Y.createClientVe(this.A,this,167342),this.L(this.A,"click",()=>{Y.logClick(this.A)}),S=new g.Dk(this.element,!0),g.R(this,S),S.subscribe("hoverstart",()=>{Y.logVisibility(this.A,!0)},this));
g.my(this.element,"ytp-caption-window-rollup");g.R(this,this.K3);g.Zt(this.element,"overflow","hidden")}tv(){g.CK(this.K3)}K_(){this.element.removeEventListener("transitionend",this.K_,!1);g.J$(this.element,"ytp-rollup-mode");this.Z(this.Fz,!0)}x6(){return this.B?this.U:this.S}C3(){return this.B?this.S:this.U}Z(S,W){this.Fz=S;if(this.N.params.vc){var m=0;for(let a=0;a<this.W.length&&m<S.length;a++)this.W[a]===S[m]&&m++;m>0&&m<S.length&&(S=this.W.concat(S.slice(m)));this.yc=this.U;this.S=this.U=0;
super.Z(S);FW9(this,W)}super.Z(S)}};var YN9=class{constructor(S,W,m,a){this.X=S;this.B=W;this.logger=m;this.Wv=a;this.Aw=[];this.aT=[];this.C=null;this.eg={qyD:()=>this.C,
rU:()=>this.Aw};
S=g.kW(this.X.K().experiments,"html5_override_micro_discontinuities_threshold_ms");this.N=S>0?S:10}unload(){this.C!=null&&(this.X.removeEventListener("sabrCaptionsDataLoaded",this.C),this.C=null);this.Aw=[];this.X.publish("sabrCaptionsBufferedRangesUpdated",this.Aw)}Ti(S){return{formatId:g.vo(S.info.yD.info,this.Wv),O9:S.info.O9+(this.Wv?0:1),startTimeMs:S.info.j*1E3,durationMs:S.info.Z*1E3}}};var Gd9=class extends g.Ob{constructor(S,W){super(W);this.N=S;this.X=W;this.logger=new g.gz("caps");this.Z=this.iY=null;this.bY=new YN9(this.X,this,this.logger,this.N.Wv)}j(S,W,m){this.B();W=S.getId();W=W!=null&&W in this.N.C?this.N.C[W]:null;W||(W=S.languageCode,W=this.N.isManifestless?uWN(this,W,"386"):uWN(this,W));W&&(this.Z=S,this.iY=W,nkN(this.bY,m),this.X.publish("sabrCaptionsTrackChanged",g.vo(W.info,this.N.Wv)))}A(S){var W=this.N.isManifestless?gkv(this,"386"):gkv(this);for(const m of W)g.Vm(this.C,
m);S.jS()}B(){this.Z&&(this.Z=this.iY=null,this.bY.unload(),this.X.publish("sabrCaptionsTrackChanged",null))}W(){return""}};var Oan="WEBVTT".split("").map(S=>S.charCodeAt(0)),lNw=class extends LQ{constructor(){super()}B(S,W){S instanceof ArrayBuffer&&(S=g.lg(new Uint8Array(S)));
const m=[];S=S.split(KGn);for(let V=1;V<S.length;V++){var a=S[V],J=W;if(a!==""&&!TYN.test(a)){var B=RN.exec(a);if(B&&B.length>=4){var E=Ff(B[1]),z=Ff(B[2])-E;E+=J;var y=(B=B[3])?B.split(" "):[];B={};var Y=null;var G="";var K=null,T="";for(const X of y)if(y=X.split(":"),y.length===2){var q=y[1];switch(y[0]){case "line":y=q.split(",");y[0].endsWith("%")&&(Y=y[0],B.PT=Number.parseInt(Y,10),y.length===2&&(G=y[1].trim()));break;case "position":y=q.split(",");K=y[0];B.Io=Number.parseInt(K,10);y.length===
2&&(T=y[1].trim());break;case "align":switch(q){case "start":B.textAlign=0;break;case "middle":B.textAlign=2;break;case "end":B.textAlign=1}}}Y||G||(G="end");if(!K)switch(B.textAlign){case 0:B.Io=0;break;case 1:B.Io=100;break;case 2:B.Io=50}if(B.textAlign!=null){Y=0;switch(G){case "center":Y+=3;break;case "end":Y+=6;break;default:Y+=0}switch(T){case "line-left":Y+=0;break;case "center":Y+=1;break;case "line-right":Y+=2;break;default:switch(B.textAlign){case 0:Y+=0;break;case 2:Y+=1;break;case 1:Y+=
2}}G=Y<0||Y>8?7:Y;B.lV=G}a=a.substring(RN.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");T=B;B=a;a={};if(B.indexOf("<")<0&&B.indexOf("&")<0)J=QhQ(E,z,5,T),z=new JH(E,z,5,J.id,B,!1,g.Sm(a)?void 0:a),m.push(J),m.push(z),J.C.push(z);else for(G=B.split(qN9),G.length===1?(B=5,T=QhQ(E,z,B,T)):(Y=B=6,T=Object.assign({Q6:32},T),T=new Ep(E,z,Y,"_"+B0++,T)),m.push(T),Y=E,K=0;K<G.length;K++)if(y=G[K],K%2===0){q=g.aT(`<html>${y}</html>`);let X;q.getElementsByTagName("parsererror").length?(X=q.createElement("span"),
X.appendChild(q.createTextNode(y))):X=q.firstChild;X$p(this,Y,z-(Y-E),B,T,K>0,X,a,m)}else Y=Ff(y)+J}RN.lastIndex=0}}return m}},TYN=/^NOTE/,KGn=/(?:\r\n|\r|\n){2,}/,RN=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),qN9=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var pIp=class extends g.JW{constructor(S,W){super();this.X=S;this.Y=W;this.C=null;this.Xz=this.X.rD();this.logger=new g.gz("caps")}clear(){this.C&&this.C.dispose();this.C=null}reset(){this.C&&this.C.reset()}j9(){super.j9();this.clear()}};var Vp={windowColor:"#080808",windowOpacity:0,textAlign:2,lV:7,Io:50,PT:100,isDefault:!0,v1:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.FL("captions",class extends g.gL{constructor(S){super(S);this.X=S;this.AX=[];this.bY={};this.TN={};this.V=!1;this.B="NONE";this.N=this.S=this.iY=this.Hn=this.hX=null;this.p_={jS:()=>{this.jS()},
BL:(a,J,B,E)=>{this.BL(a,J,B,E)}};
this.C=null;this.Y=this.X.K();this.videoData=this.X.getVideoData();this.mU=this.X.QD();this.A={v1:{}};this.W={v1:{}};this.videoData.tv()?this.B="OFFLINE":g.ypj(this.videoData,this.X)?this.B="HLS":sh9(this.videoData,this.X)?this.B="SABR_LIVE":g.Yx7(this.videoData,this.X)?this.B="LIVE":this.videoData.captionTracks.length?this.B="INNERTUBE":this.videoData.yc&&(this.B="TTS");this.ZQ=this.Y.controlsType==="3";this.K_=new pIp(this.X,this.Y);this.vn=new g.JC(this);this.Z=new g.c({G:"div",O:"ytp-caption-window-container",
J:{id:"ytp-caption-window-container"}});this.U={top:0,right:0,bottom:0,left:0,width:1,height:1};let W=null;const m=g.h$("yt-html5-player-modules::subtitlesModuleData");m&&(W=new g.Mi(m));this.storage=W;this.d2=!!S.QT()?.Hn();this.j=LWp(this);this.q2=!this.j&&this.ZQ&&this.d2&&(this.B==="LIVE"||this.B==="SABR_LIVE");g.R(this,this.K_);this.j?this.cn=this.GN=null:(this.GN=new g.NB(this.C3,void 0,this),g.R(this,this.GN),this.cn=new g.rr(this.TV,2E3,this),g.R(this,this.cn));g.R(this,this.vn);g.TJ(this.player,
this.Z.element,4);g.R(this,this.Z);this.j||this.vn.L(S,"resize",this.R2);(this.x6=g.Ic(this.Y)&&!g.rd()&&!this.X.isFullscreen()&&!this.j&&!this.q2)&&this.vn.L(S,"resize",this.yc);this.vn.L(S,"onPlaybackAudioChange",this.sV);this.vn.L(S,g.yC("captions"),a=>{this.onCueRangeEnter(a)});
this.vn.L(S,g.Yf("captions"),a=>{this.onCueRangeExit(a)});
nQ(this,Cl()||{});g.oV(this.player,"onCaptionsModuleAvailable");this.B==="HLS"&&this.j&&(S=this.X.QT().IL(),this.d2&&this.vn.L(S.textTracks,"addtrack",this.tv))}j9(){if(this.j||this.q2){const S=this.X.QT();S&&!S.n_()&&S.q2()}else sp(this,!1);super.j9()}qC(){return this.Y.T("html5_honor_caption_availabilities_in_audio_track")&&this.B!=="LIVE"&&this.B!=="SABR_LIVE"}E3(){if(this.ZQ)return this.j||this.q2;if(this.B==="HLS")return this.j;var S=this.getAudioTrack();if(this.qC()){if(!S.captionTracks.length)return!1;
if(!this.N)return!0}S=ob(S,g.SB(this.Y));return S==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:S==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?g9(this):uE(this)||g9(this)?!0:xaN(this)}load(){super.load();this.S=this.getAudioTrack();if(this.N)this.C&&(this.K_.clear(),this.j?iaN(this,!0):this.player.getPresentingPlayerType()!==3&&this.N.j(this.C,"json3",this.p_),this.B!=="HLS"&&this.j||this.q2||Op(this)||g.oV(this.player,"captionschanged",g.nN(this.C)));else{let S;this.B==="OFFLINE"?S=new Egg(this.player,this.videoData,
this.getAudioTrack()):this.B==="SABR_LIVE"?S=new Gd9(this.videoData.C,this.player):this.B==="HLS"?S=new ZaN(this.player):this.B==="LIVE"?S=new okp(this.videoData.C,this.player):this.B==="INNERTUBE"?S=new g.jH(this.player,this.videoData,this.getAudioTrack()):S=new g.Qh(this.player,this.videoData.yc,this.videoData.videoId,g.BEj(this.videoData),this.videoData.V2,this.videoData.eventId);this.N=S;g.R(this,this.N);this.N.A(this.p_)}}unload(){this.j&&this.C?iaN(this,!1):(this.cn&&this.cn.f1(),this.player.Zz("captions"),
this.AX=[],this.N&&this.N.B(),this.K_.clear(),this.iY&&this.player.iQ(this.iY),this.R2());super.unload();this.player.OC();g.oV(this.player,"captionschanged",{})}create(){this.E3()&&this.load();var S;a:{if(this.Y.T("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(S=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const W of S)if(W.kind==="asr"&&W.languageCode===
"en"){S=!0;break a}S=!1}S&&this.X.publish("showpromotooltip",this.Z.element)}jS(){var S=ob(this.player.getAudioTrack(),g.SB(this.Y));var W=S==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Qp(this,this.V):S==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&g9(this)?j1(this):uE(this)||this.V||xaN(this)?Qp(this,this.V):g9(this)?j1(this):null;if(this.B!=="HLS"&&this.j||this.q2){const m=g.Cf(this.N.C,!0);S=[];for(let a=0;a<m.length;a++){const J=m[a],B=g.nX("TRACK");B.setAttribute("kind","subtitles");B.setAttribute("label",
g.V9(J));B.setAttribute("srclang",g.s6(J));B.setAttribute("id",J.toString());this.q2||B.setAttribute("src",this.N.W(J,"vtt"));J===W&&B.setAttribute("default","1");S.push(B)}W=this.X.QT();W.AX(S);S=W.IL();this.d2&&this.vn.L(S.textTracks,"change",this.K3)}else!this.C&&W&&lE(this,W),g.oV(this.player,"onCaptionsTrackListChanged"),g.rJ(this.player,"onApiChange")}getTrackById(S){const W=g.Cf(this.N.C,!0);for(let m=0;m<W.length;m++)if(W[m].toString()===S)return W[m];return null}K3(){const S=this.X.QT().IL().textTracks;
let W=null;for(let m=0;m<S.length;m++)S[m].mode==="showing"&&(W=this.getTrackById(S[m].id));(this.loaded?this.C:null)!==W&&lE(this,W,!0)}tv(){this.N?.A(this.p_)}Ks(){!this.C&&this.j||this.unload()}BL(S,W,m,a){if(S){H0(this,this.C??void 0);this.N.U()&&(this.AX=[],this.X.Zz("captions"),b$(this.GN),this.K_.reset());a:{var J=this.K_;a=a||0;m=Haw(J,S,m||0);S=[];try{for(const x of m){const L=x.trackData,d=x.P3,h=J.Y.T("safari_live_drm_captions_fix");if(typeof L!=="string"){m=S;var B=m.concat;if(h&&jhv(L))var E=
MAv(J,L,d);else{var z=J,y=W,Y=L,G=d,K=a;if(!Tbx(Y))throw Error("Invalid binary caption track data");z.C||(z.C=new y8Q(K,y));E=z.C.B(Y,G)}var T=B.call(m,E)}else{if(L.substring(0,6)==="WEBVTT")var q=S.concat(MAv(J,L,d));else{m=S;var V=m.concat;b:{y=J;z=W;if(L[0]==="{")try{y.C||(y.C=new BYx(Ua9(z)));var X=y.C.B(L,d);break b}catch(kX){g.Z(kX);X=[];break b}const JG=g.aT(L);if(!JG||!JG.firstChild){const kX=Error("Invalid caption track data");kX.params=L;throw kX;}if(JG.firstChild.tagName==="timedtext"){if(Number(JG.firstChild.getAttribute("format"))===
3){Y=JG;y.C||(y.C=new atn(Ua9(z)));X=y.C.B(Y,d);break b}const kX=Error("Unsupported subtitles format in web player (Format2)");kX.params=L;throw kX;}if(JG.firstChild.tagName==="transcript"){const kX=Error("Unsupported subtitles format in web player (Format1)");kX.params=L;throw kX;}const yP=Error("Invalid caption track data");yP.params=L;throw yP;}q=V.call(m,X)}T=q}S=T}var M=S;break a}catch(x){g.OK(J.logger,187101178,`Captions parsing failed: ${x.message}. `);J.clear();M=[];break a}M=void 0}W=M;W.length>
0&&(M=this.C,this.Xf(M,!!M,Op(this)?"g":this.V?"m":"s"));this.player.iQ(W,void 0,this.B==="LIVE"||this.B==="SABR_LIVE");!this.V||this.q2||Op(this)||g.Cs(this.Y)||g.d2(this.Y)||g.CG(this.Y)||this.Y.bY==="shortspage"||this.player.isInline()||(this.cn.f1(),W=Bb9({lV:0,Io:5,PT:5,vc:2,textAlign:0,KW:0,lang:"en"}),this.Hn=[W],M=["Click "," for settings"],this.hX||(J=new g.g$(g.ML()),g.R(this,J),this.hX=J.element),J=W.end-W.start,(T=g.V9(this.C))&&this.Hn.push(new JH(W.start,J,0,W.id,T)),this.Hn.push(new JH(W.start,
J,0,W.id,M[0]),new JH(W.start,J,0,W.id,this.hX,!0),new JH(W.start,J,0,W.id,M[1],!0)),this.player.iQ(this.Hn),this.cn.Db());!this.V||this.q2||Op(this)||(g.SB(this.Y)?Xf(this,!0):v0(this,!0),this.S&&(this.S.j=this.C),this.player.OC());this.V=!1}}onCueRangeEnter(S){this.AX.push(S);b$(this.GN)}onCueRangeExit(S){g.v9(this.AX,S);this.N instanceof okp&&this.N.bY&&this.player.FK([S]);b$(this.GN)}getCaptionWindowContainerId(){return this.Z.element.id}TV(){RNg(this,this.Hn);this.Hn=null}C3(){if(!this.x6||!this.j){this.GN.stop();
g.WF(this.TN);this.AX.sort(g.zS);var S=this.AX;if(this.iY){const W=g.qx(S,function(m){return this.iY.indexOf(m)===-1},this);
W.length&&(S=W)}for(const W of S)W instanceof Ep?Pz8(this,W):fNp(this,W);for(const [W,m]of Object.entries(this.bY)){const a=W,J=m;this.TN[a]?(J.element.parentNode||(J instanceof hNn||J instanceof $aN||g.Gj(this.bY,(B,E)=>{E!==a&&B.N.params.lV===J.N.params.lV&&B.N.params.Io===J.N.params.Io&&B.N.params.PT===J.N.params.PT&&(B.dispose(),delete this.bY[E]);return E===a},this),this.Z.element.appendChild(J.element)),J.Z(this.TN[a])):(J.dispose(),delete this.bY[a])}}}Oh(){nQ(this,{},!0);
g.oV(this.player,"captionssettingschanged")}Ov(){var S=Vp.v1;S={background:S.background,backgroundOpacity:S.backgroundOpacity,charEdgeStyle:S.charEdgeStyle,color:S.color,fontFamily:S.fontFamily,fontSizeIncrement:S.fontSizeIncrement,fontStyle:S.bold&&S.italic?3:S.bold?1:S.italic?2:0,textOpacity:S.textOpacity,windowColor:Vp.windowColor,windowOpacity:Vp.windowOpacity};const W=Cl()||{};W.background!=null&&(S.background=W.background);W.backgroundOverride!=null&&(S.backgroundOverride=W.backgroundOverride);
W.backgroundOpacity!=null&&(S.backgroundOpacity=W.backgroundOpacity);W.backgroundOpacityOverride!=null&&(S.backgroundOpacityOverride=W.backgroundOpacityOverride);W.charEdgeStyle!=null&&(S.charEdgeStyle=W.charEdgeStyle);W.charEdgeStyleOverride!=null&&(S.charEdgeStyleOverride=W.charEdgeStyleOverride);W.color!=null&&(S.color=W.color);W.colorOverride!=null&&(S.colorOverride=W.colorOverride);W.fontFamily!=null&&(S.fontFamily=W.fontFamily);W.fontFamilyOverride!=null&&(S.fontFamilyOverride=W.fontFamilyOverride);
W.fontSizeIncrement!=null&&(S.fontSizeIncrement=W.fontSizeIncrement);W.fontSizeIncrementOverride!=null&&(S.fontSizeIncrementOverride=W.fontSizeIncrementOverride);W.fontStyle!=null&&(S.fontStyle=W.fontStyle);W.fontStyleOverride!=null&&(S.fontStyleOverride=W.fontStyleOverride);W.textOpacity!=null&&(S.textOpacity=W.textOpacity);W.textOpacityOverride!=null&&(S.textOpacityOverride=W.textOpacityOverride);W.windowColor!=null&&(S.windowColor=W.windowColor);W.windowColorOverride!=null&&(S.windowColorOverride=
W.windowColorOverride);W.windowOpacity!=null&&(S.windowOpacity=W.windowOpacity);W.windowOpacityOverride!=null&&(S.windowOpacityOverride=W.windowOpacityOverride);return S}EM(S,W){const m={};Object.assign(m,Cl());Object.assign(m,S);nQ(this,m,W);g.oV(this.player,"captionssettingschanged")}R2(){!this.j&&this.loaded&&(g.EP(this.bY,function(S,W){S.dispose();delete this.bY[W]},this),this.C3())}pJ(S,W){switch(S){case "fontSize":if(isNaN(W))break;
S=g.P$(W,-2,4);this.EM({fontSizeIncrement:S});return S;case "reload":W&&!this.j&&lE(this,this.C,!0);break;case "stickyLoading":W!==void 0&&this.Y.Z&&(g.SB(this.Y)?Xf(this,!!W):v0(this,!!W));break;case "track":return tAZ(this,W);case "tracklist":return this.N?g.F9(g.Cf(this.N.C,!(!W||!W.includeAsr)),m=>g.nN(m)):[];
case "translationLanguages":return this.N?this.N.S.map(m=>Object.assign({},m)):[];
case "sampleSubtitles":this.j||W===void 0||sp(this,!!W);break;case "sampleSubtitlesCustomized":this.j||sp(this,!!W,W);break;case "recommendedTranslationLanguages":return g.kY();case "defaultTranslationSourceTrackIndices":return this.N?this.N.vn:[]}}getOptions(){const S="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.Z&&S.push("stickyLoading");return S}cO(){let S=this.C;if(this.X.CE("captions")){if(this.Y.T("html5_modify_caption_vss_logging"))return(S=this.videoData.Op??
null)?{cc:g.oQX(S)}:{};if(S){let W=S.vssId;S.translationLanguage&&W&&(W=`t${W}.${g.s6(S)}`);return{cc:W}}}return{}}G7(){this.isSubtitlesOn()?(g.SB(this.Y)?Xf(this,!1):v0(this,!1),H0(this),lE(this,null,!0)):this.jG()}jG(){const S=Op(this)||!this.C?Qp(this,!0):this.C;S&&this.hV(S.vssId,"m");this.isSubtitlesOn()||lE(this,Op(this)||!this.C?Qp(this,!0):this.C,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.C&&!Op(this)}sV(){const S=Op(this);g9(this,S)?lE(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.qC()&&(this.V=!1,this.C=null,this.N&&(this.N.dispose(),this.N=null)),this.E3()&&(S?lE(this,Qp(this,!1),!1):this.load()))}KM(S){S&&(this.U={top:S.top,right:S.right,bottom:S.bottom,left:S.left,width:1-S.left-S.right,height:1-S.top-S.bottom},this.Z.element.style.top=`${this.U.top*100}%`,this.Z.element.style.left=`${this.U.left*100}%`,this.Z.element.style.width=`${this.U.width*100}%`,this.Z.element.style.height=`${this.U.height*100}%`,this.Z.element.style.position="absolute",
S=kCw(this))&&(this.Z.element.style.width=`${S.width}px`,this.Z.element.style.height=`${S.height}px`)}onVideoDataChange(S,W){S==="newdata"&&(this.videoData=W,this.loaded&&this.unload(),this.V=!1,this.C=null,this.N&&(this.N.dispose(),this.N=null,g.oV(this.player,"captionschanged",{})),this.E3()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}yc(){const S=this.X.QT();S&&!S.n_()&&S.q2();this.X.isFullscreen()?(this.j=this.ZQ=!0,this.loaded&&this.jS()):(this.ZQ=this.Y.controlsType==="3",
this.j=LWp(this));lE(this,this.C)}g2(){const S=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;S&&g.AJ(this.player,"innertubeCommand",S)}Xf(S,W,m){const a=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let J="";S&&(J=S.vssId,J=J.replace(a,""));let B="";S&&S.getId()&&(B=S.getId()||"");S&&S.getXtags()&&(S=S.getXtags(),S=S.replace(a,""),B=B.concat(`;${S}`));this.B==="HLS"&&(B="");this.X.Xf(W?J:"",W?B:"",m)}hV(S,W){S=(S||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");S.length>0&&this.X.hV(S,W)}});})(_yt_player);
