(function(g){var window=this;'use strict';var $w=function(S){S.publish("autonavvisibility")},PDx=function(S,W){g.AJ(S,"onAutonavCoundownStarted",W)},hH=function(S){return S.isBackground()&&S.O$()},ft9=function(S,W){W=W.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
S.U=W?.navigationEndpoint;W=W?.trackingParams;S.playButton&&W&&S.X.setTrackingParams(S.playButton.element,W)},Ze=function(S){const W=tH(S);
var m=Math,a=m.min;var J=S.V?Date.now()-S.V:0;m=a.call(m,J,W);AH(S,Math.ceil((W-m)/1E3));W-m<=500&&S.C()?S.select(!0):S.C()&&S.S.start()},Ne=function(S){var W=S.X.Cy(!0,S.X.isFullscreen());
g.I(S.container.element,"ytp-autonav-endscreen-small-mode",S.m9(W));g.I(S.container.element,"ytp-autonav-endscreen-is-premium",!!S.suggestion&&!!S.suggestion.fY);g.I(S.X.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!S.X.W1());g.I(S.X.getRootNode(),"countdown-running",S.C());g.I(S.container.element,"ytp-player-content",S.X.W1());g.Zt(S.overlay.element,{width:`${W.width}px`});if(!S.C()){S.X.W1()?AH(S,Math.round(tH(S)/1E3)):AH(S);W=!!S.suggestion&&!!S.suggestion.pA;const m=S.X.W1()||!W;g.I(S.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!m&&W);g.I(S.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",m&&!W);S.W.UV(S.X.W1());g.I(S.element,"ytp-enable-w2w-color-transitions",!!S.X.getVideoData()?.watchToWatchTransitionRenderer)}},AH=function(S,W=-1){S=S.j.I2("ytp-autonav-endscreen-upnext-header");
g.gY(S);if(W>=0){W=String(W);const m="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],a="Up next in $SECONDS".indexOf(m);if(a>=0){S.appendChild(g.sN("Up next in $SECONDS".slice(0,a)));const J=g.nX("span");g.So(J,"ytp-autonav-endscreen-upnext-header-countdown-number");g.XO(J,W);S.appendChild(J);S.appendChild(g.sN("Up next in $SECONDS".slice(a+m.length)));return}}g.XO(S,"Up next")},tH=function(S){return S.X.isFullscreen()?(S=S.X.getVideoData()?.Do,S===-1||S===void 0?8E3:S):S.X.I$()>=0?S.X.I$():
g.kW(S.X.K().experiments,"autoplay_time")||1E4},bE=function(S,W){W=kd$(S,W);
var m=Math,a=m.min;var J=(0,g.t)()-S.V;m=a.call(m,J,W);W=W===0?1:Math.min(m/W,1);S.AX.setAttribute("stroke-dashoffset",`${-211*(W+1)}`);W>=1&&S.C()&&S.api.getPresentingPlayerType()!==3?S.select(!0):S.C()&&S.j.start()},kd$=function(S,W){return W?W:S.api.isFullscreen()?(S=S.api.getVideoData()?.Do,S===-1||S===void 0?8E3:S):S.api.I$()>=0?S.api.I$():g.kW(S.api.K().experiments,"autoplay_time")||1E4},oN=function(S){const W=S.W1();
W!==S.V&&(S.V=W,$w(S.player),S.V?(S.N!==S.C&&S.N.hide(),S.table.hide()):(S.N!==S.C&&S.N.show(),S.table.show()))},r9=function(S){return g.q_(S.player)&&S.j()&&!S.A},CQ=function(S){const W=S.W1();
W!==S.S&&(S.S=W,$w(S.player))},c0=function(S){return g.q_(S.player)&&S.j()&&!S.W},De=function(S){const W=S.W1();
W!==S.bY&&(S.bY=W,$w(S.player))},$1Z=function(S){S=S.K();
return S.tv&&!S.Ar&&!S.disableOrganicUi},h28=function(S){const W=S.player.getVideoData();
if(!W||S.C===W.Ar&&S.N===W.x6)return!1;S.C=W.Ar;S.N=W.x6;return!0},tuZ=function(S){S.player.Zz("endscreen");
var W=S.player.getVideoData();W=new g.jX(Math.max((W.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const m=new g.jX(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});S.player.iQ([W,m])};
g.c5.prototype.I$=g.lc(9,function(){return this.app.I$()});
g.I0.prototype.I$=g.lc(8,function(){return this.getVideoData().vj});
g.CC.prototype.wk=g.lc(7,function(S){this.XK().wk(S)});
g.p7.prototype.wk=g.lc(6,function(S){this.uN!==S&&(this.uN=S,this.UK())});
var A8$=class extends g.c{constructor(S){const W=S.K(),m=W.j;super({G:"a",O:"ytp-autonav-suggestion-card",J:{href:"{{url}}",target:m?W.S:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},D:[{G:"div",Wn:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],J:{style:"{{background}}"},D:[{G:"div",J:{"aria-label":"{{timestamp}}"},Wn:["ytp-autonav-timestamp"],Bn:"{{duration}}"},
{G:"div",Wn:["ytp-autonav-live-stamp"],Bn:"Live"},{G:"div",Wn:["ytp-autonav-upcoming-stamp"],Bn:"Upcoming"},{G:"div",O:"ytp-autonav-list-overlay",D:[{G:"div",O:"ytp-autonav-mix-text",Bn:"Mix"},{G:"div",O:"ytp-autonav-mix-icon"}]}]},{G:"div",Wn:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Bn:"{{title}}"},{G:"div",Wn:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Bn:"{{author}}"},{G:"div",Wn:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
Bn:"{{views_and_publish_time}}"}]});this.X=S;this.suggestion=null;this.C=m;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.X.HA(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.V0||void 0)&&this.X.logClick(this.element)}onClick(S){g.HY(S,this.X,this.C,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(S){switch(S.keyCode){case 13:case 32:S.defaultPrevented||(this.select(),S.preventDefault())}}};var w9=class extends g.c{constructor(S,W=!1){super({G:"div",O:"ytp-autonav-endscreen-countdown-overlay"});this.cn=W;this.cancelCommand=this.U=void 0;this.V=0;this.container=new g.c({G:"div",O:"ytp-autonav-endscreen-countdown-container"});g.R(this,this.container);this.container.Xn(this.element);W=S.K();const m=W.j;this.X=S;this.suggestion=null;this.onVideoDataChange("newdata",this.X.getVideoData());this.L(S,"videodatachange",this.onVideoDataChange);this.j=new g.c({G:"div",O:"ytp-autonav-endscreen-upnext-container",
J:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},D:[{G:"div",O:"ytp-autonav-endscreen-upnext-header"},{G:"div",O:"ytp-autonav-endscreen-upnext-alternative-header",Bn:"{{autoplayAlternativeHeader}}"},{G:"a",O:"ytp-autonav-endscreen-link-container",J:{href:"{{url}}",target:m?W.S:""},D:[{G:"div",O:"ytp-autonav-endscreen-upnext-thumbnail",J:{style:"{{background}}"},D:[{G:"div",J:{"aria-label":"{{timestamp}}"},
Wn:["ytp-autonav-timestamp"],Bn:"{{duration}}"},{G:"div",Wn:["ytp-autonav-live-stamp"],Bn:"Live"},{G:"div",Wn:["ytp-autonav-upcoming-stamp"],Bn:"Upcoming"}]},{G:"div",O:"ytp-autonav-endscreen-video-info",D:[{G:"div",O:"ytp-autonav-endscreen-premium-badge"},{G:"div",O:"ytp-autonav-endscreen-upnext-title",Bn:"{{title}}"},{G:"div",O:"ytp-autonav-endscreen-upnext-author",Bn:"{{author}}"},{G:"div",O:"ytp-autonav-view-and-date",Bn:"{{views_and_publish_time}}"},{G:"div",O:"ytp-autonav-author-and-view",Bn:"{{author_and_views}}"}]}]}]});
g.R(this,this.j);this.j.Xn(this.container.element);m||this.L(this.j.I2("ytp-autonav-endscreen-link-container"),"click",this.vn);this.X.createClientVe(this.container.element,this,115127);this.X.createClientVe(this.j.I2("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.c({G:"div",O:"ytp-autonav-overlay"});g.R(this,this.overlay);this.overlay.Xn(this.container.element);this.W=new g.c({G:"div",O:"ytp-autonav-endscreen-button-container"});g.R(this,this.W);this.W.Xn(this.container.element);
this.cancelButton=new g.c({G:"button",Wn:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],J:{"aria-label":"Cancel autoplay"},Bn:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.Xn(this.W.element);this.cancelButton.listen("click",this.AX,this);this.X.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.c({G:"a",Wn:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],J:{href:"{{url}}",role:"button","aria-label":"Play next video"},Bn:"Play Now"});g.R(this,this.playButton);this.playButton.Xn(this.W.element);this.playButton.listen("click",this.vn,this);this.X.createServerVe(this.playButton.element,this.playButton,!0);(W=this.X.getVideoData())&&ft9(this,W);this.S=new g.rr(()=>{Ze(this)},500);
g.R(this,this.S);this.bY();this.L(S,"autonavvisibility",this.bY);this.X.T("web_autonav_color_transition")&&(this.L(S,"autonavchange",this.q2),this.L(S,"onAutonavCoundownStarted",this.GN))}Z(S){this.suggestion!==S&&(this.suggestion=S,g.mk(this.j,S),this.playButton.updateValue("url",this.suggestion.nk()),Ne(this))}C(){return this.V>0}A(){this.C()||(this.V=Date.now(),Ze(this),PDx(this.X,tH(this)),g.I(this.X.getRootNode(),"countdown-running",this.C()))}B(){this.N();Ze(this);const S=this.j.I2("ytp-autonav-endscreen-upnext-header");
S&&g.XO(S,"Up next")}N(){this.C()&&(this.S.stop(),this.V=0)}select(S=!1){this.X.nextVideo(!1,S);this.N()}vn(S){g.HY(S,this.X)&&(S.currentTarget===this.playButton.element?this.X.logClick(this.playButton.element):S.currentTarget===this.j.I2("ytp-autonav-endscreen-link-container")&&(S=this.j.I2("ytp-autonav-endscreen-link-container"),this.X.logVisibility(S,!0),this.X.logClick(S)),this.U?(g.AJ(this.X,"innertubeCommand",this.U),this.N()):this.select())}AX(){this.X.logClick(this.cancelButton.element);g.BY(this.X,
!0);this.cancelCommand&&g.AJ(this.X,"innertubeCommand",this.cancelCommand)}onVideoDataChange(S,W){ft9(this,W);this.cancelCommand=W.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}GN(S){if(this.X.getVideoData()?.watchToWatchTransitionRenderer){var W=this.X.getVideoData().watchToWatchTransitionRenderer;const m=W?.fromColorPaletteDark,a=W?.toColorPaletteDark;m&&a&&(W=this.element,W.style.setProperty("--w2w-start-background-color",
g.cz(m.surgeColor)),W.style.setProperty("--w2w-start-primary-text-color",g.cz(m.primaryTitleColor)),W.style.setProperty("--w2w-start-secondary-text-color",g.cz(m.secondaryTitleColor)),W.style.setProperty("--w2w-end-background-color",g.cz(a.surgeColor)),W.style.setProperty("--w2w-end-primary-text-color",g.cz(a.primaryTitleColor)),W.style.setProperty("--w2w-end-secondary-text-color",g.cz(a.secondaryTitleColor)),W.style.setProperty("--w2w-animation-duration",`${S}ms`));g.I(this.element,"ytp-w2w-animate",
!0)}}q2(S){this.X.T("web_autonav_color_transition")&&S!==2&&g.I(this.element,"ytp-w2w-animate",!1)}bY(){const S=this.X.W1();this.cn&&this.jg!==S&&this.UV(S);Ne(this);this.X.logVisibility(this.container.element,S);this.X.logVisibility(this.cancelButton.element,S);this.X.logVisibility(this.j.I2("ytp-autonav-endscreen-link-container"),S);this.X.logVisibility(this.playButton.element,S)}m9(S){return S.width<400||S.height<459}};var S5=class extends g.c{constructor(S,W){super({G:"div",Wn:["html5-endscreen","ytp-player-content",W||"base-endscreen"]});this.created=!1;this.player=S}create(){this.created=!0}destroy(){this.created=!1}j(){return!1}W1(){return!1}U(){return!1}};var WK=class extends g.c{constructor(S){super({G:"div",Wn:["ytp-upnext","ytp-player-content"],J:{"aria-label":"{{aria_label}}"},D:[{G:"div",O:"ytp-cued-thumbnail-overlay-image",J:{style:"{{background}}"}},{G:"span",O:"ytp-upnext-top",D:[{G:"span",O:"ytp-upnext-header",Bn:"Up Next"},{G:"span",O:"ytp-upnext-title",Bn:"{{title}}"},{G:"span",O:"ytp-upnext-author",Bn:"{{author}}"}]},{G:"a",O:"ytp-upnext-autoplay-icon",J:{role:"button",href:"{{url}}","aria-label":"Play next video"},D:[{G:"svg",J:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},D:[{G:"circle",O:"ytp-svg-autoplay-circle",J:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",O:"ytp-svg-autoplay-ring",J:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",O:"ytp-svg-fill",J:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",O:"ytp-upnext-bottom",D:[{G:"span",O:"ytp-upnext-cancel"},
{G:"span",O:"ytp-upnext-paused",Bn:"Autoplay is paused"}]}]});this.api=S;this.cancelButton=null;this.AX=this.I2("ytp-svg-autoplay-ring");this.S=this.notification=this.j=this.suggestion=null;this.U=new g.rr(this.W,5E3,this);this.V=0;var W=this.I2("ytp-upnext-cancel");this.cancelButton=new g.c({G:"button",Wn:["ytp-upnext-cancel-button","ytp-button"],J:{tabindex:"0","aria-label":"Cancel autoplay"},Bn:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.listen("click",this.vn,this);this.cancelButton.Xn(W);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.R(this,this.U);this.api.createClientVe(this.element,this,18788);W=this.I2("ytp-upnext-autoplay-icon");this.L(W,"click",this.q2);this.api.createClientVe(W,this,115130);this.bY();this.L(S,"autonavvisibility",this.bY);this.L(S,"mdxnowautoplaying",this.GN);this.L(S,"mdxautoplaycanceled",this.cn);g.I(this.element,"ytp-upnext-mobile",this.api.K().N)}W(){this.notification&&(this.U.stop(),this.Zb(this.S),this.S=null,this.notification.close(),
this.notification=null)}Z(S){this.suggestion=S;g.mk(this,S,"hqdefault.jpg")}bY(){this.UV(this.api.W1());this.api.logVisibility(this.element,this.api.W1());this.api.logVisibility(this.I2("ytp-upnext-autoplay-icon"),this.api.W1());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.W1())}Hn(){window.focus();this.W()}A(S){this.C()||(g.G3("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.V=(0,g.t)(),this.j=new g.rr(()=>{bE(this,S)},25),bE(this,S),PDx(this.api,kd$(this,
S)));
g.J$(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}C(){return!!this.j}B(){this.N();this.V=(0,g.t)();bE(this);g.my(this.element,"ytp-upnext-autoplay-paused")}N(){this.C()&&(this.j.dispose(),this.j=null)}select(S=!1){if(this.api.K().T("autonav_notifications")&&S&&window.Notification&&typeof document.hasFocus==="function"){const W=Notification.permission;W==="default"?Notification.requestPermission():W!=="granted"||document.hasFocus()||(this.W(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.Zf()}),this.S=this.L(this.notification,"click",this.Hn),this.U.start())}this.N();this.api.nextVideo(!1,S)}q2(S){!g.QK(this.cancelButton.element,S.target)&&g.HY(S,this.api)&&(this.api.W1()&&this.api.logClick(this.I2("ytp-upnext-autoplay-icon")),this.select())}vn(){this.api.W1()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.BY(this.api,!0)}GN(S){this.api.getPresentingPlayerType();this.show();this.A(S)}cn(){this.api.getPresentingPlayerType();
this.N();this.hide()}j9(){this.N();this.W();super.j9()}};var NYp=class extends S5{constructor(S){super(S,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.c({G:"div",O:"ytp-suggestion-panel",D:[{G:"div",Wn:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Bn:"More videos"}]});this.S=new g.c({G:"div",O:"ytp-suggestions-container"});this.videos=[];this.B=null;this.V=this.Z=!1;this.N=new w9(this.player);g.R(this,this.N);this.N.Xn(this.element);S.getVideoData().x6?this.C=this.N:(this.C=new WK(S),g.TJ(this.player,
this.C.element,4),g.R(this,this.C));this.overlay=new g.c({G:"div",O:"ytp-autonav-overlay-cancelled-state"});g.R(this,this.overlay);this.overlay.Xn(this.element);this.A=new g.JC(this);g.R(this,this.A);g.R(this,this.table);this.table.Xn(this.element);this.table.show();g.R(this,this.S);this.S.Xn(this.table.element);this.hide()}create(){super.create();this.A.L(this.player,"appresize",this.W);this.A.L(this.player,"onVideoAreaChange",this.W);this.A.L(this.player,"videodatachange",this.onVideoDataChange);
this.A.L(this.player,"autonavchange",this.bY);this.A.L(this.player,"onAutonavCancelled",this.vn);this.onVideoDataChange()}show(){super.show();(this.Z||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.BY(this.player,!1);g.q_(this.player)&&this.j()&&!this.B?(oN(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||hH(this.player.MP())&&this.player.T("web_player_pip_logging_fix")?this.C.select(!0):this.C.A():this.videoData.autonavState===3&&this.C.B()):(g.BY(this.player,
!0),oN(this));this.W()}hide(){super.hide();this.C.B();oN(this)}W(){var S=this.player.Cy(!0,this.player.isFullscreen());oN(this);Ne(this.N);g.I(this.element,"ytp-autonav-cancelled-small-mode",this.m9(S));g.I(this.element,"ytp-autonav-cancelled-tiny-mode",this.MY(S));g.I(this.element,"ytp-autonav-cancelled-mini-mode",S.width<=400||S.height<=360);this.overlay&&g.Zt(this.overlay.element,{width:`${S.width}px`});if(!this.V)for(S=0;S<this.videos.length;S++)g.I(this.videos[S].element,"ytp-suggestion-card-with-margin",
S%2===1)}onVideoDataChange(){var S=this.player.getVideoData();if(this.videoData!==S&&S){this.videoData=S;S=this.videoData.suggestions;var W=this.videoData.iY();W&&(this.C.Z(W),this.C!==this.N&&this.N.Z(W));if(S&&S.length)for(let a=0;a<ZX9.length;++a){var m=ZX9[a];S&&S[m]&&(this.videos[a]=new A8$(this.player),W=this.videos[a],m=S[m],W.suggestion!==m&&(W.suggestion=m,g.mk(W,m)),g.R(this,this.videos[a]),this.videos[a].Xn(this.S.element))}this.W()}}bY(S){S===1?(this.Z=!1,this.B=this.videoData.clientPlaybackNonce,
this.C.N(),this.jg&&this.W()):(this.Z=!0,this.W1()&&(S===2?this.C.A():S===3&&this.C.B()))}vn(S){S?this.bY(1):(this.B=null,this.Z=!1)}j(){return this.videoData.autonavState!==1}m9(S){return(S.width<910||S.height<459)&&!this.MY(S)&&!(S.width<=400||S.height<=360)}MY(S){return S.width<800&&!(S.width<=400||S.height<=360)}W1(){return this.jg&&g.q_(this.player)&&this.j()&&!this.B}},ZX9=[1,3,2,4];var bXn=class extends S5{constructor(S){super(S,"videowall-endscreen");this.X=S;this.stills=[];this.A=this.videoData=null;this.W=this.S=!1;this.bY=null;g.my(this.element,"modern-videowall-endscreen");this.N=new g.JC(this);g.R(this,this.N);this.V=new g.rr(()=>{g.my(this.element,"ytp-show-tiles")},0);
g.R(this,this.V);this.table=new g.g$({G:"div",O:"ytp-modern-endscreen-content"});g.R(this,this.table);this.table.Xn(this.element);S.getVideoData().x6?this.C=new w9(S,!0):this.C=new WK(S);g.R(this,this.C);g.TJ(this.player,this.C.element,4);S.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var S=this.player.getVideoData();S&&(this.videoData=S);this.B();this.N.L(this.player,"appresize",this.B);this.N.L(this.player,"onVideoAreaChange",this.B);this.N.L(this.player,"videodatachange",
this.onVideoDataChange);this.N.L(this.player,"autonavchange",this.Z);this.N.L(this.player,"onAutonavCancelled",this.vn);S=this.videoData.autonavState;S!==this.bY&&this.Z(S);this.N.L(this.element,"transitionend",this.q2)}destroy(){g.Bp(this.N);g.aC(this.stills);this.stills=[];super.destroy();g.J$(this.element,"ytp-show-tiles");this.V.stop();this.bY=this.videoData.autonavState}j(){return this.videoData.autonavState!==1}show(){const S=this.jg;super.show();g.J$(this.element,"ytp-show-tiles");this.player.K().N?
g.CK(this.V):this.V.start();(this.W||this.A&&this.A!==this.videoData.clientPlaybackNonce)&&g.BY(this.player,!1);r9(this)?(CQ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||hH(this.player.MP())&&this.player.T("web_player_pip_logging_fix")?this.C.select(!0):this.C.A():this.videoData.autonavState===3&&this.C.B()):(g.BY(this.player,!0),CQ(this));S!==this.jg&&this.player.logVisibility(this.element,!0)}hide(){const S=this.jg;super.hide();this.C.B();CQ(this);S!==this.jg&&this.player.logVisibility(this.element,
!1)}q2(S){S.target===this.element&&this.B()}B(){const S=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.iY()];if(S.length){var W=this.X.Cy(!0,this.X.isFullscreen()),m=Math.floor((W.width-64+16)/(g.P$(W.width*.27,250,450)+16));W=Math.min(3,Math.floor((W.height-64)/((W.width-64-(m-1)*16)/m*.5625+70)));g.BL(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.my(this.element,`ytp-modern-endscreen-limit-rows-${W}`);
g.I(this.element,"ytp-modern-endscreen-single-item",m===1);g.I(this.element,"ytp-modern-endscreen-row-0",W===0);m=this.table.element;m.ariaLive="polite";this.C.Z(this.videoData.iY());this.C instanceof w9&&Ne(this.C);g.I(this.element,"ytp-endscreen-takeover",r9(this));CQ(this);W=0;m.ariaBusy="true";var a=S.length;for(let J=0;J<a;J++){const B=J%a;let E=this.stills[J];E||(E=new g.E4j(this.player),this.stills[J]=E,m.appendChild(E.element));g.AK7(E,S[B]);W++}this.stills.length=W}}onVideoDataChange(){const S=
this.player.getVideoData(1);this.videoData!==S&&(S?.iY()?(this.videoData=S,this.B()):this.player.N2("missg",{vid:S?.videoId||"",cpn:S?.clientPlaybackNonce||""}))}U(){return this.C.C()}Z(S){S===1?(this.W=!1,this.A=this.videoData.clientPlaybackNonce,this.C.N(),this.jg&&this.B()):(this.W=!0,this.jg&&r9(this)&&(S===2?this.C.A():S===3&&this.C.B()))}vn(S){if(S){for(S=0;S<this.stills.length;S++)this.X.logVisibility(this.stills[S].element,!0);this.Z(1)}else this.A=null,this.W=!1;this.B()}W1(){return this.jg&&
r9(this)}};var ogp=class extends S5{constructor(S){super(S,"subscribecard-endscreen");this.C=new g.c({G:"div",O:"ytp-subscribe-card",D:[{G:"img",O:"ytp-author-image",J:{src:"{{profilePicture}}"}},{G:"div",O:"ytp-subscribe-card-right",D:[{G:"div",O:"ytp-author-name",Bn:"{{author}}"},{G:"div",O:"html5-subscribe-button-container"}]}]});g.R(this,this.C);this.C.Xn(this.element);const W=S.getVideoData();this.subscribeButton=new g.rW("Subscribe",null,"Unsubscribe",null,!0,!1,W.zz,W.subscribed,"trailer-endscreen",null,
S,!1);g.R(this,this.subscribeButton);this.subscribeButton.Xn(this.C.I2("html5-subscribe-button-container"));this.L(S,"videodatachange",this.zN);this.zN();this.hide()}zN(){const S=this.player.getVideoData();this.C.update({profilePicture:S.profilePicture,author:S.author});this.subscribeButton.channelId=S.zz;var W=this.subscribeButton;S.subscribed?W.C():W.N()}};var r8n=class extends g.c{constructor(S){const W=S.K(),m=g.rE||g.Jm?{style:"will-change: opacity"}:void 0,a=W.j,J=["ytp-videowall-still"];W.N&&J.push("ytp-videowall-show-text");super({G:"a",Wn:J,J:{href:"{{url}}",target:a?W.S:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},D:[{G:"div",O:"ytp-videowall-still-image",J:{style:"{{background}}"}},{G:"span",O:"ytp-videowall-still-info",J:{"aria-hidden":"true"},D:[{G:"span",O:"ytp-videowall-still-info-bg",
D:[{G:"span",O:"ytp-videowall-still-info-content",J:m,D:[{G:"span",O:"ytp-videowall-still-info-title",Bn:"{{title}}"},{G:"span",O:"ytp-videowall-still-info-author",Bn:"{{author_and_views}}"},{G:"span",O:"ytp-videowall-still-info-live",Bn:"Live"},{G:"span",O:"ytp-videowall-still-info-duration",Bn:"{{duration}}"}]}]}]},{G:"span",Wn:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},D:[{G:"span",O:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",
O:"ytp-videowall-still-listlabel-length",D:[" (",{G:"span",Bn:"{{playlist_length}}"},")"]}]},{G:"span",Wn:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},D:[{G:"span",O:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",O:"ytp-videowall-still-listlabel-length",Bn:" (50+)"}]}]});this.suggestion=null;this.N=a;this.api=S;this.C=new g.JC(this);g.R(this,this.C);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.C.L(S,"videodatachange",
this.onVideoDataChange);S.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.HA(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.V0||void 0)&&this.api.logClick(this.element)}onClick(S){if(g.kE(this.api.K())&&this.api.T("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let W=this.suggestion.nk();const m={};g.Y5(this.api,m);W=g.u9(W,m);g.lh(W,this.api,S)}else g.HY(S,this.api,
this.N,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(S){switch(S.keyCode){case 13:case 32:S.defaultPrevented||(this.select(),S.preventDefault())}}onVideoDataChange(){const S=this.api.getVideoData(),W=this.api.K();this.N=S.i$?!1:W.j}};var CDN=class extends S5{constructor(S){super(S,"videowall-endscreen");this.X=S;this.A=0;this.stills=[];this.W=this.videoData=null;this.V=this.bY=!1;this.vn=null;this.B=new g.JC(this);g.R(this,this.B);this.Z=new g.rr(()=>{g.my(this.element,"ytp-show-tiles")},0);
g.R(this,this.Z);var W=new g.c({G:"button",Wn:["ytp-button","ytp-endscreen-previous"],J:{"aria-label":"Previous"},D:[g.Vf()]});g.R(this,W);W.Xn(this.element);W.listen("click",this.GN,this);this.table=new g.g$({G:"div",O:"ytp-endscreen-content"});g.R(this,this.table);this.table.Xn(this.element);W=new g.c({G:"button",Wn:["ytp-button","ytp-endscreen-next"],J:{"aria-label":"Next"},D:[g.nG()]});g.R(this,W);W.Xn(this.element);W.listen("click",this.AX,this);S.getVideoData().x6?this.C=new w9(S,!0):this.C=
new WK(S);g.R(this,this.C);g.TJ(this.player,this.C.element,4);S.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var S=this.player.getVideoData();S&&(this.videoData=S);this.N();this.B.L(this.player,"appresize",this.N);this.B.L(this.player,"onVideoAreaChange",this.N);this.B.L(this.player,"videodatachange",this.onVideoDataChange);this.B.L(this.player,"autonavchange",this.S);this.B.L(this.player,"onAutonavCancelled",this.q2);S=this.videoData.autonavState;S!==this.vn&&this.S(S);
this.B.L(this.element,"transitionend",this.cn)}destroy(){g.Bp(this.B);g.aC(this.stills);this.stills=[];super.destroy();g.J$(this.element,"ytp-show-tiles");this.Z.stop();this.vn=this.videoData.autonavState}j(){return this.videoData.autonavState!==1}show(){const S=this.jg;super.show();g.J$(this.element,"ytp-show-tiles");this.player.K().N?g.CK(this.Z):this.Z.start();(this.V||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.BY(this.player,!1);c0(this)?(De(this),this.videoData.autonavState===2?
this.player.getVisibilityState()===3||hH(this.player.MP())&&this.player.T("web_player_pip_logging_fix")?this.C.select(!0):this.C.A():this.videoData.autonavState===3&&this.C.B()):(g.BY(this.player,!0),De(this));S!==this.jg&&this.player.logVisibility(this.element,!0)}hide(){const S=this.jg;super.hide();this.C.B();De(this);S!==this.jg&&this.player.logVisibility(this.element,!1)}cn(S){S.target===this.element&&this.N()}N(){var S=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.iY()];
if(S.length){g.my(this.element,"ytp-endscreen-paginate");var W=this.X.Cy(!0,this.X.isFullscreen()),m=g.DI(this.X);m&&(m=m.aU()?48:32,W.width-=m*2);var a=W.width/W.height,J=96/54,B=m=2,E=Math.max(W.width/96,2),z=Math.max(W.height/54,2),y=S.length;var Y=y*4;for(Y-=4;Y>0&&(m<E||B<z);){var G=m/2,K=B/2,T=m<=E-2&&Y>=K*4,q=B<=z-2&&Y>=G*4;if((G+1)/K*J/a>a/(G/(K+1)*J)&&q)Y-=G*4,B+=2;else if(T)Y-=K*4,m+=2;else if(q)Y-=G*4,B+=2;else break}J=!1;Y>=12&&y*4-Y<=6&&(B>=4||m>=4)&&(J=!0);Y=m*96;E=B*54;a=Y/E<a?W.height/
E:W.width/Y;a=Math.min(a,2);Y=Math.floor(Math.min(W.width,Y*a));E=Math.floor(Math.min(W.height,E*a));W=this.table.element;W.ariaLive="polite";g.z6(W,Y,E);g.Zt(W,{marginLeft:`${Y/-2}px`,marginTop:`${E/-2}px`});this.C.Z(this.videoData.iY());this.C instanceof w9&&Ne(this.C);g.I(this.element,"ytp-endscreen-takeover",c0(this));De(this);Y+=4;E+=4;a=0;W.ariaBusy="true";for(z=0;z<m;z++)for(G=0;G<B;G++)if(T=a,q=0,J&&z>=m-2&&G>=B-2?q=1:G%2===0&&z%2===0&&(G<2&&z<2?G===0&&z===0&&(q=2):q=2),T=g.fa(T+this.A,y),
q!==0){K=this.stills[a];K||(K=new r8n(this.player),this.stills[a]=K,W.appendChild(K.element));var V=Math.floor(E*G/B);const X=Math.floor(Y*z/m),M=Math.floor(E*(G+q)/B)-V-4,x=Math.floor(Y*(z+q)/m)-X-4;g.Dt(K.element,X,V);g.z6(K.element,x,M);g.Zt(K.element,"transitionDelay",(G+z)/20+"s");g.I(K.element,"ytp-videowall-still-mini",q===1);g.I(K.element,"ytp-videowall-still-large",q>2);q=Math.max(x,M);g.I(K.element,"ytp-videowall-still-round-large",q>=256);g.I(K.element,"ytp-videowall-still-round-medium",
q>96&&q<256);g.I(K.element,"ytp-videowall-still-round-small",q<=96);T=S[T];K.suggestion!==T&&(K.suggestion=T,q=K.api.K(),V=g.WL(K.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.mk(K,T,V),g.kE(q)&&!K.api.T("web_player_log_click_before_generating_ve_conversion_params")&&(q=T.nk(),V={},g.bI(K.api,"addEmbedsConversionTrackingParams",[V]),q=g.u9(q,V),K.updateValue("url",q)),(T=(T=T.sessionData)&&T.itct)&&K.api.setTrackingParams(K.element,T));a++}W.ariaBusy="false";g.I(this.element,
"ytp-endscreen-paginate",a<y);for(S=this.stills.length-1;S>=a;S--)m=this.stills[S],g.ju(m.element),g.md(m);this.stills.length=a}}onVideoDataChange(){const S=this.player.getVideoData(1);this.videoData!==S&&(S?.iY()?(this.A=0,this.videoData=S,this.N()):this.player.N2("missg",{vid:S?.videoId||"",cpn:S?.clientPlaybackNonce||""}))}AX(){this.A+=this.stills.length;this.N()}GN(){this.A-=this.stills.length;this.N()}U(){return this.C.C()}S(S){S===1?(this.V=!1,this.W=this.videoData.clientPlaybackNonce,this.C.N(),
this.jg&&this.N()):(this.V=!0,this.jg&&c0(this)&&(S===2?this.C.A():S===3&&this.C.B()))}q2(S){if(S){for(S=0;S<this.stills.length;S++)this.X.logVisibility(this.stills[S].element,!0);this.S(1)}else this.W=null,this.V=!1;this.N()}W1(){return this.jg&&c0(this)}};var c88=class extends g.c{constructor(S){super({G:"button",Wn:["ytp-watch-on-youtube-button","ytp-button"],Bn:"{{content}}"});this.X=S;this.buttonType=this.buttonType=1;this.C();this.buttonType===2&&g.my(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.C);this.UV(!0)}C(){let S,W;switch(this.buttonType){case 1:S="Watch again on YouTube";W=156915;break;case 2:S="Continue watching on YouTube";W=156942;break;default:S="Continue watching on YouTube",
W=156942}this.update({content:S});this.X.hasVe(this.element)&&this.X.destroyVe(this.element);this.X.createClientVe(this.element,this,W)}onClick(S){this.X.T("web_player_log_click_before_generating_ve_conversion_params")&&this.X.logClick(this.element);g.lh(this.getVideoUrl(),this.X,S);this.X.T("web_player_log_click_before_generating_ve_conversion_params")||this.X.logClick(this.element)}getVideoUrl(){var S=!0;switch(this.buttonType){case 1:S=!0;break;case 2:S=!1}S=this.X.getVideoUrl(S,!1,!1,!0);const W=
this.X.K();if(g.kE(W)){const m={};g.kE(W)&&g.bI(this.X,"addEmbedsConversionTrackingParams",[m]);S=g.u9(S,m)}return S}logVisibility(){this.X.logVisibility(this.element,this.jg&&this.iY)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}vU(S){super.vU(S);this.logVisibility()}};var D1n=class extends S5{constructor(S){super(S,"watch-again-on-youtube-endscreen");this.watchButton=new c88(S);g.R(this,this.watchButton);this.watchButton.Xn(this.element);g.w8K(S)&&(this.C=new g.AG9(S),g.R(this,this.C),this.N=new g.c({G:"div",Wn:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],J:{tabIndex:"-1"},D:[this.C]}),g.R(this,this.N),this.C.Xn(this.N.element),this.N.Xn(this.element));S.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.C?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const W=this.N;if(W){var S=this.C.hasSuggestions();g.I(this.element,"ytp-shorts-branded-ui",S);S?W.show():W.hide()}g.DI(this.player)?.wk(!0);this.player.logVisibility(this.element,!0);this.watchButton.vU(!0)}}hide(){super.hide();g.DI(this.player)?.wk(!1);this.player.logVisibility(this.element,!1);this.watchButton.vU(!1)}};g.FL("endscreen",class extends g.gL{constructor(S){super(S);this.endScreen=null;this.C=this.N=this.B=!1;this.listeners=new g.JC(this);g.R(this,this.listeners);const W=S.K();S.isEmbedsShortsMode()?this.endScreen=new D1n(S):$1Z(S)?(this.B=!0,h28(this),this.C?this.endScreen=new NYp(S):W.T("delhi_modern_endscreen")?this.endScreen=new bXn(S):this.endScreen=new CDN(S)):W.Ar?this.endScreen=new ogp(S):this.endScreen=new S5(S);g.R(this,this.endScreen);g.TJ(S,this.endScreen.element,4);tuZ(this);this.listeners.L(S,
"videodatachange",this.onVideoDataChange,this);this.listeners.L(S,g.yC("endscreen"),m=>{this.onCueRangeEnter(m)});
this.listeners.L(S,g.Yf("endscreen"),m=>{this.onCueRangeExit(m)})}E3(){var S=this.player.getVideoData();
const W=S.mutedAutoplay&&(S.limitedPlaybackDurationInSeconds>0||S.endSeconds>0||S.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!W)return!0;var m=!(!S?.iY()&&!S?.suggestions?.length);m=!$1Z(this.player)||m;S=S.HW;const a=this.player.IH();return m&&!S&&!a&&!W}W1(){return this.endScreen.W1()}BI(){return this.W1()?this.endScreen.U():!1}j9(){this.player.Zz("endscreen");super.j9()}load(){{const m=this.player.getVideoData(),a=m.transitionEndpointAtEndOfStream;if(a&&a.videoId){var S=
this.player.Pv().H1.get("heartbeat");var W=m.iY();!W||a.videoId!==W.videoId||m.H9?(this.player.HA(a.videoId,void 0,void 0,!0,!0,a),S&&S.Ir("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),S=!0):S=!1}else S=!1}S||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(S){this.E3()&&(this.endScreen.created||this.endScreen.create(),S.getId()==="load"&&this.load())}onCueRangeExit(S){S.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){tuZ(this);this.B&&h28(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.C?this.endScreen=new NYp(this.player):this.endScreen=new CDN(this.player),g.R(this,this.endScreen),g.TJ(this.player,this.endScreen.element,4))}});})(_yt_player);
